@startuml PopBindTag
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "PopBind 😃" as bind
    participant "...Tag 😃" as tag
    participant "Binds 🪣" as binds
end box


wallet -> bind: PopBind 🔆 {bind, vault}

activate bind    
    wallet -> bind: "tag"
    bind -> tag: RUN {bind.*}
deactivate bind

activate tag
    tag -> wallet: TEXT 🔠 "tag?"
    tag -> binds: SAVE 💾 {tag}
    tag -> wallet: DONE ✅ "changed"
    tag -> : GOODBYE 👋
deactivate tag
 
@enduml 
