@startuml Saved@Broker

 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Saved 🐌" as broker
    participant "Wallets 🪣" as wallets
    'participant "Offers 🪣" as offers
    participant "Tokens 🪣" as tokens
end box
'participant "Issuer 🎴" as issuer


activate wallet
    wallet -> broker: Saved 🐌 {issuer, token}
deactivate wallet

activate broker
    broker -> wallets: READ 🧲 {from}
    broker -> tokens: READ 🧲 {issuer, token}
    broker -> tokens: SAVE 💾 {SAVED}
deactivate broker

'activate tokens
'    tokens --> issuer: SEND 📬 {Accepted 🐌}
'deactivate tokens


@enduml 
