

@startuml Bio Issues

title
    👉 Issue biometric token
end title

legend top
    Details:
    * Issue a printable Token QR with an embedded biometric hash.
    * The Token is always signed by the issuer.
    * It's signed over the hash and codes provided by other domains.
    
    Use case: 
    * a citizen with an old physical passport from the local government

    Step:
        1. User logs in to the gov website, 
            and binds the gov domain with the digital wallet. 
        2. User goes to a biometric scanning center to collect bio hashes,
            and binds the center to the wallet. 
        3. User logs in into an issuer authority’s website (e.g., home office),
            and shares the bindings with the gov and the bio scanning center. 
        4. The issuer fetches passport details and hashes from the gov and bio 
            center vaults, merges them in a token, signs it, and issues it to the citizen. 
        5. The citizen can print the QR and scan it on any official site, 
            followed by a face scan to confirm if it’s the right person entering the building.

end legend

' ------------------
actor "User" as user
participant "👱🤵 Wallet \n& Broker" as wallet
participant "Authority\n(local gov)" as auth
participant "BioReader\n(center)" as bio
participant "🃏 Issuer\n(domain)" as issuer

' Bind Authority
user --> auth: check-in()
activate auth
    auth --> wallet: bindable(doc)
    activate wallet
        user --> wallet: bind()
        wallet --> auth: bind()
    deactivate wallet
deactivate auth

' Scan biometrics
user --> bio: 👟 walk-in...
activate bio
    bio -> bio: tap()

    bio --> wallet: bindable(hash)
    activate wallet
        user --> wallet: bind()
        wallet --> bio: bind()
    deactivate wallet

deactivate bio

' Issue token
user --> issuer: check-in()
activate issuer
    issuer --> wallet: query(doc, hash)
    activate wallet
        user --> wallet: share()
        
        wallet --> auth: disclose(doc)
        activate auth
            auth --> issuer: consume(doc)
        deactivate auth
        
        wallet --> bio: disclose(hash)
        activate bio
            bio --> issuer: consume()
        deactivate bio

        issuer --> wallet: issue(token)

        ' Accept token
        user --> wallet: accept()
        wallet -> issuer: download()

    deactivate wallet
deactivate issuer



' ------------------
@enduml

