@startuml SHARE
 
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker
    participant "Consumer 💼" as consumer
end box

box Itemizer 🛢  #FFFFFA
    participant "Hooks" as hooks
end box

participant "Broker 🤵" as broker
participant "Vault 🗄️" as vault

activate script
    script -> talker: SHARE 💼 \n {schemas}
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {hook}
    talker --> broker: SEND 📬 {Query 🐌 hook, schemas}
    activate broker
    talker -> talker: WAIT {hook}
deactivate talker

    broker -> vault: Disclose 🐌
deactivate broker

activate vault

    vault -> consumer: Context 🚀 {hook}

    activate consumer
        consumer -> hooks: GET 🧲 {hook}
        consumer -> vault: {context, schema}
    deactivate consumer

    vault --> consumer: Consume 🐌 {hook, schema, collection}
deactivate vault

activate consumer
    consumer -> vault: Collect 🚀 {collection}

    activate vault
        vault -> consumer: {data}
    deactivate vault

    consumer -> talker: REEL 🎣 {hook, data}
deactivate consumer

activate talker
    talker -> script: RETURN \n{schema, data}
deactivate talker

activate script
deactivate script

@enduml 
