@startuml Freeze@Broker

participant "Host 🤗" as host

box Broker 🤵 domain #FFFFFA
    participant "Handler 📃" as broker
    'participant "Wallets 🪣" as wallets
    participant "Chats 🪣" as chats
end box

participant "Wallet 👱" as wallet


activate host
    host --> broker: Freeze 🐌
deactivate host

activate broker
    broker -> chats: READ 🧲
    broker -> chats: SAVE 💾
    broker --> wallet: SEND 📬 {Frozen@}
deactivate broker



@enduml 
