@startuml Handle

participant "User 🧑" as user
box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "CALL 🧮" as engine
    'participant "Inbox 📨" as inbox
end box
participant "Hosted 📦" as hosted


activate script
    script --> user: ⏪ PROMPT 🤔
    script -> engine: CALL 🧮 {function} 
deactivate script


activate engine
    engine --> hosted: Handle 🐌 {function, hook}
activate hosted
    engine -> engine: WAIT 🧘 {hook}
deactivate engine
    
    hosted --> engine: Handled 🐌 {hook, result}
deactivate hosted

activate engine
    engine -> script: RACE 🏁 {result}
deactivate engine

activate script
    script --> user: ⏪ PROMPT 🤔
deactivate script

@enduml