@startuml VERIFY Schema 🧩

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "GRAPH ⌘" as verify
end box
participant "Graph 🕸" as graph


activate script
    script -> verify: GRAPH 🕸 {subject, payload}

activate verify
    
    verify -> graph: 📬 SEND 🚀 <subject>@Graph {payload}
    activate graph
        graph -> verify: {response}
    deactivate graph

    verify -> script: RETURN {response}

deactivate verify

          
@enduml