@startuml OnChatterFinder

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "OnOpened 🔔" as script
    participant "Chatters 🪣" as table
    participant "OnFinder 🔔" as handler
end box

participant "Finder 🔎" as finder


chats --> script: OPENED 🔔

activate script
    script -> table: SAVE 💾 {FINDER}
deactivate script

activate table
    table --> handler: FINDER 🔔
deactivate table

activate handler
    handler --> finder: SEND 📬 {Present 🐌}
deactivate handler

activate finder
    finder --> chats : Presented 🐌 PRESENTED 
deactivate finder

@enduml