@startuml OnChatterFinder

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as table
    participant "OnFinder 🔔" as handler
end box
participant "Finder 🔎" as finder


wallet --> chats: Opened 🐌

activate chats
    chats --> table: SAVE 💾 {FINDER}
deactivate chats

activate table
    table --> handler: FINDER 🔔
deactivate table

activate handler
    handler --> finder: SEND 📬 {Present 🐌}
deactivate handler

activate finder
    finder --> chats : Presented 🐌 PRESENTED 
deactivate finder

@enduml