@startuml OnChatAltered

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Script 📃" as script
    participant "Chats 🪣" as chats
    participant "OnAltered 🔔" as handler
    participant "Wallets 🪣" as wallets
    participant "Frontend 🪣" as frontend
end box



activate script
    script -> chats: SAVE 💾, DELETE 🗑️
deactivate script

activate chats
    chats --> handler: ALTERED 🔔
deactivate chats

activate handler
    handler -> wallets: READ 🧲
    handler -> frontend: READ 🧲 {Wallet: $wallet.ID}
    handler -> frontend: SAVE 💾 {Chats: $wallet.Chats}
deactivate handler

@enduml 
