@startuml Hook

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "HOOK 🪝" as hook
    'participant "Imprints 🪣" as imprints
    participant "Hooks 🪣" as hooks
end box



activate script
    script -> hook: HOOK 🪝 {uuid}
deactivate script

activate hook
    'hook -> imprints: IMPRINT 🦶 {uuid}
    hook -> hooks: SAVE 💾 {uuid, script, line}

    alt in the present
        hook -> script: RETURN {empty}
        activate script

    else anytime later, in the future
        hook <-  : REEL 🎣 {uuid, output}
        'hook -> imprints: RECALL 🪶 {uuid}
        hook -> script : RETURN {output}
    end alt
    
deactivate hook


@enduml