@startuml 👉 Host NFC-QR check-in

' ------------

actor User as user  
participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph


activate broker

' Get the host's public name and icon
broker -> graph: 1) Identity 🚀
activate graph
  graph -> broker: {identity}
deactivate graph

' Get the host's public title
broker -> graph: 2) Translate 🚀
activate graph
  graph -> broker: {title}
deactivate graph

' Create a new session ID
broker -> broker: chat+

' Ask for a new chat to be opened
broker --> notifier: 3) Open  🐌
deactivate broker

activate notifier
  notifier --> wallet
deactivate notifier


activate wallet
  wallet -> wallet: new chat 💬
deactivate wallet

    
' ------------
@enduml