@startuml OnTokenDeclined

participant "Issuer 🎴" as issuer

box Broker 🤵 domain #FFFFFA
    participant "Offer@ 📃" as script
    participant "Tokens 🪣" as tokens
    participant "OnDeclined 🔔" as change
end box

participant "Wallet 👱" as wallet
'participant "Notifier 📣" as notifier

' The issuer offers a token to the broker
issuer --> script: Offer 🐌

activate script
    ' The Broker asks the wallet if it wants to save the token
    script --> wallet: CONFIRM 👍 {save?}   
deactivate script

activate wallet
    ' The wallet rejects the token
    wallet --> script: {no}
deactivate wallet

activate script
    script -> tokens: SAVE 💾 {REJECTED}
deactivate script

activate tokens
    tokens --> change: REJECTED 🔔
deactivate tokens

activate change
    change --> issuer: SEND 📬 {Declined 🐌}
deactivate change

@enduml 