@startuml OnTokenDeclined

participant "Issuer 🎴" as issuer
box Broker 🤵 domain #FFFFFA
    participant "Offer 🐌" as script
    participant "Tokens 🪣" as tokens
    participant "OnDeclined 🔔" as change
end box


issuer --> script: Offer 🐌

activate script
    script -> tokens: SAVE 💾 {OFFERED}
deactivate script

activate tokens
    tokens --> tokens: SAVE 💾 {DECLINED}
    tokens --> change: DECLINED 🔔
deactivate tokens

activate change
    change --> issuer: SEND 📬 {Declined 🐌}
deactivate change

@enduml 