@startuml Broker.Chats.Abandon 
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as script
    participant "Binds 🪣" as binds
end box
participant "Host 🤗" as host


wallet -> script: Pop 🐌 {CHAT}

activate script
    wallet -> script: {abandon}
    script -> binds: 💾 ABANDONED
deactivate script

activate binds
    binds -> host: Abandoned 🐌
deactivate binds


@enduml 
