@startuml Broker.Chats.Abandon 
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "PopChat 😃" as script
    participant "Chats 🪣" as binds
end box
participant "Host 🤗" as host


wallet -> script: PopChat 🔆 {chat}

activate script
    wallet -> script: "abandon"
    script -> binds: 💾 {ABANDONED}
deactivate script

activate binds
    binds -> host: Abandoned @ Host 🐌
deactivate binds


@enduml 
