@startuml OnChatInserted

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as table
    participant "OnInserted 🔔" as handler
end box



wallet --> table: Locate 🐌
activate table
    wallet --> table: Pop 🐌
    table --> handler: INSERTED 🔔
deactivate table

activate handler
    handler -> table: SAVE 💾 {RESOLVED}
deactivate handler

@enduml 
