@startuml OnChatInserted

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as table
    participant "OnInserted 🔔" as handler
end box

participant "Graph 🕸" as graph

wallet --> table: Locate 🐌
activate table
    wallet --> table: Pop 🐌
    table --> handler: INSERTED 🔔
deactivate table

activate handler
    handler -> graph: TRANSLATE 🈯
    handler -> table: SAVE 💾 {DETAILED}
deactivate handler

@enduml 
