@startuml OnChatInserted

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as table
    participant "OnInserted 🔔" as handler
    participant "Talker 😃" as talker
end box
participant "Printer 🖨️" as printer


wallet --> table: Locate 🐌
activate table
    wallet --> table: Pop 🐌
    table --> handler: INSERTED 🔔
deactivate table

activate handler
    group IF key.IsEmpty

        handler -> talker: PARSE 🔆 {locator}

        group WHILE locator.IsAlias 

            handler -> printer: SEND 🚀 Resolve 

            activate printer
                printer -> handler: {host locator}
            deactivate printer

            handler -> talker: PARSE 🔆 {locator}

        end group
    end group

    handler -> table: SAVE 💾 {RESOLVED}

deactivate handler

@enduml 
