@startuml OnWalletLanguage
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Language@ 📃" as handler
    participant "Wallets 🪣" as wallets
    participant "OnLanguage 🔔" as script
    participant "Binds 🪣" as binds
    participant "Tokens 🪣" as tokens
    participant "Chats 🪣" as chats
end box

'participant "Vault 🗄️" as vault
'participant "Graph 🕸" as graph

wallet --> handler: Language 🐌
activate handler
    handler -> wallets: SAVED 💾 {language}
deactivate

activate wallets
    wallets --> script: UPDATED 🔔
deactivate wallets

activate script
    script -> script: PARALLEL {wallet.*}
    activate script
        script -> binds: SAVE 💾 {language}
        script -> tokens: SAVE 💾 {language}
        script -> chats: SAVE 💾 {language}
    deactivate script
deactivate script



@enduml 
