@startuml OnChatterHost


box Broker 🤵 domain #FFFFFA
    participant "OnBroker 🔔" as broker
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as table
    participant "OnHost 🔔" as handler
end box
participant "Host 🤗" as host

activate broker
    broker -> chats: SAVE 💾 {ACTIVE}
deactivate broker


activate chats
    chats --> table: SAVE 💾 {HOST}
deactivate chats

activate table
    table --> handler: HOST 🔔
deactivate table

activate handler
    handler --> host: SEND 📬 {Hello@ 🐌}
deactivate handler

@enduml