@startuml OnBindBound
 
box Broker 🤵 domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnBound 🔔" as handler
end box
participant "Vault 🗄️" as vault


activate binds
    binds --> handler: BOUND 🔔
deactivate binds

activate handler
    handler --> vault: SEND 📬 {Bound@}
deactivate handler


@enduml 
