@startuml Wallet: Share()

participant "Wallet 👱" as user
participant "Broker 🤵" as broker
participant "Consumer 💼" as consumer
participant "Vault 🗄️" as vault
participant "Graph 🕸" as graph

' --------------------
' QUERY
' --------------------

activate consumer

group Request the data

    consumer --> broker: 1) Query  🐌
    deactivate consumer

    ' Broker 🤵
    activate broker 
    broker -> graph: 2) Queryable 🚀 {codes}
    broker -> graph: 3) Translate 🚀 {codes}

    alt Select if 2+ vaults
        broker --> user: 4 ⏪ Prompt 🤔
        deactivate broker

        activate user
            user --> broker: {selected}
        deactivate user

        activate broker
    end alt

    broker --> vault: 5) Disclose 🐌 {code}
    deactivate broker

    activate vault

end group

group Gather the data

    alt If requires context
        ' Get te context.
        vault -> consumer: 6) Queried 🚀 
        activate consumer
        consumer --> vault: {context}
        deactivate consumer
    end alt

    ' Ask user to confirm.
    vault --> user: 7 ⏪ Prompt 🤔 {confirm?}
end group

vault --> consumer: 8 ⏪ Consume 🧩
deactivate vault 



@enduml 