@startuml Goodbye
' ------------------

actor "User" as user
participant "Broker 🤵\nhost" as broker
participant "Review ⭐\nagent" as reviewer
participant "Host 🤗\ndomain" as host
participant "Graph 🕸\ndomain" as graph
participant "Finder 🔎\nsubscribers" as finder


activate broker


    host --> graph: {manifest}

    broker --> reviewer: 1) rate@
    deactivate broker

group Ask user feedback

    activate reviewer
        reviewer -> graph: 2) service@ 
        reviewer --> user: 3) ⏪ prompt
    deactivate reviewer

    ' Answer to reviewer.
    activate user
        user --> reviewer: {rate}
    deactivate user

    ' Confirm reviewed to broker.
    activate reviewer
        
        loop Follow-up questions
            reviewer --> user: ⏪ prompt {why?}
        end loop


end group

group Delayed fan out of anonymous feedback 

        reviewer --> host: 4) rated@

        reviewer --> finder: 5) ⏩ ingest {rated}
        reviewer --> finder: ⏩ ingest {rated}

    deactivate reviewer

end group






' ------------
@enduml 