@startuml PresentChat

box Broker 🤵 domain #FFFFFA
    participant "TALK ⌘" as cmd
    participant "Welcome 😃" as handler
    participant "Chatters 🪣" as chatters    
    participant "Chats 🪣" as chats
end box

participant "Wallet 👱" as wallet

cmd -> handler: 🏃 RUN 
activate handler
    handler -> chatters: READ 🧲 
    handler -> chats: 
    handler -> wallet: INFO ⓘ {reason}
    handler -> wallet: INFO ⓘ {shared binds}
    handler -> wallet: INFO ⓘ {shared tokens}
deactivate handler

@enduml