@startuml Vault.Discloses

participant "Broker 🤵" as broker

box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as table
    participant "Schemas 🪣" as schemas
    participant "Script 📃" as handler
end box
participant "Graph 🕸" as graph
participant "Consumer 💼" as consumer


broker --> table: 🐌 Disclose @ Vault 

activate table
    table -> graph: 🔔 ASKED: 🚀 Trusts @ Graph ❌ UNTRUSTED
    table -> consumer: 🔔 TRUSTED: 🚀 Queried @ Consumer 
    table -> schemas: 🔔 DETAILED: READ 🧲 
    
    activate table
        table -> handler: 🏃 RUN {script, context}
    deactivate table
    activate handler
        handler -> table: SAVE 💾 {data}
    deactivate handler

    table --> consumer: 🔔 READY: 🐌 Consume @ Consumer
deactivate table

activate consumer
    consumer -> table: 🚀 Collect @ Vault
deactivate consumer


@enduml 