@startuml ⚙️ Form

participant "Consumer 💼" as consumer
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user
participant "Vault 🗄️" as vault


' 🐌  🚀

'activate consumer
    consumer --> broker: 1) Query 🐌 
'deactivate consumer

activate broker
    broker --> user: 2) FAIL ❌ unannounced
deactivate broker

'activate consumer
    consumer --> broker: 3) Inform 🐌
'deactivate consumer

activate broker
    broker -> graph: 4) Form 🚀
    broker -> user: 5) CONFIRM 👍
    broker --> consumer: 6) Informed 🐌
deactivate broker

activate consumer
    consumer --> broker: 7) Query 🐌 ✅
deactivate consumer

activate broker
    broker --> vault: 8) Disclose 🐌
deactivate broker



@enduml 