@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Help 🐌" as handler
    participant "Helps 🪣" as table
    participant "Schemas 🪣" as schemas
    participant "Script 📃" as script
end box
participant "Graph 🕸" as graph
participant "Biller 🤝" as biller
participant "Consumer 💼 " as consumer



handler -> table: 💾 INVITED

group Validations

activate table
    table -> graph: 🔔 INVITED: TRUSTS 🫡 {consumer, schema} ❌ UNTRUSTED 
    table -> biller: 🔔 TRUSTED: 🚀 Authorize @ Biller {consumer, schema} ❌ BLOCKED
    table -> consumer: 🔔 VALID: 🚀 Invited @ Consumer {invite} ❌ BROKEN
    
end group 

    table -> schemas: 🔔 DETAILED: READ 🧲 
    activate table
        table -> script: RUN 🏃 {schema.script}
    deactivate table
    table -> consumer: 🔔 HELPED: 🐌 Helped @ Consumer {invite, help}
    table -> biller: 🔔 BILLABLE: 🐌 Bill @ Biller {authorization} 
    table -> table: 🔔 BILLED
deactivate table


@enduml 