@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Help 🐌" as handler
    participant "Helps 🪣" as table
end box
participant "Graph 🕸" as graph
participant "Biller 🤝" as biller
participant "Consumer 💼 " as consumer
participant "Wallet 🧑" as wallet
'participant "Broker 🤵" as broker


handler -> table: 💾 INVITED

activate table
    table -> graph: TRUSTS 🫡 {consumer, schema}
deactivate table

activate graph
    graph -> table: 💾 TRUSTED ✅ UNTRUSTED ❌
deactivate graph

activate table
    table -> biller: 🚀 Authorize @ Biller {consumer, schema}
deactivate table

activate biller
    biller -> table: 💾 VALID ✅ BLOCKED ❌
deactivate biller

activate table
    table -> consumer: 🚀 Invited @ Consumer {invite}
deactivate table

activate consumer
    consumer -> table: 💾 DETAILED ✅ BROKEN ❌
deactivate consumer

activate table
    table -> wallet: 🐌 Prompt @ Broker 
deactivate table

activate wallet
    wallet -> table: 💾 HELPED ✅
deactivate wallet

activate table
    table -> consumer: 🐌 Helped @ Consumer {invite, help}
deactivate table

activate consumer
    consumer -> table: 💾 BILLABLE ✅
deactivate consumer

activate table
    table -> biller: 🐌 Bill @ Biller {authorization}
deactivate table

activate biller
    biller -> table: 💾 BILLED ✅
deactivate biller

@enduml 