@startuml OnTokenSaved

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Saved@ 📃" as script
    participant "Tokens 🪣" as tokens
    participant "OnAccepted 🔔" as change
end box

'participant "Notifier 📣" as notifier
participant "Issuer 🎴" as issuer

wallet --> script: Saved 🐌

activate script
    script -> tokens: SAVE 💾 {ACCEPTED}
deactivate script

activate tokens
    tokens --> change: ACCEPTED 🔔
deactivate tokens

activate change
    change --> issuer: SEND 📬 {Accepted 🐌 true}
deactivate change

@enduml 