@startuml OnTokenAccepted

participant "Issuer 🎴" as issuer
box Broker 🤵 domain #FFFFFA
    participant "Offer 🐌" as script
    participant "Tokens 🪣" as tokens
    participant "OnAccepted 🔔" as change
end box
participant "Wallet 👱" as wallet


issuer --> script: Offer 🐌 {hook}

activate script
    script -> tokens: SAVE 💾 {OFFERED}
deactivate script

activate tokens
    tokens --> tokens: SAVE 💾 {ACCEPTED}
    tokens --> change: ACCEPTED 🔔
deactivate tokens

activate change
    change --> wallet: SEND 📬 {Save 🐌 hook, id}
deactivate change

@enduml 