@startuml Broker.Binds.Bind
 
participant "Vault 🗄️" as vault
box Broker 🤵 domain #FFFFFA
    participant "Bind 🐌" as script
    participant "Binds 🪣" as binds
end box
participant "Graph 🕸" as graph
participant "Wallet 👱" as wallet


activate vault
    vault -> script: Bind 🐌
deactivate vault

activate script
    script -> binds: 💾 OFFERED
deactivate script

activate binds
    
    binds -> graph: TRANSLATE 🈯 
    activate graph
        graph -> binds: 💾 DETAILED
    deactivate graph

    binds -> wallet: CONFIRM 👍 "accept?"
    activate wallet
        wallet -> binds: 💾 ACTIVE or REJECTED
    deactivate wallet

    binds -> vault: Bound 🐌 {answer}
deactivate binds


@enduml 
