@startuml OnWalletLocalized
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as handler
    participant "Wallets 🪣" as wallets
    participant "OnLocalized 🔔" as script
    participant "Binds 🪣" as binds
    participant "Tokens 🪣" as tokens
    participant "Chats 🪣" as chats
end box


wallet --> handler: Pop 🐌
activate handler
    wallet --> handler: {language}
    handler -> wallets: SAVED 💾 {language}
deactivate

activate wallets
    wallets --> script: UPDATED 🔔
deactivate wallets

activate script
    script -> binds: SAVE 💾 {language}
    script -> tokens: 
    script -> chats: 
deactivate script



@enduml 
