@startuml Host.Prompts.Prompt
 
box Host 🤗 domain #FFFFFD
    participant "PROMPT ⌘" as PROMPT
    participant "Prompts 🪣" as prompts
end box
participant "Graph 🕸" as graph
participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet


activate PROMPT
    PROMPT -> prompts: 💾 {INSERTED}
deactivate PROMPT

activate prompts
    prompts -> PROMPT: TRANSLATE 🈯
deactivate prompts

activate PROMPT
    PROMPT -> prompts: 💾 {TRANSLATED}
deactivate PROMPT

activate prompts
    prompts -> PROMPT: ASSERT 🚦
deactivate prompts

activate PROMPT
    PROMPT -> prompts: 💾 {ASSERTED}
deactivate PROMPT

activate prompts
    prompts -> broker: 🐌 Prompt @ Broker
deactivate prompts

activate broker
    broker -> wallet:
deactivate broker

activate wallet
    wallet -> prompts: 🚀 Prompted @ Host
    wallet -> prompts: 🐌 Reply @ Host 💾 {REPLIED}
deactivate wallet

activate prompts
    prompts -> PROMPT: REEL 🎣 or RACE 🏁
deactivate prompts


@enduml 
