@startuml Host.Prompts.Prompt
 
box Host 🤗 domain #FFFFFD
    participant "Talker 😃" as PROMPT
    participant "Prompts 🪣" as prompts
end box
participant "Graph 🕸" as graph
participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet


activate PROMPT
    PROMPT -> prompts: 💾 {INSERTED}
deactivate PROMPT

activate prompts
    prompts -> graph: TRANSLATE 🈯
    activate graph
        graph -> prompts: 💾 {TRANSLATED}
    deactivate graph
    prompts -> broker: 🐌 Prompt @ Broker
deactivate prompts

activate broker
    broker -> wallet:
deactivate broker

activate wallet
    wallet -> prompts: 🚀 Prompted @ Host
    wallet -> prompts: 🐌 Reply @ Host 💾 {REPLIED}
deactivate wallet

activate prompts
    prompts -> PROMPT: REEL 🎣 
deactivate prompts


@enduml 
