@startuml Chat

actor "User" as user
participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Filer 🗃️\nvault" as filer
participant "Broker 🤵\ndomain" as broker

'group Register

    user --> syncer: 1) chat {key}

    activate syncer
        syncer --> filer: 2) Chat 🐌
    deactivate syncer

    activate filer
        filer --> broker: 3) Engage ⏩
    deactivate filer

    activate broker
        broker --> filer:
    deactivate broker

    activate filer
        filer --> wallet: 4) ⏪ Prompt {what?} 
    deactivate filer

@enduml