@startuml OnSchemaLocalized
 

box Broker 🤵 domain #FFFFFA
    participant "Schemas 🪣" as schemas
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph


activate schemas
    schemas --> handler: UPDATED 🔔 {language}
deactivate schemas

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> schemas: SAVE 💾 {translation}
deactivate handler


@enduml 
