@startuml CHAT
' TODO

participant  "Broker 🤵" as broker
box Host 🤗 domain #FFFFFA
    participant "Script 📃" as script
    participant "CHAT 💬" as CHAT
    participant "$.Chat 🧠" as holder
    participant "Chats 🪣" as chats
end box


broker --> script: {chat}

activate script
    script -> CHAT: CHAT 💬 {chat, broker}
deactivate script

activate CHAT

    group Return if $.Chat.Exists
        CHAT -> holder: IF $.Chat.Exists 
        CHAT -> script: RETURN 
    end group

    group Return if Host.Chats exists
        CHAT -> chats: READ 🧲 {broker, chat}
        CHAT -> holder: SET $.Chat
        CHAT -> script: RETURN 
    end group

    CHAT -> chats: SAVE 💾 {chat, broker}
activate chats
    CHAT -> CHAT: WAIT 🧘 {chat.ID}
deactivate CHAT

    chats --> CHAT: RACE 🏁
deactivate chats

activate CHAT
    CHAT -> script: RETURN
deactivate CHAT

activate script
deactivate script

@enduml 
