@startuml Issuer.Tokens
 
box Issuer 🎴 domain #FFFFFA
    participant "Script" as script
    participant "Tokens 🪣" as tokens
end box
participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

script -> tokens: 💾 ISSUED

activate tokens
    tokens --> broker: Issue 🐌  
deactivate tokens

activate broker
    broker --> tokens: 🐌 💾 OFFERED, declined
    broker --> wallet: Save 🐌 
deactivate broker

activate wallet
    wallet -> tokens: Issued 🚀
    wallet --> broker: Saved 🐌
deactivate wallet

activate broker
    broker --> tokens: 🐌 💾 OFFERED, accepted
deactivate broker

@enduml 
