@startuml OnTokenDeclined

participant "Broker 🤵" as broker

box Issuer 🎴 domain #FFFFFA
    participant "Declined 🐌" as script
    participant "Tokens 🪣" as tokens
    participant "OnDeclined 🔔" as handler
    participant "Talker 😃" as talker
end box


broker --> script: Declined 🐌 {token}

activate script
    script -> tokens: SAVE 💾 {DECLINED}
deactivate script

activate tokens
    tokens --> handler: DECLINED 🔔
deactivate tokens

activate handler
    handler --> talker: REEL 🎣
deactivate handler

@enduml 
