@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Caller 📃" as script
    participant "WAIT 🧘" as wait
    'participant "Imprints 🪣" as imprints
    participant "Waits 🪣" as waits
end box
participant "Alarm ⏰" as alarm

activate script
    script -> wait: WAIT 🧘 {uuid} 
deactivate script

activate wait
    wait -> waits: 💾 {WAIT, uuid}
    activate waits
        waits -> alarm: 🐌 Trigger {uuid}
    deactivate waits
    activate alarm

    wait -> wait: HOOK 🪝 {uuid}
deactivate wait



    alarm -> waits: 🔔 Timeout 💾 {TIMEOUT}
deactivate alarm

activate waits
    waits <- : 🏁 RACE 💾 {RACE, result}
    'waits -> imprints: RECALL 🪶 {uuid}
    waits -> wait: REEL 🎣 {uuid, result} (or empty)
deactivate waits

activate wait
    wait -> script: RETURN {result}
deactivate wait


activate script    
    
@enduml