@startuml Wallet: Share Token


actor User as user
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(host)" as consumer
participant "Identity 🆔\n(vault)" as identity
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer
consumer --> user : 1) ⏪ Share Token 🎫



'group Request ID check

    consumer -> graph: 2) Trusts 🚀 {identity}
    consumer --> broker: 3) Verify 🐌
    deactivate consumer

    activate broker
        broker --> identity: 4) Verify 🐌 {ID locator}
    deactivate broker

    activate identity
        identity -> graph: 5) Trusts 🚀


'end group


identity --> user: 6 ⏪ Take Selfie 📸

group Confirm ID 

        identity --> consumer: 7) Verified 🐌
    deactivate identity

    ' CONSUMER
    activate consumer   
        consumer -> graph: 8) Trusts 🚀 {identity}

end group

    deactivate consumer

@enduml 