@startuml Wallet: Share Token


actor User as user
'participant "Wallet 👱\napp" as wallet
'participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\ndomain" as broker
participant "Issuer 🎴\ndomain" as issuer
participant "Consumer 💼\ndomain" as consumer
participant "Graph 🕸\ndomain" as graph


' --------------------
' QUERY
' --------------------

user <-- issuer: 1) ⏪ Save Token 

user --> consumer: 2)  Share Token ⏩


issuer --> broker: 3) Revise 🐌

'group Offline verification

    consumer -> broker: 4) Status 🚀

    activate broker
    activate consumer
        broker -> graph: 5) Trusts 🚀
        broker -> consumer: {status}
    deactivate broker

    deactivate consumer

'end group

@enduml 