@startuml Wallet: Share Token


actor User as user
'participant "Wallet 👱\napp" as wallet
'participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\ndomain" as broker
participant "Graph 🕸\ndomain" as graph
participant "Issuer 🎴\ndomain" as issuer
participant "Consumer 💼\ndomain" as consumer


' --------------------
' QUERY
' --------------------

issuer --> broker: 1) ⏪ Offer Token
activate broker
    broker --> user
deactivate broker

consumer --> broker: 2) ⏪ Share Token
activate broker
    broker --> user
deactivate broker


'group Update Token
    issuer --> broker: 3) Revise 🐌
    activate broker
        broker --> user
    deactivate broker
'end group

'group Offline verification

    consumer -> broker: 4) Status 🚀

    activate broker
    activate consumer
        broker -> graph: 5) Trusts 🚀
        broker -> consumer: {status}
    deactivate broker

    deactivate consumer

'end group

@enduml 