@startuml Wallet: Share Token


actor User as user
participant "Wallet 👱\n(app)" as wallet
participant "Notifier 📣\n(domain)" as notifier
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(host)" as consumer
participant "Identity 🆔\n(vault)" as identity
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer

group Share token

    consumer --> broker: 1) Query@
    deactivate consumer

    activate broker
        broker -> graph: 2) Queryable@ {codes}
        broker -> graph: 3) Translate@ {codes}
        broker --> notifier: 4) Query@
    deactivate broker

    activate notifier
        notifier --> wallet
    deactivate notifier

    activate wallet
        user --> wallet: 5) Share
        wallet --> consumer: 6. Verify@ {tokens}
    deactivate wallet

    activate consumer
    consumer -> graph: 7) Trusts@ {issuers}

end group


group Request ID check

    consumer -> graph: 8) Trusts@ {identity}
    consumer --> broker: 9) Query@ 
    deactivate consumer

    activate broker
        broker --> identity: Delegate@ {ID locator}
    deactivate broker

    activate identity
        identity -> graph: Trusts@ 


end group


identity --> wallet: 10 ⏪ Selfie

group Confirm ID 

        identity --> consumer: 11) Consume@ 
    deactivate identity

    ' CONSUMER
    activate consumer   
        consumer -> graph: 12) Trusts@ {identity}
        consumer -> identity: 13) Collect@
        activate identity
            identity -> consumer: {data}
        deactivate identity

end group

    deactivate consumer

@enduml 