@startuml Wallet: Share()


actor "User\nInterface" as user
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(domain)" as consumer
participant "Vault 🗄️\n(domain)" as vault
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer

group Request

    consumer --> broker: 1) Query  🐌
    deactivate consumer

    ' Broker 🤵
    activate broker 
    broker -> graph: 2) Queryable 🚀 {codes}
    broker -> graph: 3) Translate 🚀 {codes}

    alt Select if 2+ vaults
        broker --> user: 4 ⏪ prompt
        deactivate broker

        activate user
            user --> broker: {selected}
        deactivate user

        activate broker
    end alt

    broker --> vault: 5) Disclose 🐌 {code}
    deactivate broker

    activate vault
    vault -> graph: 6) Trusts 🚀

end group

'group User confirmation

    vault --> user: 7 ⏪ prompt (user confirmation)

'end group 


group Response

        vault --> consumer: 8) Consume 🐌
    deactivate vault

    activate consumer
        consumer -> graph: 9) Trusts 🚀 {vault}
        consumer -> vault: 10) Collect 🚀
        activate vault
            vault -> consumer: {data}
        deactivate vault

end group

    deactivate consumer

@enduml 