@startuml Invite

participant "Consumer 💼 " as host
box "Broker 🤵" #FFFFFA
    participant "Invites 🪣" as broker
    participant "Chatters 🪣" as chatters
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user
participant "Helper 🤲" as helper


activate host
    host --> broker: 🐌 Invite @ Broker
deactivate host

activate broker
    broker -> graph: 🔔 INVITED: 🫡 TRUSTS {consumer} ❌ UNTRUSTED
    broker -> graph: 🔔 TRUSTED: chatters: READ 🧲 

alt Only runs it not yet a chatter
    broker -> user: 🔔 VERIFIED: CONFIRM 🤔 "add helper to chat?" ❌ REJECTED
    activate broker
        broker -> chatters: 💾 HELPER
    deactivate broker
end alt 

    broker -> helper: 🔔 ADDED: 🐌 Help @ Helper
    broker -> broker: 🔔 DONE
deactivate helper


@enduml 