@startuml Invite

participant "Consumer 💼 " as host
box "Broker 🤵" #FFFFFA
    participant "Invites 🪣" as broker
    participant "Chatters 🪣" as chatters
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user
participant "Helper 🤲" as helper


activate host
    host --> broker: 🐌 Invite 💾 INVITED
deactivate host

activate broker
    broker -> graph: 🫡 TRUSTS
deactivate broker

activate graph
    graph -> broker: 💾 TRUSTED ✅ UNTRUSTED ❌
deactivate graph

activate broker
    broker -> chatters: READ 🧲 
deactivate broker

activate chatters
    chatters -> broker: 💾 CONFIRM ✅ HELP ✅
deactivate chatters

activate broker
    broker -> user: CONFIRM 🤔
deactivate broker

activate user
    user -> broker: 💾 HELP ✅ REJECTED ❌
deactivate user

activate broker
    broker -> chatters: 💾 HELPER
    broker -> helper: 🐌 Help @ Helper
deactivate broker

activate helper
    helper -> broker: 💾 DONE
deactivate helper


@enduml 