@startuml OnTokenIssued
 
participant "Issuer 🎴" as issuer
box Broker 🤵 domain #FFFFFA
    participant "Issue 🐌" as script
    participant "Tokens 🪣" as tokens
    participant "OnIssued 🔔" as handler
end box
participant "Graph 🕸" as graph


issuer --> script: Issue 🐌 {token}

activate script
    script -> tokens: SAVE 💾 {ISSUED}
deactivate script

activate tokens
    tokens --> handler: ISSUED 🔔
deactivate tokens

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> tokens: SAVE 💾 {DETAILED}
deactivate handler


@enduml 
