@startuml OnChatLeft
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop@ 📃" as script
    participant "Binds 🪣" as binds
    participant "OnRemoved 🔔" as handler
end box

participant "Host 🤗" as host

wallet --> script: Pop 🐌

activate script
    wallet --> script: leave
    script -> binds: SAVE 💾 {LEFT}
deactivate script

activate binds
    binds --> handler: LEFT 🔔
deactivate binds

activate handler
    handler --> host: SEND 📬 {Abandoned@}
deactivate handler


@enduml 
