@startuml OnPopPopped
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pops 🪣" as pops
    participant "OnWallet 🔔" as popped
end box

wallet --> pops: Pop 🐌 {WALLET}

activate pops
    pops --> popped: POPPED 🔔
deactivate pops

activate popped
    popped -> popped: CHAT 💬 
    popped -> wallet: ONE 🤔 {what?}
    popped -> pops: SAVE 💾 {...}
deactivate popped

@enduml 
