@startuml OnBindLocalized
 

box Broker 🤵 domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph



activate binds
    binds --> handler: UPDATED 🔔 {language}
deactivate binds

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> binds: SAVE 💾 {translation}
deactivate handler


@enduml 
