@startuml Pop@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop@ 📃" as pop
    participant "Wallets 🪣" as wallets
    participant "Locate@ 📃" as assess
    participant "Hello@ 📃" as introduced
    'participant "Wallets 🪣" as wallets
end box

box "Talker 😃" #FFFFFA
    participant "Engine ⚙️" as engine
    participant "Talkers 🪣" as talkers
'    participant "Pop {?} 📃" as popX
end box

'participant "Vault 🗄️" as vault

activate wallet 
    wallet --> pop: Pop 🐌 {context, key}
deactivate wallet

activate pop
    pop -> wallets: READ 🧲
    pop -> engine: LOCATE 🔆 {script}
deactivate pop

activate engine
    engine -> talkers: SAVE 💾
    engine -> pop: {locator}
deactivate engine

activate pop
    pop --> wallet: SEND 📬 Open 🐌 {locator}
deactivate pop

activate wallet
    wallet --> assess: Assess 🐌 {locator}
deactivate wallet

activate assess
    assess --> introduced:
deactivate assess

activate introduced
    'introduced -> engine: CHAT 💬
    introduced -> engine: TALK 😃
deactivate introduced

'activate popX
'deactivate popX

activate engine
    engine -> talkers: READ 🧲
    engine -> : RUN 🏃 {script} 
deactivate engine

@enduml 
