@startuml OnBindRejected
 
box Broker 🤵 domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnRejected 🔔" as handler
end box
participant "Vault 🗄️" as vault


activate binds
    binds --> handler: REJECTED 🔔
deactivate binds

activate handler
    handler --> vault: SEND 📬 {Bound@, declined}
deactivate handler


@enduml 
