@startuml OnChatterBroker


box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "OnPresented 🔔" as script
    participant "Chatters 🪣" as table
    participant "OnBroker 🔔" as handler
    participant "Talker 😃" as talker
end box

participant "Wallet 👱" as wallet

chats --> script: PRESENTED 🔔

activate script
    script -> table: SAVE 💾 {BROKER}
deactivate script

activate table
    table --> handler: BROKER 🔔
deactivate table

activate handler
    handler -> talker: CHAT 💬
    handler --> wallet: INFO ⓘ {reason}
    handler --> wallet: INFO ⓘ {shared binds}
    handler --> wallet: INFO ⓘ {shared tokens}
    handler -> chats: SAVE 💾 {ACTIVE}
deactivate handler

@enduml