@startuml OnChatterBroker

box Broker 🤵 domain #FFFFFA
    participant "Script 📃" as script
    participant "Chatters 🪣" as table
    participant "OnBroker 📃" as handler
end box

participant "Wallet 👱" as wallet

activate script
    script -> table: SAVE 💾 {BROKER}

activate table
    table --> handler: BROKER 🔔
deactivate table

activate handler
    handler --> wallet: INFO ⓘ {reason}
    handler --> wallet: INFO ⓘ {shared binds}
    handler --> wallet: INFO ⓘ {shared tokens}
deactivate handler

@enduml