@startuml OnQueryMatched

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnMatched 🔔" as handler
end box
participant "Graph 🕸" as graph

activate table
    table --> handler: MATCHED 🔔
deactivate table

activate handler
    
    handler -> handler: PARALLEL {matches}
    activate handler
        handler -> graph: TRUSTS 🫡 {CONSUMER}
        handler -> graph: TRUSTS 🫡 {VAULT}
    deactivate handler

    alt has trusts?
        handler -> table: SAVE 💾 {TRUSTED}
    else no trusted matches
        handler -> table: SAVE 💾 {UNTRUSTED}
    end alt

deactivate handler

@enduml