@startuml OnChatOpened

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Opened 🐌" as script
    participant "Chats 🪣" as chats
    participant "OnOpened 🔔" as handler
end box
participant "Finder 🔎" as finder
participant "Broker 🤵" as broker


wallet --> script: Opened 🐌

activate script
    script -> chats: SAVE 💾 {OPENED}
deactivate script

activate chats
    chats --> handler: OPENED 🔔
deactivate chats

alt IF Host is Broker

    activate handler
        handler -> chats: 💾 ACTIVE

end

    
        handler -> finder: 🤲 INVITE 
        handler -> broker: 🤲 INVITE 
        handler -> chats: 💾 PRESENTED
    deactivate handler


@enduml