@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "CALL 🧮" as talker
    participant "Holders 🪣" as holders
end box
participant "Hosted 📦" as hosted



activate script 
    script -> talker: CALL 🧮 {function, inputs} 
deactivate script

activate talker
    talker -> talker: uuid: {.UUID}
    talker -> holders: IMPRINT 🦶 {uuid}
    talker --> hosted: ASYNC 👷🏼 {uuid, function, inputs} 
activate hosted
    talker -> talker: WAIT 🧘 {uuid}
deactivate talker 
          
    hosted -> holders: Placed 🚀 READ 🧲 {uuid, holder}
    hosted -> holders: Place 🚀 SAVE 💾 {uuid, holder, value}
    hosted --> talker: Handled 🐌 RACE 🏁 {uuid, result}
deactivate hosted

activate talker
    talker -> holders: RECALL 🪶 {uuid}
    talker -> script: RETURN {result}
deactivate talker

activate script



@enduml