@startuml Wallet: Share()

actor User as user  
participant "Wallet 👱\napp" as wallet
participant "Broker 🤵\nhost" as broker
participant "Finder 🔎\nvault" as finder
participant "Vault 🗄️\n(domain)" as vault

vault --> broker: 1) Engage 🐌 {locator}

activate broker

broker --> wallet: 2) ⏪ Assessed        
activate wallet
    wallet --> wallet: new Chat 💬
deactivate wallet

broker --> finder: 3) Introduce ⏩
deactivate broker
    activate finder
        finder --> broker
    deactivate finder
activate broker
        
broker --> wallet: 4) ⏪ Prompt 🤔 {binds}
broker --> vault: 5) Hello 🐌 {locator}
deactivate broker

activate vault
    vault --> wallet: 6) ⏪ Prompt {what?} 
deactivate vault

activate wallet
    user --> wallet: reply
deactivate wallet

@enduml 