@startuml Wallet: Share()

actor User as user  
participant "Wallet 👱\napp" as wallet
participant "Broker 🤵\nhost" as broker
participant "Finder 🔎\nvault" as finder
participant "Vault 🗄️\n(domain)" as vault

vault --> broker: 1) Engage 🐌 {locator}

activate broker

broker --> wallet: 2) ⏪ Open {locator}
broker --> vault: 3) Hello 🐌 {locator}
deactivate broker

activate vault
    vault --> wallet: 4) ⏪ Prompt {what?} 
deactivate vault

activate wallet
    user --> wallet: reply
deactivate wallet

@enduml 