@startuml Identify

box Identity 🆔 domain #FFFFFA
    participant "Caller 📃" as caller
    participant "Identity 📃" as script
    participant "Liveness 📸" as liveness
end box
participant "Wallet 👱" as wallet


caller -> script: RUN {citizen}

activate script
    script -> liveness: RUN {Liveness, citizen}
deactivate script   

activate liveness
    liveness -> wallet: 📸 smile
    liveness -> script
deactivate liveness

activate script
    script -> caller: RETURN
deactivate script
    
@enduml