@startuml Bind Biller

participant "Editor 🧑‍💻\nvault" as folder
participant "Collector 🏦\nvault" as collector
actor "User\nin chat" as user
participant "Biller 🤝\ndomain" as biller


activate biller
    biller --> user: 1) ⏪ Prompt 🤔 {what? ➜ bind}
    biller --> user: 2) ⏪ Bind 🔗 {host profile}
    biller --> collector: 3) ⏪ ShareBind 🔗 {collector}
    biller --> folder: 4) ⏪ ShareBind 🔗 {folder}
    biller --> user: 5) ⏪ ShareToken 🎫 {host admin}
deactivate biller
    
' ------------
@enduml