@startuml OnChatAbandoned
 
box Broker 🤵 domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnAbandoned 🔔" as handler
end box
participant "Host 🤗" as host


activate binds
    binds --> handler: ABANDONED 🔔
deactivate binds

activate handler
    handler --> host: SEND 📬 {Abandoned@}
deactivate handler


@enduml 
