@startuml 👉 Printer NFC-QR check-in


box "Broker 🤵" #FFFFFA
    participant "Locate@ 📃" as assess
    participant "Save-Chat 📃" as script
    participant "Chats 🪣" as chats
end box

'participant "Graph 🕸" as graph

activate assess
    assess -> script: 
deactivate assess

activate script
    script -> chats: SAVE {chat}
    script -> assess: RETURN {chat}
deactivate script

activate assess
deactivate assess


@enduml