@startuml PopChat
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chat 🔆" as popped
    participant "Chats 🪣" as chats
end box

wallet -> popped: Pop 🎈 {Chat}


activate popped
    popped -> chats: SELECT 🧲 
    popped -> wallet: INFO ⓘ {chat}
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {selection, chat}
deactivate popped

@enduml 
