@startuml OnChatLocalized
 

box Broker 🤵 domain #FFFFFA
    participant "Wallets 🪣" as wallets
    participant "OnLocalized 🔔" as script
    participant "Chats 🪣" as chats
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph


wallets --> script: UPDATED 🔔
activate script
    script -> chats: SAVE 💾 {language}
deactivate script

activate chats
    chats --> handler: UPDATED 🔔
deactivate chats

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> chats: SAVE 💾 {translation}
deactivate handler


@enduml 
