@startuml Vault.Shares

participant "Broker 🤵" as broker

box Vault 🗄️ domain #FFFFFA
    participant "Shares 🪣" as table
    participant "Graph 🕸" as graph
    participant "Script 📃" as handler
    participant "Hosted 📦" as hosted
end box
participant "Consumer 💼" as consumer


broker -> table: 🐌 Disclose @ Vault 💾 ASKED

activate table
    table -> graph: 🚀 Trusts @ Graph 
deactivate table

activate graph
    graph -> table: 💾 TRUSTED ✅ UNTRUSTED ❌
deactivate graph

activate table
    'table -> hosted: 🐌 Handle @ Hosted  
    table -> handler: RUN 📃 
deactivate table

activate handler
    handler -> hosted: 🐌 Handle 
    handler -> table: RETURN
deactivate handler

'activate hosted
'    hosted -> table: 🐌 Handled @ Talker 💾 READY
'deactivate hosted

activate table
    table -> consumer: 🐌 Consume @ Consumer
deactivate table

activate consumer
    consumer -> table: 🚀 Collect @ Vault
deactivate consumer


@enduml 