@startuml Vault.Shares

participant "Broker 🤵" as broker

box Vault 🗄️ domain #FFFFFA
    participant "Shares 🪣" as table
end box
participant "Graph 🕸" as graph
participant "Hosted 📦" as hosted
participant "Consumer 💼" as consumer


broker -> table: 🐌 Disclose @ Vault 💾 ASKED

activate table
    table -> graph: 🚀 Trusts @ Graph 
deactivate table

activate graph
    graph -> table: 💾 TRUSTED, UNTRUSTED
deactivate graph

activate table
    table -> hosted: IF trusted: 🐌 Handle @ Hosted  
deactivate table

activate hosted
    hosted -> table: 🐌 Handled @ Talker 💾 READY
deactivate hosted

activate table
    table -> consumer: 🐌 Consume @ Consumer
deactivate table

activate consumer
    consumer -> table: 🚀 Collect @ Vault
deactivate consumer


@enduml 