@startuml OnCollectsReady

box Vault 🗄️ domain #FFFFFA
    participant "Collects 🪣" as collects
    participant "OnReady 🔔" as ready
end box
participant "Consumer 💼" as consumer


activate collects
    collects --> ready: READY 🔔 
deactivate collects

activate ready
    ready --> consumer: SEND 📬 {Consume 🐌}
deactivate ready

activate consumer
    consumer -> collects: Collect 🚀
deactivate consumer

@enduml 