@startuml SHARE
 
box Host 🤗 domain #FFFFFD
    participant "Command ⌘" as script
    participant "Talker 😃" as talker
    participant "Prompts 🪣" as table
end box
participant "Wallet 👱" as wallet


activate script
    script -> talker: .PROMPT 🤔 
deactivate script

activate talker
    talker -> table: SAVE 💾 

    activate table
        table -> talker: {prompt}
        table --> wallet: Prompt @ Broker 🐌 {prompt}
    deactivate table
    activate wallet

    
    alt Non-blocking 
        alt With Options
            talker -> talker: HOOK 🪝 {prompt}
        end alt
        talker -> script: RETURN { }
    else Blocking
        talker -> talker: WAIT 🧘 {prompt}
    end alt

deactivate talker


activate wallet
    
    wallet -> table: Prompted @ Host 🚀 {prompt}
    activate table
        table -> wallet: {details}
    deactivate table

    wallet --> table: Reply @ Host 🐌 {prompt, reply}

deactivate wallet

activate table
    table -> talker: REEL 🎣 {prompt, reply}
deactivate table

activate talker
    talker -> script: RETURN {reply}
deactivate talker

activate script
deactivate script

@enduml 
