@startuml Wallet: Share Token


actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\ndomain" as notifier
participant "Broker 🤵\ndomain" as broker

participant "Consumer 💼\ndomain" as consumer
participant "Issuer 🎴\ndomain" as issuer
participant "Graph 🕸\ndomain" as graph

' --------------------
' QUERY
' --------------------


    'activate consumer
    consumer --> broker: 1) Query 🐌
    'deactivate consumer

    activate broker
        broker -> graph: 2) Queryable 🚀 {codes}
        broker -> graph: 3) Translate 🚀 {codes}
        broker --> wallet: 4) ⏪ Prompt 🤔 {tokens}
    deactivate broker


    
    activate wallet
        user --> wallet: share
        wallet --> broker: {tokens}
    deactivate wallet

    activate broker
        broker --> notifier: 5) Share 🐌
    deactivate broker

    activate notifier
        notifier --> wallet
    deactivate notifier

    activate wallet
        wallet --> consumer: 6) Receive 🐌 {tokens}
    deactivate wallet


    activate consumer
        
            consumer -> graph: 7) Trusts 🚀 {issuers}
            consumer -> graph: 8) PublicKey 🚀 {dkim}
            consumer -> broker: 9) ⏪ Token status
        
        consumer --> consumer: process
    deactivate consumer

'end group 


@enduml 