@startuml Tokens

title
    👱 Wallet: List Tokens
end title


' ----------------------
actor User as user
participant "Wallet 👱\napp" as wallet
participant "Broker 🤵\nhost" as broker
' ----------------------
' LIST
' ----------------------

user --> wallet: tokens

alt if not cached

    activate wallet
        wallet -> broker: Tokens 🚀

        activate broker
            broker -> wallet: {tokens}
        deactivate broker

    deactivate wallet
end

@enduml