@startuml ⚙️ OnChatsInformed

box Broker 🤵 #FFFFFA
    participant "Chats 🪣" as table
    participant "OnInformed 🔔" as event
end box
participant "Consumer 💼" as consumer

table -> event: INFORMED 🔔

activate event
    event --> consumer: SEND 📬 {Informed 🐌}
deactivate event


@enduml 