@startuml Broker.Tokens.Updates
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Wallets 🪣" as wallets
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
    

wallet -> wallets: 🐌 Pop 💾 {language: X}

activate wallets
    wallets -> tokens: 💾 {language}
deactivate wallets

activate tokens
    tokens -> frontend: 💾 {localized tokens}
deactivate tokens

activate frontend
    frontend -> wallet: IF changed: 🐌 Updated 
deactivate frontend

@enduml 
