@startuml Bind()

 
participant "Vault 🗄️" as vault

box Broker 🤵 domain  #FFFFFA
    participant "Bindable@ 📃" as broker
    'participant "Talker 😃" as talker
    'participant "Script 📃" as script
    participant "Chats 🪣" as chats
    participant "Binds 🪣" as binds
end box

'participant "Graph 🕸" as graph
'participant "Wallet 👱" as wallet


vault --> broker: Bindable 🐌 
deactivate vault    

activate broker
    'Read the chats
    broker -> chats: READ 🧲 
    'broker -> binds: 
    broker -> binds: SAVE 💾 {OFFERED}
deactivate broker


@enduml 
