@startuml Bind()

 
participant "Vault 🗄️" as vault

box Hosted 📦 domain  #FFFFFA
    participant "Broker 🤵" as broker
    'participant "Talker 😃" as talker
    'participant "Script 📃" as script
    participant "Binds 🪣" as itemizer
end box

participant "Graph 🕸" as graph
participant "Wallet 👱" as wallet


    vault --> broker: Bindable 🐌 {codes}
    deactivate vault    

    activate broker
 
        ' Translate.
        broker -> graph: SEND: Translate 🚀
        activate graph
            graph -> broker: {translations}
        deactivate
        
        ' RAISE BINDABLE!
        broker --> wallet: MANY {which ones?}
        broker --> itemizer: SAVE 💾 {binds}

        broker --> vault: SEND: Bound 🐌 {codes} 
    deactivate broker

@enduml 
