@startuml Place@Talker

participant "Hosted 📦" as hosted

box Talker 😃 domain #FFFFFA
    participant "Inbox 📨" as inbox
    participant "Hooks 🪣" as hooks
    participant "Holders 🪣" as holders
end box


activate hosted
    hosted -> inbox: Place 🚀 {A into $p}

    activate inbox
        inbox -> hooks: READ {hook}
        inbox -> holders: SAVE 💾 {hook, A into $p}
        inbox -> hosted: 
    deactivate inbox

deactivate hosted

@enduml