@startuml Callback

participant "Vault\nDomain" as vault
participant "Vault\nTalker 😃" as talker
participant "Hooks\nTable 🪣" as hooks
participant "Message\nHandler 📨" as handler
actor "User" as user

activate vault
    vault --> talker: BIND 🔗
deactivate vault
group .BIND
activate talker
    talker -> hooks: SAVE 💾 {$.cursor}    
    talker --> user: Bindable 🐌 {hook}
deactivate talker
activate user
end group

group Bound@Vault
    user --> handler: Bound 🐌 {hook}
deactivate user
activate handler

    handler -> hooks: GET {hook}
    activate hooks
        hooks -> handler: {cursor}
    deactivate hooks
    handler --> talker: REEL 🎣 {cursor,result}
deactivate handler

activate talker
end group
    talker -> talker: IF {result}: \n - SUCCESS ✅
deactivate talker

@enduml