@startuml Hook

participant "Domain 👥" as domain

box Talker 😃 domain #FFFFFA
    participant "Inbox 📨" as inbox
    participant ".REEL 📃" as reel
    participant "Hooks 🪣" as hooks
    participant "Holders 🪣" as holders
    participant "Caller 📃" as caller
end box


domain --> inbox: 🐌 {hook, out}

activate inbox
    inbox -> reel:  REEL 🎣 {hook, out}
deactivate inbox

activate reel
    reel -> hooks: GET {hook}
    
    activate hooks
        hooks -> reel: {caller, script, holders}
    deactivate hooks

    group Load holders into memory

        reel -> reel: PARALLEL {holders}
        activate reel
            reel -> holders: GET {holder}
            
            activate holders
                holders -> reel: {value}
            deactivate holders

            reel -> reel: EVAL holder: value
        deactivate reel

    end group

    reel -> caller: exit {script}  with {out}

deactivate reel

@enduml