@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant ".WAIT 📃" as wait
    participant "Holders 🪣" as holders
    participant "Hooks 🪣" as hooks
    participant "Engine ⚙️" as engine
end box


activate script
    script -> wait: WAIT 🧘 {hook} 
deactivate script

activate wait

    wait -> hooks: SAVE 💾 {hook, $.Script, $.Holders.Holder}

    wait -> wait: PARALLEL {$.Holders}
    activate wait
        wait -> holders: SAVE 💾 {hook, holder, value}
        wait -> engine: EXIT
    deactivate wait

deactivate wait

engine <- : REEL 🎣 {hook, return}
activate engine
    engine -> script: RETURN {return}
deactivate engine

activate script    
    
@enduml