@startuml Subscribe

participant "Streamer 🌬️\ndomain" as streamer

box Subscriber #FFFFFF
    participant "Buffer ⏳\nhelper" as buffer
    participant "Consumer 💼\ndomain" as domain
end box


activate streamer
    streamer --> buffer: 1) updated@
deactivate streamer

activate buffer
    buffer --> domain: 2) wake-up@
deactivate buffer

activate domain

    loop more?
        domain --> buffer: 3) consume@ 
    end loop

deactivate domain

@enduml