@startuml Wallet: Share()


actor "User\nInterface" as user
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(domain)" as consumer
participant "Vault 🗄️\n(domain)" as vault
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer

group Request

    consumer --> broker: query@
    deactivate consumer

    ' Broker 🤵
    activate broker 
    broker -> graph: queryable@ {codes}
    broker -> graph: translate@ {codes}

    alt Select if 2+ vaults
        broker --> user: ⏪ prompt
        deactivate broker

        activate user
            user --> broker: {selected}
        deactivate user

        activate broker
    end alt

    broker --> vault: disclose@ {code}
    deactivate broker

    activate vault
    vault -> graph: trusts@

end group

group User confirmation

    vault --> user: ⏪ prompt
    deactivate vault

    activate user
        user --> vault: { confirmation }
    deactivate user

    activate vault

end group 


group Response

        vault --> consumer: consume@
    deactivate vault

    activate consumer
        consumer -> graph: trusts@ {vault}
        consumer -> vault: collect@
        activate vault
            vault -> consumer: {data}
        deactivate vault

end group

    deactivate consumer

@enduml 