@startuml Status@Broker


participant "Consumer 💼" as consumer

box Talker 😃 domain #FFFFFA
    participant "Broker 🤵" as broker
    participant "Tokens 🪣" as tokens
    participant "Queries 🪣" as queries
end box
participant "Graph 🕸" as graph


consumer -> broker: Status 🚀

activate consumer
    
    activate broker
        broker -> tokens: READ 🧲 {token}
        broker -> queries: Consumed in the past?
        broker -> graph: TRUSTS 🫡 Trusts @ Graph 🚀    
        broker -> consumer: {status}
    deactivate broker

deactivate consumer

@enduml 