@startuml OnInviteValid

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnVerified 🔔" as handler
end box
participant "INVITE ⌘" as cmd

table --> handler: VERIFIED 🔔 

activate handler
    handler -> cmd: RACE 🏁 {help}
deactivate handler

@enduml 