@startuml VERIFY Domain Message 📨

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "VERIFY ⌘ Message 📨" as verify
end box
participant "Graph 🕸" as graph


activate script
    script -> verify: VERIFY 🔐 {message [,key]}

activate verify
    
    verify -x script: invalid hash 💥

    alt IF key is not empty
        verify -x script: VERIFY 🔐 Signature ᝰ🖊
    else IF key is empty
        verify -> graph: VERIFY 🔐 Domain 👥
        verify -x script: invalid signature 💥
    end alt

    verify -> script: RETURN ✅ 

deactivate verify

          
@enduml