@startuml OnFrontendAltered


box Broker 🤵 domain #FFFFFA
    participant "Frontend 🪣" as frontend
    participant "OnAltered 🔔" as handler
end box
participant "Notifier 📣" as notifier


    frontend --> handler: ALTERED 🔔
deactivate frontend

activate handler
    handler --> notifier: SEND 📬 {Updated@ 🐌}
deactivate handler

@enduml 
