@startuml Wallet: Share Token


actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Consumer 💼\ndomain" as consumer
participant "Issuer 🎴\ndomain" as issuer
participant "Graph 🕸\ndomain" as graph

' --------------------
' QUERY
' --------------------

group Offer Token
    issuer --> broker: 0. ⏪ Offer
    activate broker
    activate issuer
    deactivate broker
    deactivate issuer
end group


group Share token

    'activate consumer
    consumer --> broker: 1. Query@
    'deactivate consumer

    activate broker
        broker -> graph: 2. Queryable@ {codes}
        broker -> graph: 3. Translate@ {codes}
        broker --> notifier: 4. Share@
    deactivate broker

    activate notifier
        notifier --> wallet
    deactivate notifier

    activate wallet
        user --> wallet: share
        wallet --> consumer: 5. Shared@ {tokens}
    deactivate wallet

    activate consumer
        consumer -> graph: 6. Trusts@ {issuers}
    deactivate consumer

end group 

group Update Token
    issuer --> broker: 7. Revise@
    activate broker
    deactivate broker
end group

group Offline verification

    consumer -> broker: 8. Status@

    activate broker
    activate consumer
        broker -> graph: 9. Trusts@ 
        broker -> consumer: {status}
    deactivate broker

    deactivate consumer

end group

@enduml 