@startuml Wallet: Share Token


actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Consumer 💼\ndomain" as consumer
participant "Issuer 🎴\ndomain" as issuer
participant "Graph 🕸\ndomain" as graph

' --------------------
' QUERY
' --------------------

group Update Token
    issuer --> broker: Revise@
    activate broker
    deactivate broker
end group


group Share token

    'activate consumer
    consumer --> broker: 1. Query@
    'deactivate consumer

    activate broker
        broker -> graph: 2. Queryable@ {codes}
        broker -> graph: 3. Translate@ {codes}
        broker --> notifier: 4. Share@
    deactivate broker

    activate notifier
        notifier --> wallet
    deactivate notifier

    activate wallet
        user --> wallet: share
        wallet --> consumer: 5. Verify@ {tokens}
    deactivate wallet

    activate consumer
        consumer -> graph: 6. Trusts@ {issuers}

end group 


group Async verification

    consumer --> issuer: 7. Verify@ 
    deactivate consumer

    activate issuer
        issuer -> graph: Trusts@ 
        issuer --> consumer: 8. Verified@ 
    deactivate issuer

    activate consumer   
    deactivate consumer

end group

@enduml 