@startuml

actor "User" as user

'box "User Interface (UI)"  #FFFFFF
  participant "Wallet 👱" as wallet
  'participant "Notifier 📣\n(domain)" as notifier  
  participant "Broker 🤵" as broker
'end box

participant "Host 🤗" as host

' The host is prompting the user
'host --> wallet: ⏪ prompt 

' The user invokes the broker's talker
user --> wallet: broker 🤵
activate wallet
    wallet --> broker: 1) Join 🐌
deactivate wallet

' The broker shows the chat options
activate broker
    broker --> wallet: 2) ⏪ Prompt 🤔
deactivate broker

' The user asks to abandon the chat.
activate wallet
    user --> wallet: abandon
    wallet --> broker:
deactivate wallet

' The broker notifies the host and the notifier about the abandoned chat.
activate broker
    broker --> host: 3) Abandoned 🐌
deactivate broker

' ----------------------
@enduml 