@startuml OnBindRejected

participant "Broker 🤵" as broker

box Vault 🗄️ domain #FFFFFA
    participant "Rejected 🐌" as script
    participant "Binds 🪣" as binds
    participant "OnRejected 🔔" as trigger
    'participant "Talker 😃" as talker
    participant "BIND ⌘" as bind
end box


broker --> script: Rejected 🐌

activate script
    script -> binds: SAVE 💾 {REJECTED}
deactivate script

activate binds
    binds --> trigger: REJECTED 🔔
deactivate binds

activate trigger
    trigger --> bind: REEL 🎣 {id}
deactivate trigger


@enduml 