@startuml OnTokenLocalized
 
box Broker 🤵 domain #FFFFFA
    participant "Wallets 🪣" as wallets
    participant "OnLocalized 🔔" as script
    participant "Tokens 🪣" as tokens
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph


wallets --> script: UPDATED 🔔
activate script
    script -> tokens: SAVE 💾 {language}
deactivate script

activate tokens
    tokens --> handler: UPDATED 🔔
deactivate tokens

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> tokens: SAVE 💾 {translation}
deactivate handler


@enduml 
