@startuml ⚙️ Broker.Chats.Inform ⏩ flow

participant "Consumer 💼" as consumer

box Broker 🤵 #FFFFFA
    participant "Inform 🐌" as broker
    participant "Chats 🪣" as table
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user


consumer -> broker: Inform 🐌

activate broker
    broker -> table:  💾 {INFORM}
deactivate broker

activate table
    table -> graph: Form @ Graph 🚀
    table -> user: CONFIRM 👍
deactivate table

activate user
    user -> table:  💾 {INFORMED}
deactivate user

activate table
    table -> consumer: Informed 🐌
deactivate table


@enduml 