@startuml Goodbye
' ------------------

participant "Host 🤗" as host

box Broker 🤵 domain #FFFFFA
    participant "Goodbye@ 📃" as broker
    'participant "Wallets 🪣" as wallets
    participant "Chats 🪣" as chats
end box


activate host
    host --> broker: Goodbye 🐌
deactivate host

activate broker    
    broker -> chats: READ 🧲
    broker -> chats: SAVE 💾 {CLOSED}
deactivate broker


' ------------
@enduml 