@startuml Goodbye
' ------------------

participant "Host 🤗" as host

box Broker 🤵 domain #FFFFFA
    participant "Goodbye@ 📃" as broker
    'participant "Wallets 🪣" as wallets
    participant "Chats 🪣" as chats
end box

participant "Reviewer ⭐" as reviewer
participant "Advertizer 👀" as ads


activate host
    host --> broker: Goodbye 🐌
deactivate host

activate broker    
    
deactivate broker


' ------------
@enduml 