@startuml 🤲 OnHelperTrusted

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnTrusted 🔔" as event
end box
participant "Biller 🤝" as biller


table --> event: TRUSTED 🔔
activate event
    event -> biller: SEND 📬 {Authorize @ Biller 🚀}

    alt IF Result is not AUTHORIZED
        event -x table: BLOCKED ❌
    else
        event -> table: SAVE 💾 {bill}
        event -> table: AUTHORIZED ✅    
    end alt
    
deactivate event

@enduml 