@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnInvited 🔔" as event
    'participant "Help 🐌" as handler
    'participant "Schemas 🪣" as schemas
    'participant "Script 📃" as script
end box
'participant "Biller 🤝" as biller
participant "Consumer 💼 " as consumer
participant "Graph 🕸" as graph

table --> event: INVITED 🔔
activate event
    event -> consumer: SEND 📬 {Invited @ Consumer 🚀}
    event -> graph: VERIFY 🔐 {context, schema}
    alt if not valid
        event -x table: BROKEN ❌
    else if valid
        event -> table: SAVE 💾 {context}
        event -> table: VALID ✅ 
    end alt
deactivate event

@enduml 