@startuml 🤲 OnHelperAuthorized

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnAuthorized 🔔" as event
end box
participant "Consumer 💼 " as consumer
participant "Graph 🕸" as graph


table --> event: AUTHORIZED 🔔
activate event
    event -> consumer: SEND 📬 {Invited @ Consumer 🚀}
    event -> graph: VERIFY 🔐 {context, schema}
    alt if not valid
        event -x table: BROKEN ❌
    else if valid
        event -> table: SAVE 💾 {context}
        event -> table: VALID ✅ 
    end alt
deactivate event

@enduml 