@startuml Prompt
' ------------------

'actor "User" as user
participant "Host 🤗" as host
box "User Interface (UI)"  #FFFFFF
    participant "Broker 🤵" as broker
    participant "Notifier 📣" as notifier
    participant "Wallet 👱" as wallet
end box 
 

activate host

group Host Prompt 

    host --> broker: 1) Prompt 🐌 
    deactivate host

    ' Broker
    activate broker
        broker --> notifier: 2) Prompt 🐌
    deactivate broker

    ' Notifier
    activate notifier
        notifier --> wallet
    deactivate notifier

    ' Wallet
    activate wallet

        ' Get Prompt
        wallet -> host: 3) Prompted @ Host 🚀 >> {details}
        wallet -> host:  4) Download @ Host 🚀 >> {file}

end group


group User Response

    'user --> wallet: reply

    'wallet -> wallet: sign(msg)
    wallet --> host: 5) Reply 🐌 {signed content}
    deactivate wallet

    activate host

        'alt is vault?
        '    host -> host: validate(sign)
        'end alt

end group

deactivate host

' ------------
@enduml 
