@startuml ISSUE


box Issuer 🎴️ domain #FFFFFA
    participant "Script 📃" as script
    participant "ISSUE ⌘" as talker
    participant "Tokens 🪣" as hooks
end box

participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: ISSUE 🎫
deactivate script

activate talker
    talker -> hooks: SAVE 💾 
activate hooks
    hooks --> talker: {token}
    talker -> talker: WAIT 🧘 {token.ID}
deactivate talker

    hooks --> broker: SEND 📬 {Offer@ 🐌}
deactivate hooks

activate broker
    broker --> wallet: Save 🐌
deactivate broker

activate wallet
    wallet -> hooks: Issued 🚀 READ 🧲 
    wallet --> broker: Saved 🐌
deactivate wallet

activate broker
    broker --> hooks: 🐌 Offered 💾 OFFERED
deactivate broker

activate hooks
    hooks -> talker: RACE 🏁 
deactivate hooks

activate talker
    talker -> script: RETURN 
deactivate talker

activate script
deactivate script

@enduml 
