@startuml OnInformInform
 
box Broker 🤵 domain #FFFFFA
    participant "Forms 🪣" as table
    participant "OnInform 🔔" as handler
    participant "Chats 🪣" as chats
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user


activate table
    table --> handler: INFORM 🔔
deactivate table

activate handler
    handler -> graph: GRAPH 🕸 Form 
    handler -> handler: CHAT 💬

    alt IF only 1 step is needed
        handler -> user: INFO ⓘ
    else if only 1 step is needed
        handler -> user: CONFIRM 👍 
    end
    
    handler -> chats:  💾 {form}
    handler -> table:  💾 INFORMED
deactivate handler


@enduml 
