@startuml Bind Biller

participant "Biller 🤝" as biller
participant "Wallet 👱" as user
participant "Collector 🏦" as collector
participant "Editor 💻" as folder


activate biller
    biller --> user: 1) ONE 🤔 {what? ➜ bind}
    biller --> user: 2) BIND 🔗 {host profile}
    biller --> collector: 3) SHARE 🔗 {collector}
    biller --> folder: 4) SHARE 🔗 {folder}
    biller --> user: 5) SHARE 🎫 {host admin}
deactivate biller
    
' ------------
@enduml