@startuml Revoke


' ----------------------

actor User as user
participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Issuer 🎴" as issuer

issuer --> broker: 1) Revise 🐌
activate broker
    broker --> wallet: 2) ⏪ Prompt 🤔 {revoked}     
deactivate broker

' ----------------------
@enduml