@startuml Broker.Tokens.Updates
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as pop
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
participant "Issuer 🎴" as issuer
participant "Notifier 📣" as notifier

wallet -> pop: Pop 🐌 {TOKEN}

activate pop
    wallet -> pop: {remove}
    pop -> tokens: 💾 {REMOVED}
deactivate pop    


activate tokens
    tokens -> issuer: 🐌 Removed @ Issuer
    tokens -> notifier: 🐌 Remove @ Notifier
    tokens -> frontend: 💾 {tokens}
deactivate tokens

activate frontend
    frontend -> notifier: 🐌 Updated @ Notifier
deactivate frontend

@enduml 
