@startuml ISSUE
 
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker
    'participant "Consumer 💼" as consumer
    participant "Issuer 🎴" as issuer
end box

box Itemizer 🛢  #FFFFFA
    participant "Hooks" as hooks
end box

participant "Broker 🤵" as broker
'participant "Vault 🗄️" as vault

activate script
    script -> talker: ISSUE 🎫
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {hook}
    talker --> broker: SEND 📬 {Offer 🐌 hook}
    activate broker
    talker -> talker: WAIT {hook}
deactivate talker

        broker --> issuer: Accepted 🐌 {hook}
    deactivate broker

activate issuer
    issuer -> talker: REEL 🎣 {hook, data}
deactivate issuer

activate talker
    talker -> script: RETURN \n{schema, data}
deactivate talker

activate script
deactivate script

@enduml 
