@startuml Wallet: Share Token


participant "Issuer 🎴" as issuer
participant "Wallet 👱" as user
participant "Consumer 💼" as consumer
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph
'participant "Notifier 📣" as notifier


' --------------------
' QUERY
' --------------------

user <-- issuer: 1) Save Token ⏩

user --> consumer: 2)  Share Token ⏩


issuer --> broker: 3) Revise 🐌

'group Offline verification

    consumer -> broker: 4) Status 🚀

    activate broker
    activate consumer
        broker -> graph: 5) Trusts 🚀
        broker -> consumer: {status}
    deactivate broker

    deactivate consumer

'end group

@enduml 