@startuml OnPopPopped
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Popped 🐌" as pop
    participant "Pops 🪣" as pops
    participant "OnPopped@ 🔔" as popped
    participant "Talker 😃" as talker
end box

wallet --> pop: Popped 🐌 {chat}

activate pop
    pop -> pops: SAVE 💾 {POPPED}
deactivate pop

activate pops
    pops --> popped: POPPED 🔔
deactivate pops

activate popped
    popped -> talker: CHAT 💬 
    popped --> wallet: ONE 🤔 {what?}
deactivate popped

activate wallet
    wallet --> popped: 
deactivate wallet

activate popped
    popped -> pops: SAVE 💾 {...}
deactivate popped

@enduml 
