@startuml Clone

actor "User" as user
participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Filer 🌲\nvault" as filer

'group Register

    activate filer
        filer --> wallet: 1) ⏪ Prompt 🤔 {what? ➜ clone} 
        filer -> filer: stage
        filer --> wallet: 2) ⏪ Prompt ⓘ { pin 🄰 }
    deactivate filer    

        user --> syncer: 3) $ clone { pin 🄰 }

    activate syncer 
        syncer -> user: show pin 🄱
        syncer -> filer: Clone 🚀 { 🄰🄱 }
    deactivate syncer
        
    activate filer
        filer -> syncer: { cloned }
        filer --> wallet: ⏪ Prompt 🤔 { sent pin 🄱? ➜ yes }
        filer -> filer: activate
        filer --> wallet: ⏪ Prompt ✔ { OK, sync now } 
    deactivate filer

    user --> syncer: 5) Sync ⏩
    

'end group

@enduml