@startuml Sync

participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Filer 🌲\nvault" as filer

syncer -> filer: 1) Map 🚀
activate syncer

    activate filer
        'filer -> filer: stage
        filer -> syncer: {map}
    deactivate filer

    syncer -> filer: 2) Upload 🚀 {file}
    
    activate syncer
        syncer -> filer
        activate syncer
            syncer -> filer
            'activate syncer
            '    syncer -> filer
            'deactivate syncer
        deactivate syncer
        'syncer -> filer
    deactivate syncer

    syncer -> filer: 3) Uploaded 🚀
deactivate syncer

activate filer
    filer -> syncer: {changes}
deactivate filer

activate syncer
    syncer -> filer: 4) Download 🚀 {file}
    activate syncer
        syncer -> filer
        activate syncer
            syncer -> filer
            'activate syncer
                'syncer -> filer
            'deactivate syncer
        deactivate syncer
        'syncer -> filer
    deactivate syncer
deactivate syncer

@enduml