@startuml Broker.Schemas

box Broker 🤵 domain #FFFFFA
    participant "Chats, Binds, Tokens 🪣" as propagate
    participant "Wallets 🪣" as wallets
    participant "Schemas 🪣" as schemas
    participant "Frontend 🪣" as frontend
end box
participant "Graph 🕸" as graph
participant "Notifier 📣" as notifier


propagate -> schemas: 💾 Propagate Parents 
activate schemas
    wallets -> schemas: 💾 {language}
    
    schemas -> graph: 🔔 OnInsert: 🚀 Schema @ Graph
    activate graph
        graph -> schemas: 💾 {details}
    deactivate graph

    schemas -> graph: 🔔 OnLocalized: 🚀 Translate @ Graph
    activate graph
        graph -> schemas: 💾 {translations}
    deactivate graph

    schemas -> frontend: 🔔 OnAltered: 💾 SAVE

deactivate schemas

activate frontend
    frontend -> notifier: IF changed: 🐌 Updated@
deactivate frontend

@enduml 
