@startuml Handle

participant "User 🧑" as user
box Hoster ☁️ domain #FFFFFA
    participant "Host 🤗" as host
    participant "Script 📃" as script
    participant "Talker 😃" as talker
end box
participant "Hosted 📦" as hosted

'activate host
    script --> user: 1 ⏪ PROMPT 🤔
'deactivate host

activate user
    user --> host: Reply 🐌
deactivate user

activate host
    host --> talker: 
deactivate host

activate talker
    talker --> hosted: 2) Handle 🐌 {function}
deactivate talker
    
activate hosted
        
    hosted -> talker: 3) Placed 🚀 {$placeholder}

    activate talker
        talker -> hosted: {$placeholder value}
    deactivate talker

    hosted --> talker: 4) Handled 🐌 {result}
deactivate hosted

activate talker
    talker --> host: {prompt}
deactivate talker

activate host
    host --> user: 5 ⏪ Prompt 🤔
deactivate host

@enduml