@startuml Pop@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as pop
    participant "Wallets 🪣" as wallets
    participant "Pops 🪣" as pops
end box


activate wallet 
    wallet --> pop: Pop 🐌 {context, key}
deactivate wallet

activate pop
    pop -> wallets: READ 🧲
    pop -> pops: SAVE 💾
deactivate pop



@enduml 
