@startuml VERIFY Token 🎫

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "VERIFY ⌘ Token 🎫" as verify
end box
participant "Graph 🕸" as graph 
participant "Broker 🤵" as broker


activate script
    script -> verify: VERIFY 🔐 {token}

activate verify
    
    verify -x script: 🚦 ASSERT {starts, expires}

    verify -> graph: 📬 SEND 🚀 PublicKey@Graph {issuer, dkim}
    activate graph
        graph -> verify: {key}
    deactivate graph

    verify -x script: 🔐 VERIFY ᝰ🖊 Signature 💥

    verify -> graph: 📬 SEND 🚀 Schema@Graph {code}
    activate graph
        graph -> verify: {schema}
    deactivate graph

    verify -x script: 🔐 VERIFY 🧩 Schema 💥

    verify -> broker: 📬 SEND 🚀 Status@Broker {token, issuer}
    activate broker
        broker -> verify: {status}
    deactivate broker

    verify -x script: 🚦 ASSERT {active} 💥

    verify -> script: RETURN ✅ 

deactivate verify

          
@enduml