@startuml VERIFY Token 🎫

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "VERIFY 🔐 Token 🎫" as verify
end box
participant "Graph 🕸" as graph 
participant "Broker 🤵" as broker


activate script
    script -> verify: VERIFY 🔐 {token}

activate verify
    
    verify -x script: 🚦 ASSERT .IsToken
    verify -x script: 🚦 ASSERT {starts, expires}

    verify -> graph: VERIFY 🔐 Domain 👥
    verify -x script: invalid signature 💥 

    verify -> graph: VERIFY 🔐 Schema 🧩
    verify -x script: invalid schema 💥

    verify -> broker: SEND 📬 Status@Broker 🚀 {token, issuer}
    activate broker
        broker -> verify: {status}
    deactivate broker

    verify -x script: 🚦 ASSERT {ACTIVE} 💥

    verify -> script: RETURN ✅ 

deactivate verify

          
@enduml