@startuml Present

participant "Helper 🤲" as helper
participant "Broker 🤵" as broker
participant "Biller 🤝" as biller
participant "Payer 💳" as payer
participant "Identifier 🆔" as id
participant "Wallet 🧑" as user

activate helper
    helper -> user: INFORM
    helper -> user: BIND
    helper -> broker: Invite
deactivate helper

activate broker
    user --> broker: OK
    broker --> biller: Invite 🐌
deactivate broker

activate biller
    biller -> user: ONE 🤔 {plan?}
    biller --> payer: Share {link} 🐌
deactivate biller

activate payer
    user <-- payer: ⏪ Prompt 
    payer --> biller: Consume {link} 🐌
deactivate payer

activate biller
    biller --> id: Share {sign}
deactivate biller

activate id
    user <-- id: ⏪ Prompt {card}
    id --> biller: Consume {link} 🐌
deactivate id


' ------------
@enduml