@startuml OnDiscloseReady

box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as discloses
    participant "OnReady 🔔" as ready
end box
participant "Consumer 💼" as consumer


activate discloses
    discloses --> ready: READY 🔔 
deactivate discloses

activate ready
    ready --> consumer: SEND 📬 {Consume 🐌}
deactivate ready

activate consumer
    consumer -> discloses: Collect 🚀
deactivate consumer

@enduml 