@startuml Invite

participant "Consumer 💼 " as host
box "Broker 🤵" #FFFFFA
    participant "Handler 📃" as broker
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as invitee
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user


activate broker
    broker -> user: CONFIRM 🤔
    broker -> invitee: SAVE 💾 {HELPER} 
deactivate broker

@enduml 