@startuml 💼 Consumer.Invites 🪣 table
 
box Consumer 💼 domain #FFFFFA
    participant "INVITE ⌘" as talker
    participant "Invites 🪣" as table
end box
participant "Graph 🕸" as graph
participant "Helper 🤲" as helper


activate talker
    talker --> table: SAVE 💾 {INVITED}
deactivate talker

activate table
    table -> graph: 🔔 INVITED: TRUSTS 🫡 {helper} ❌ UNTRUSTED
    table --> helper: 🔔 TRUSTED: Invite @ Broker 🐌 
deactivate table

activate helper
    helper --> table: 🐌 Helped @ Consumer 
deactivate helper

activate table
    table -> graph: 🔔 HELPED: VERIFY 🔐 {data, schema} ❌ INVALID 
    table -> talker: 🔔 VALID: RACE 🏁 
deactivate table


@enduml 
