@startuml 💼 Consumer.Invites 🪣 table
 
box Consumer 💼 domain #FFFFFA
    participant "INVITE ⌘" as talker
    participant "Invites 🪣" as table
end box
participant "Graph 🕸" as graph
participant "Helper 🤲" as helper


activate talker
    talker -> table: 💾 INVITED
deactivate talker

activate table
    table -> graph: TRUSTS 🫡 {helper}
deactivate table

activate graph
    graph -> table: 💾 TRUSTED ✅ UNTRUSTED ❌
deactivate graph

activate table
    table -> helper: Invite @ Broker 🐌 
deactivate table

activate helper
    helper -> table: 🐌 Helped @ Consumer 💾 HELPED
deactivate helper

activate table
    table -> graph: VERIFY 🔐 {data, schema}
deactivate table

activate graph
    graph -> table: 💾 VALID ✅ INVALID ❌
deactivate graph

activate table
    table -> talker: RACE 🏁 
deactivate table


@enduml 
