@startuml FILTER
 
box Talker 😃 domain #FFFFFA
    
    participant "Script 📃" as script
    participant ".FILTER 📃" as talker

    participant ".MANY 📃" as many
    participant "Host 🤗" as host
    'participant "Consumer 💼" as consumer
end box

participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: FILTER 🔽 {options}
deactivate script

activate talker
    talker -> many: MANY 🔠 {options}
deactivate talker

activate many
    many --> broker: Prompt 🐌 {options}
deactivate many


activate broker
    broker --> wallet:
deactivate broker

activate wallet
    wallet --> host: Reply 🐌 {selected}
deactivate wallet

activate host
    host -> many:
deactivate host

activate many
    many -> talker:
deactivate many

activate talker
    talker -> script: RETURN {selected}
deactivate talker

activate script
deactivate script

@enduml 
