@startuml PopToken
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Token 🔆" as popped
    participant "Tokens 🪣" as tokens   
end box

wallet -> popped: Pop 🎈 {Token}


activate popped
    popped -> tokens: SELECT 🧲 
    popped -> wallet: INFO ⓘ {token}
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {selection, token}
deactivate popped

@enduml 
