@startuml OnQueryDisclosed

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnDisclosed 🔔" as handler
end box
participant "Vault 🗄️" as vault
participant "Consumer 💼" as consumer

activate table
    table --> handler: DISCLOSED 🔔
deactivate table

activate handler
    handler --> vault: SEND 📬 {Disclose@ 🐌}
deactivate handler

activate vault
    vault --> consumer: Consume@ 🐌 {data}
deactivate vault
    

@enduml