@startuml SHARE
 
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant ".TRANSLATE 📃" as translate
    participant "Talker 😃" as talker
end box

participant "Graph 🕸\ndomain" as graph

activate script
    script -> translate: TRANSLATE 
deactivate script
activate translate

alt with Text
    translate -> talker: .Translate()
    activate talker
        talker -> translate: {translation}
    deactivate talker
end alt

alt with Domain or Schema

        translate -> talker: SEND
    'deactivate translate

    activate talker
        talker -> graph:  Translate 🚀

        activate graph
            graph -> talker: {translations}
        deactivate

        talker -> translate: {translations}
    deactivate talker

'activate translate
end alt

    translate -> script: RETURN {translations}
deactivate translate

activate script
deactivate script

@enduml 
