@startuml SHARE
 
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant ".TRANSLATE 📃" as translate
    'participant "Talker 😃" as talker
end box

participant "Graph 🕸\ndomain" as graph

activate script
    script -> translate: TRANSLATE 
deactivate script

activate translate

    translate -> graph: SEND 📬 Identity 🚀
    translate -> graph: SEND 📬 Schema 🚀
    translate -> translate: $.Chat.Language
    translate -> translate: .Translate()

    translate -> script: RETURN {translations}
deactivate translate

activate script
deactivate script

@enduml 
