@startuml Consumer@Consumer

participant "Vault 🗄️" as vault

box Hoster ☁️ domain #FFFFFA
    participant "Consumer 💼" as consumer
    participant "Talker 😃" as talker
    participant "Script 📃" as script
end box

box Itemizer 🛢 domain #FFFFFA
    participant "Hooks 🪣" as hooks
end box

participant "Graph 🕸" as graph

activate vault
    vault --> consumer: Consume 🐌 {hook, collect}
deactivate vault

activate consumer
    consumer -> hooks: GET {hook}
    consumer -> graph: TRUSTS 🫡 {vault, schema}
    consumer -> vault: SEND 📬 Collect 🚀 {collect}
    
    activate vault
        vault -> consumer: {data}
    deactivate vault

    consumer --> talker: REEL 🎣 {hook, data}
deactivate consumer

activate talker
    talker --> script: RETURN {data}
deactivate talker

activate script
deactivate script

@enduml 