@startuml OnChatPresented

participant "Finder 🔎" as finder

box Broker 🤵 domain #FFFFFA
    participant "Presented@ 📃" as script
    participant "Chats 🪣" as chats
    participant "OnPresented 🔔" as handler
    participant "Chatters 🪣" as chatters
end box

activate finder
    finder -> script: Presented 🐌
deactivate finder

activate script
    script -> chats: SAVE 💾 {PRESENTED}
deactivate script

activate chats
    chats --> handler: PRESENTED 🔔
deactivate chats

activate handler
    handler -> chatters: SAVE 💾 {BROKER}
deactivate handler

@enduml