@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant ".TALK 📃" as talk
    participant "Talkers 🪣" as talkers
    participant "Handler 📃" as talker
end box


activate script
    script -> talk: TALK 😃
deactivate script

activate talk
    talk -> talkers: READ 🧲 {$.Chat.Key}
    activate talkers
        talkers -> talk: {$talker}
    deactivate talkers
    talk -> talker: RUN {$talker.Script}
deactivate talk

activate talker
    
@enduml