@startuml Wallet: Share()


actor "User\nInterface" as user
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(domain)" as consumer
participant "Vault 🗄️\n(domain)" as vault
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer

group Request

    consumer --> broker: 1) Query  🐌
    deactivate consumer

    ' Broker 🤵
    activate broker 
    broker -> graph: 2) Queryable 🚀 {codes}
    broker -> graph: 3) Translate 🚀 {codes}

    alt Select if 2+ vaults
        broker --> user: 4 ⏪ Prompt 🤔
        deactivate broker

        activate user
            user --> broker: {selected}
        deactivate user

        activate broker
    end alt

    broker --> vault: 5) Disclose 🐌 {code}
    deactivate broker

    activate vault

end group

group Assess

    ' Get te context.
    vault -> consumer: 6) Context 🚀 
    activate consumer
    consumer --> vault: {context}
    deactivate consumer

    ' Ask user to confirm.
    vault --> user: 7 ⏪ Prompt 🤔 {confirm?}
end group

vault --> consumer: 8 ⏪ Consume 🧩
deactivate vault 



@enduml 