@startuml OnChatLocalized
 

box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph



activate chats
    chats --> handler: UPDATED 🔔 {language}
deactivate chats

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> chats: SAVE 💾 {translation}
deactivate handler


@enduml 
