@startuml OnDomainLocalized
 

box Broker 🤵 domain #FFFFFA
    participant "Domains 🪣" as domains
    participant "OnLocalized 🔔" as handler
end box
participant "Graph 🕸" as graph


activate domains
    domains --> handler: UPDATED 🔔 {language}
deactivate domains

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler -> domains: SAVE 💾 {translation}
deactivate handler


@enduml 
