@startuml 🤲 Helper.OnBillable

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnInvited 🔔" as event
end box
participant "Biller 🤝" as biller


table --> event: BILLABLE 🔔

activate event
    event -> biller: SEND 📬 {Bill @ Biller 🐌}
    event -> table: BILLED ✅
deactivate event    

@enduml 