@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnInvited 🔔" as event
    'participant "Help 🐌" as handler
    participant "Schemas 🪣" as schemas
    participant "Script 📃" as script
end box
'participant "Graph 🕸" as graph
'participant "Biller 🤝" as biller
'participant "Consumer 💼 " as consumer

table --> event: INVITED 🔔

activate event
    event -> schemas: READ 🧲
    event -> script: RUN 🏃 {schema.script}
deactivate event

activate script
    script -> event: RETURN {result}
deactivate script

activate event
    event -> table: SAVE 💾 {help}
    event -> consumer: SEND 📬 {Helped @ Consumer 🐌}
    event -> biller: SEND 📬 {Bill @ Biller 🐌}
    event -> table: HELPED ✅
deactivate event    

@enduml 