@startuml Vault.Binds

box Vault 🗄️ domain #FFFFFA
    participant "Script  📃" as script
    participant "BIND ⌘" as cmd
    participant "Binds 🪣" as binds
    participant "Hosted 📦" as hosted
end box
participant "Broker 🤵" as broker


activate script
    script -> cmd: BIND ⌘ {schema, ref}
deactivate script

activate cmd
    cmd -> binds: 💾 {OFFERED}
deactivate cmd

activate binds
    binds -> broker: 🐌 Bind @ Broker 
deactivate binds

activate broker
    broker -> binds: IF "no": 🐌 Bound @ Vault 💾 {DECLINED}
activate binds
    broker -> binds: IF "yes": 🐌 Bound @ Vault 💾 {BOUND}
deactivate broker

    group IF {BOUND, ref}
        binds -> hosted: ASYNC 👷🏼 {Bound, ref}
    end group

    binds -> cmd: REEL 🎣 {result}

deactivate binds

activate cmd
    cmd -> script: RETURN {result}
deactivate cmd

@enduml 