@startuml OnChatOpened

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Opened@ 📃" as script
    participant "Chats 🪣" as chats
    participant "OnOpened 🔔" as handler
    participant "Chatters 🪣" as chatters
end box


activate script
    script -> chats: SAVE 💾 {OPENED}
deactivate script

activate chats
    chats --> handler: OPENED 🔔
deactivate chats

activate handler
    handler -> chatters: SAVE 💾 {FINDER}
deactivate handler

@enduml