@startuml OnShareTrusted


box Vault 🗄️ domain #FFFFFA
    participant "Shares 🪣" as shares
    participant "OnAsked 🔔" as asked
end box

participant "Hosted 📦" as hosted



activate shares
    shares --> asked: TRUSTED 🔔 
deactivate shares

activate asked
    asked --> hosted: CALL 🧮 {disclose}
deactivate asked

activate hosted
    hosted --> asked: {result}
deactivate hosted

activate asked
    asked -> shares: UPDATE 💾 {READY, result}
deactivate asked

@enduml 