@startuml Unbind 


' ---------------------
actor "User" as user 
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Vault 🗄️\nhost" as vault
 

' There's a chat with the vault.
activate vault
    vault --> wallet: ⏪ Prompt 🤔
deactivate vault

' Activate the broker.
user --> wallet: broker 🤵
activate wallet
    wallet --> broker: 1) Pop 🐌 {VAULT}
deactivate wallet
activate broker
    broker --> wallet: 2) ⏪ Prompt 🤔 {what?}
deactivate broker

' User asks to unbind.
activate wallet
    user --> wallet: unbind
    wallet --> broker: {unbind}
deactivate wallet

' BROKER. UNBIND
activate broker
    broker --> wallet: 3) ⏪ Update Binds 🔗
    broker --> vault: 4) Unbound 🐌
deactivate broker


' ---------------------
@enduml 