' https://quip.com/5rXfA36af1FM

@startuml
' ----------------------

participant "Seller 💵" as seller
participant "Broker 🤵" as broker
participant "Payer 💳" as payer
participant "Wallet 👱" as wallet
participant "Collector 🏦" as collector
participant "Notifier 📣" as notifier
actor User as user
participant "Graph 🕸" as graph



group Ask for the bill

activate seller
    seller --> collector: Register 🐌
    seller --> broker: Charge 🐌 
deactivate seller

activate broker
    broker --> payer: 🐌 Disclose @ Vault
deactivate broker

activate payer
    payer --> wallet: ONE 🤔 "how to pay?"
deactivate payer

activate wallet
    wallet -> seller: 🚀 Download @ Host {bill}
    wallet --> payer: 🐌 Reply @ Host 
deactivate wallet

activate payer
    payer -> payer: transfer funds 💵
    payer --> collector: 🐌 Consume @ Consumer
deactivate payer

activate collector
    collector -> payer: Collect @ Vault 🚀 {transfer proof}
    collector --> seller: 🐌 Consume @ Consumer
deactivate collector

activate seller
    seller -> collector: Collect @ Vault 🚀 {transfer proof}
deactivate seller

activate broker
    broker --> notifier: charge@
deactivate broker

    activate notifier
    notifier --> wallet
    deactivate notifier

      activate wallet
      wallet -> seller: download bill
      user --> wallet: review()

end group

group Pay for bill

  wallet --> seller: {OK} 
  deactivate wallet

' ----------------------
' CHARGE
' ----------------------
activate seller
seller --> broker: charge\n- collectors
deactivate seller
activate broker

loop for each collector

activate broker
broker -> graph: trustable \n- collector \n- payers 
activate graph
broker <- graph: {payer sets}
deactivate graph
deactivate broker

end loop

broker -> broker: merge(sets)
broker --> notifier: charge(payers)
deactivate
activate notifier
notifier --> wallet: charge(...)
deactivate notifier

end group

' ----------------------
@enduml 