@startuml PopBind
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Bind 🔆" as popped
    participant "Binds 🪣" as binds
end box

wallet -> popped: Pop 🎈 {Bind}


activate popped
    popped -> binds: SELECT 🧲
    popped -> wallet: INFO ⓘ {bind}
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {selection, bind}
deactivate popped

@enduml 
