@startuml VERIFY Domain 👥

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "VERIFY 🔐 Domain 👥" as verify
end box
participant "Graph 🕸" as graph 


activate script
    script -> verify: VERIFY 🔐 {data...}

activate verify

    verify -> graph: GRAPH 🕸 PublicKey 🚀 {domain, dkim}

    activate graph
        graph -> verify: {key}
    deactivate graph

    verify -x script: VERIFY 🔐 Signature ᝰ🖊 {signature, key, ...} 💥

    verify -> script: RETURN ✅ 

deactivate verify

          
@enduml