@startuml Broker.Chatters 

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as table
    participant "Pops 🪣" as pops
end box

wallet -> chats: 🐌 Opened @ Broker

activate chats
    chats -> table: 💾 POP
deactivate chats

activate table
    table -> pops: 💾 POPPED
deactivate table

activate pops
    pops -> wallet: 🐌 Prompt @ Notifier
deactivate pops

@enduml