@startuml OnBindRemoved
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop@ 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "OnRemoved 🔔" as handler
end box

participant "Vault 🗄️" as vault

wallet --> script: Pop 🐌

activate script
    script -> binds: DELETE 🗑️
deactivate script

activate binds
    binds -> handler: DELETED 🔔
deactivate binds

activate handler
    handler --> vault: SEND 📬 {Unbound@}
deactivate handler


@enduml 
