@startuml WEB

box Host 🤗 domain #FFFFFD
    participant "Script 📃" as script
    participant "WEB ⌘" as WEB
    participant "PROMPT ⌘" as PROMPT
end box
participant "Wallet 👱" as wallet


activate script
    script -> WEB: WEB 🌐 {url}
deactivate script

activate WEB
    WEB -> PROMPT: SHOW 🌐 {url}
deactivate WEB

activate PROMPT
    PROMPT --> wallet: 
deactivate PROMPT




@enduml