@startuml WEB

box Host 🤗 domain #FFFFFD
    participant "Script 📃" as script
    participant "WEB ⌘" as WEB
    participant "PROMPT ⌘" as PROMPT
end box
participant "Web Page 🌐" as page
participant "Wallet 👱" as wallet


activate script
    
    script -> page: prepare {hook, context}
    activate page
        page -> script: {url}   
    deactivate page

    script -> WEB: WEB 🌐 {text, url, hook}
deactivate script

activate WEB
    WEB -> PROMPT: RUN
deactivate WEB

activate PROMPT
    PROMPT --> wallet: Prompt@Broker 🐌 {text, url}
activate wallet
    PROMPT -> WEB
deactivate PROMPT

activate WEB
    WEB -> WEB: WAIT ⏳ {hook}
deactivate WEB


    wallet --> page: open {url}
activate page
    wallet --> page: "submit"
deactivate wallet
    page --> WEB: RACE 🏁 {hook, result}
deactivate page

activate WEB
    WEB -> script: RETURN {result}
deactivate WEB

activate script
    


@enduml