@startuml OnTokenSaved

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Saved 🐌" as saved
    participant "Tokens 🪣" as tokens
    participant "OnSaved 🔔" as onSaved
end box

'participant "Notifier 📣" as notifier
participant "Issuer 🎴" as issuer

wallet --> saved: Saved 🐌 

activate saved
    saved -> tokens: SAVE 💾 {SAVED}
deactivate saved

activate tokens
    tokens --> onSaved: SAVED 🔔
deactivate tokens

activate onSaved
    onSaved --> issuer: SEND 📬 {Offered 🐌 ACCEPTED}
deactivate onSaved

@enduml 