@startuml Accept()


' ----------------------
actor "User\nin chat" as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\ndomain" as broker
participant "Issuer 🎴\ndomain" as issuer
participant "Graph 🕸\ndomain" as graph


activate issuer
    issuer --> wallet: 1) ⏪ Prompt 🤔 {transact?}
deactivate issuer

activate wallet
    user --> wallet: transact
    wallet --> issuer: 
deactivate wallet

activate issuer
    issuer --> broker: 2) Offer 🐌 {hook}
deactivate issuer

activate broker
    broker -> graph : 3) Translate 🚀 {code}
    
    activate graph
        graph --> broker: {translation}
    deactivate graph

    broker --> wallet: 4) ⏪ Prompt 🤔 {save?}
deactivate broker

activate wallet 
    user --> wallet: save
    wallet --> broker: {Yes}
deactivate wallet

group If user accepted


activate broker
    broker --> notifier: 5) Save 🐌 {token}
deactivate broker

' NOTIFY
activate notifier
    notifier --> wallet
deactivate notifier

' ACCEPT
activate wallet
    ' DOWNLOAD
    wallet -> issuer: 6) Issued 🚀
    activate issuer
        issuer -> wallet: {token}
    deactivate issuer
    wallet -> wallet: save

    ' CONFIRM
    wallet --> broker: 7) Saved 🐌 { token, path }
deactivate wallet

' NOTIFY
activate broker
    broker --> wallet: 8) ⏪ Update Tokens 🎫

end group

    broker --> issuer: 9) Accepted {hook, token} 🐌
deactivate broker

activate issuer
    issuer --> wallet: A) ⏪ Prompt 🤔
deactivate issuer


' ----------------------
@enduml