@startuml Accept()


' ----------------------
actor "User" as user
participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph
participant "Issuer 🎴" as issuer


activate issuer
    issuer --> wallet: 1) ⏪ Prompt 🤔 {transact?}
deactivate issuer

activate wallet
    user --> wallet: transact
    wallet --> issuer: 
deactivate wallet

activate issuer
    issuer --> broker: 2) Offer 🐌 {hook}
deactivate issuer

activate broker
    broker -> graph : 3) Translate 🚀 {code}
    
    activate graph
        graph --> broker: {translation}
    deactivate graph

    broker --> wallet: 4) ⏪ Prompt 🤔 {save?}
deactivate broker

activate wallet 
    user --> wallet: yes
    wallet --> broker: 
deactivate wallet

group If user accepted


activate broker
    broker --> notifier: 5) Save 🐌 {token}
deactivate broker

' NOTIFY
activate notifier
    notifier --> wallet
deactivate notifier

' ACCEPT
activate wallet
    ' DOWNLOAD
    wallet -> issuer: 6) Issued 🚀
    activate issuer
        issuer -> wallet: {token}
    deactivate issuer
    wallet -> wallet: save

    ' CONFIRM
    wallet --> broker: 7) Saved 🐌 { token, path }
deactivate wallet

activate broker
end group

    broker --> issuer: 8) Accepted {hook, token} 🐌
deactivate broker

activate issuer
    issuer --> wallet: 9) ⏪ Prompt 🤔
deactivate issuer


' ----------------------
@enduml