@startuml Broker.Tokens.Updates
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
participant "Issuer 🎴" as issuer
    
    

wallet -> tokens: 🐌 Pop » Token » Remove 💾 {REMOVED}

activate tokens
    tokens -> wallet: 🐌 Remove 
    tokens -> issuer: 🐌 Removed
    tokens -> frontend: 💾 {remaining tokens}
deactivate tokens

activate frontend
    frontend -> wallet: 🐌 Updated 
deactivate frontend

@enduml 
