@startuml 👉 Host NFC-QR check-in
' ------------

actor User as user  
participant "Wallet 👱\napp" as wallet
participant "Broker 🤵\nhost" as broker
participant "Locator 🔆\nNFC/QR" as qr
participant "Host 🤗\ndomain" as host


group Print locators
    host --> qr: print
end group

user -> wallet: scan ✨

activate wallet
    wallet -> qr: scan ✨
    wallet --> broker: 1) Assess ⏩
deactivate wallet

activate broker
    broker --> host:  2) Hello 🐌
deactivate broker

activate host
    host --> wallet: 3) ⏪ Prompt 🤔 {what?}
deactivate host

activate wallet
    user --> wallet: reply
deactivate wallet


' ------------
@enduml