@startuml ⚙️ OnChatsInform 

box Broker 🤵 #FFFFFA
    participant "Chats 🪣" as table
    participant "OnInform 🔔" as event
end box
participant "Graph 🕸" as graph
participant "Wallet 🧑" as user

table -> event: INFORM 🔔

activate event
    event -> graph: Form @ Graph 🚀
    event --> user: CONFIRM 👍
deactivate event

activate user
    user --> event:  "yes"
deactivate user

activate event
    event -> table: SAVE 💾 {INFORMED}
deactivate event

@enduml 