@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnInvited 🔔" as event
end box
participant "Graph 🕸" as graph


table --> event: INVITED 🔔
activate event
    event -> graph: TRUSTS 🫡 {consumer, schema} 
    event -x table: UNTRUSTED ❌
    event -> table: TRUSTED ✅
deactivate event

@enduml 