
@startuml Update tokens

 
' ---------------------
actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker

 
activate broker
   
    broker --> notifier: 1) Updated 🐌  
    
deactivate broker

activate notifier
    notifier --> wallet
deactivate notifier

activate wallet
wallet -> broker: 2) Chats 🚀
activate broker
    broker -> wallet: { chats }
deactivate broker
deactivate wallet

' ---------------------
@enduml 