@startuml ASK
 
box Talker 😃 domain #FFFFFA
    
    participant "Script 📃" as script
    participant ".ASK 📃" as talker

    'participant ".MANY 📃" as many
    'participant "Host 🤗" as host
    'participant "Consumer 💼" as consumer
end box

'participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: ASK 🔽 {options}
deactivate script

activate talker
    talker --> wallet: MANY 🔠 {options}
deactivate talker

activate wallet
    wallet --> talker:  {selected}
deactivate wallet

activate talker
    talker -> script: RETURN {selected}
deactivate talker

activate script
deactivate script

@enduml 
