@startuml OnChatCreated

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Locate@ 📃" as script
    participant "Chats 🪣" as table
    participant "OnCreated 📃" as handler
end box

participant "Graph 🕸" as graph

'wallet --> script: Pop 🐌


activate script
    script -> table: SAVE 💾 {CREATED}
deactivate script

activate table
    table --> handler: CREATED 🔔
deactivate table

activate handler
    handler -> graph: TRANSLATE 🈯
    handler -> table: SAVE 💾 {DETAILED}
deactivate handler

@enduml 
