@startuml PopChatMute
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "PopChat 😃" as onChat
    participant "...Mute 😃" as onMute
    participant "Chats 🪣" as chats
end box

    
wallet -> onChat: PopChat 🔆 {chat}

activate onChat
    wallet -> onChat: "mute"
    onChat -> onMute: RUN {chat.*}
deactivate onChat

activate onMute
    onMute -> chats: SAVE 💾 {muted: True}
    onMute -> wallet: DONE ✅ "muted"
deactivate onMute

wallet -> onMute: "unmute"

activate onMute
    onMute -> chats: SAVE 💾 {muted: False}
    onMute -> wallet: DONE ✅ "unmuted"
deactivate onMute


@enduml 
