@startuml Placed@Talker

participant "Hosted 📦" as hosted

box Talker 😃️ domain #FFFFFA
    participant "Inbox 📨" as inbox
    participant "Holders 🪣" as holders
end box


activate hosted
    hosted -> inbox: Placed 🚀 {$p}

    activate inbox
        inbox -> holders: GET {chat, $p}
        inbox -> hosted: RETURN {value}
    deactivate inbox

deactivate hosted

@enduml