@startuml
' ------------------
participant "Payer 💳\ndomain" as payer
actor "User" as user
participant "Machine\nQR 🔆" as qr
participant "Machine\ndraw" as draw
participant "Vending 🏪\ndomain" as shop
participant "Collector 🏦\ndomain" as collector
' ------------------
user -> qr: scan

activate user
user -> shop: hello()
deactivate user

  activate shop
  shop -> user: "what?"
  deactivate shop

activate user
user -> shop: {buy}
deactivate user

  activate shop
  shop -> user: "item number?"
  deactivate shop

activate user
user -> shop: {123}
deactivate user

  activate shop
  shop -> user: "water bottle?"
  deactivate shop

activate user
user -> shop: {yes}
deactivate user

  activate shop
  shop -> user: charge($1.50)
  deactivate shop

activate user
user -> payer: pay()
deactivate user

    activate payer
    payer -> collector: collect()
    deactivate payer

      activate collector
      collector -> shop: paid!
      deactivate collector

  activate shop
  shop -> draw: open()
  shop -> user: "success!"
  shop -> user: goodbye()
  deactivate shop

' ------------------
@enduml