@startuml OnTokenChanged

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Script 📃" as script
    participant "Tokens 🪣" as tokens
    participant "OnChanged 📃" as change
end box

participant "Notifier 📣" as notifier

'wallet --> script: Pop 🐌

activate script
    script -> tokens: SAVE, DELETE
deactivate script

activate tokens
    tokens --> change: trigger 🔔
deactivate tokens

activate change
    change --> notifier: Updated 🐌
deactivate change

@enduml 
