@startuml PopBindRemove
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Bind 🔆" as bind
    participant "Remove 🔆" as remove
    participant "Binds 🪣" as binds
end box


wallet -> bind: Pop 🎈 {Bind}

activate bind    
    wallet -> bind: "remove"
    bind -> remove: RUN {bind}
deactivate bind

activate remove
    remove -> wallet: CONFIRM 👍 "remove?"
    remove -> binds: SAVE 💾 {REMOVED}
    remove -> wallet: DONE ✅ "removed"
    remove -> : GOODBYE 👋
deactivate remove
 
@enduml 
