@startuml Setup Thing Wi-Fi

title 
    📶 3) Wi-Fi: Setup Thing Wi-Fi
end title

legend top
    Conditions:
        * The user has the thing turned on (plugged to a power socket).
        * The user has the RJ45 connector device.
    Steps: 
        1. The user switches on the RJ45/Wi-Fi connector:
            a) the device turns on the L1 light saying it has power.
            b) the device starts the Wi-Fi direct signal.
            c) once the the Wi-Fi direct it's enabled, the L2 light turns on.
        2. The user plugs in the RJ45 cable to the thing:
            a) the L3 light turns on when the RJ45 connection is established.
end legend

' ----------------------

box "🤖 Thing" #FFFFFA
participant "RJ45\nThing" as thing
participant "NFC QR\nCode" as qr2
end box

box "📶 RJ45/WiFi" #FAFFFF
participant "RJ45/Wi-Fi\nConnector" as connector
participant "Wi-Fi\nDirect" as wifiDirect
participant "NFC QR\nCode" as qr 
end box

box 🖨️ Printer #FFFFFA
participant "Printer\n(domain)" as printer
end box

box "👱 User" #FFFDFF
participant "Wallet\nApp" as app
actor "User Phone" as user
participant "Home\nWi-Fi" as wifi
end box


group Setup Thing Wi-Fi
  
  connector -> connector: 1. switch on()
  activate connector 
  connector -> connector: L1 on()
  connector -> wifiDirect: enable()
  connector -> connector: L2 on()
  deactivate connector 

  thing -> connector: 2. plug RJ45()
  activate connector 
  connector -> connector: L3 on()
  deactivate connector 

end group


' ----------------------
@enduml