@startuml OnPromptEmojied


box Broker 🤵 domain #FFFFFA
    participant "Prompts 🪣" as table
    participant "OnEmojied 🔔" as handler
end box

participant "Notifier 📣" as notifier



activate table
    table --> handler: EMOJIED 🔔
deactivate table

activate handler
    handler --> notifier: SEND 📬 {Prompt 🐌}
deactivate handler


@enduml