@startuml OnQueryTrusted

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnTrusted 🔔" as handler
end box
participant "Wallet 👱" as wallet


activate table
    table --> handler: TRUSTED 🔔
deactivate table

activate handler

    group If are many
        handler -> wallet: ONE 🤔 "Which one?" 
    end group

    alt IF IsEmpty
        handler -> table: SAVE 💾 {REJECTED} 
    else 
        handler -> table: SAVE 💾 {SELECTED} 
    end

deactivate handler

@enduml