@startuml OnInviteTrusted

box Consumer 💼 domain #FFFFFA
    participant "Invites 🪣" as table
    participant "OnTrusted 🔔" as handler
end box
participant "Broker 🤵" as broker

table --> handler: TRUSTED 🔔 

activate handler
    handler --> broker: SEND 📬 {Invite 🐌}
deactivate handler

@enduml 