@startuml OnChatOpened

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Opened@ 📃" as script
    participant "Chats 🪣" as chats
    participant "OnOpened 🔔" as handler
    participant "Chatters 🪣" as chatters
end box

participant "Finder 🔎" as finder



wallet --> script: Opened 🐌

activate script
    script -> chats: SAVE 💾 {OPENED}
deactivate script

activate chats
    chats --> handler: OPENED 🔔
deactivate chats

alt IF Host is Broker

    activate handler
        handler -> chatters: SAVE 💾 {POP}

else IF not Broker

    
        handler -> chatters: SAVE 💾 {FINDER}
    deactivate handler

    activate chatters
        chatters --> finder: Present 🐌
    deactivate chatters

    activate finder
        finder --> chats: Presented 🐌 {PRESENTED} 
    deactivate finder

end alt

@enduml