@startuml Setup

' -----------
actor User as user
participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Vault 🗄️" as vault

' WALLET
user --> wallet: install

activate wallet

    group Register public key

        wallet -> wallet: keys*
        wallet -> notifier: 1) Onboard 🚀 \n {public key}

        activate notifier
            notifier -> broker: 2) Onboard 🚀
        
            ' BROKER
            activate broker
                broker -> broker: wallet*
                broker -> notifier: {wallet ID}
            'deactivate broker 

            notifier -> wallet: {wallet ID}

        deactivate notifier

    deactivate wallet
end group


group Ask for region

    broker --> wallet: 3) ⏪ Prompt {region?}
    deactivate broker

    activate wallet
        user --> wallet: region
        wallet --> broker: {region}
    deactivate wallet
    
    activate broker
        
end group 


group Bind agents (loop)

    broker --> vault: 4) Bind ⏩
    broker --> wallet: ⏪ Prompt {agent defaulted!}

end group

broker --> wallet: ⏪ Prompt {done!}

deactivate broker 

' -----------
@enduml