@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "Engine ⚙️" as engine
    participant "Memory 🧠" as memory
    participant "Holders 🪣" as holders
    participant "Inbox 📨" as inbox
end box

participant "Hosted 📦" as hosted

activate script
    script -> engine: CALL {X into $A}
    activate engine
        engine -> memory: READ 🧲 {A}
    deactivate engine

    script -> engine: CALL {function} 
deactivate script


activate engine
    engine --> hosted: Handle 🐌 {function, hook}
activate hosted
    engine -> holders: WAIT 🧘 {hook}
deactivate engine
          
    hosted -> inbox: Placed 🚀 {$A}

    activate inbox
        inbox -> holders: READ 🧲 {A}
        inbox -> hosted: {X}
    deactivate inbox

    hosted -> inbox: Place 🚀 {Y into $B}
    activate inbox
        inbox -> holders: SAVE 💾 {B:Y}
    deactivate inbox

    hosted --> inbox: Handled 🐌 {hook}
deactivate hosted

activate inbox
    inbox -> engine: REEL 🎣 {hook}
deactivate inbox

activate engine
    engine -> script: RETURN
deactivate engine

activate script
    script -> engine: CALL {$B}
activate engine
    engine -> script: {Y}
deactivate engine
deactivate script


@enduml