@startuml OnBindBound


box Vault 🗄️ domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnBound 🔔" as trigger
    participant "BIND ⌘" as bind
    participant "Script  📃" as script
end box


activate binds
    binds --> trigger: BOUND 🔔
deactivate binds

activate trigger
    trigger --> bind: REEL 🎣 {bind}
deactivate trigger


activate bind
    bind -> script: RETURN {bind}
deactivate bind

@enduml 