@startuml OnBindBound

participant "Broker 🤵" as broker

box Vault 🗄️ domain #FFFFFA
    participant "Bound 🐌" as script
    participant "Binds 🪣" as binds
    participant "OnBound 🔔" as trigger
    participant "BIND ⌘" as bind
end box


broker --> script: Bound 🐌

activate script
    script -> binds: SAVE 💾 {BOUND}
deactivate script

activate binds
    binds --> trigger: BOUND 🔔
deactivate binds

activate trigger
    trigger --> bind: REEL 🎣 {bind}
deactivate trigger


@enduml 