@startuml Hello@Host

participant "Broker 🤵" as broker
box Host domain #FFFFFA
    participant "Hello 🐌" as handler
    participant "Locators 🪣" as locators
    participant "Script 📃" as script
end box
participant "Graph 🕸" as graph


activate broker
    broker --> handler: Hello 🐌 {chat}
deactivate broker

activate handler
    handler -> graph: VERIFY 🔐 {msg} 
    handler -> graph: TRUSTS 🫡 {msg.from, .BROKER 🧩}
    handler -> broker: CHAT 💬 {msg.from, chat}
    handler -> locators: READ 🧲 {chat.key}
    handler -> script: RUN {locator.script}
deactivate handler


@enduml 
