@startuml Goodbye
' ------------------

actor "User" as user
participant "Broker 🤵\nhost" as broker
participant "Biller 🤝\ndomain" as biller
participant "Ads 👀\nhelper" as ads
participant "Host 🤗\ndomain" as host
participant "Curator 🧚\nagent" as curator



activate broker

    broker -> biller: -/1) new bill()
    activate biller
        biller -> broker: {bill ID}
    deactivate biller


    broker --> ads: 1) Advertise 🐌👀 {context}
    activate ads

    group time-boxed enrichment with anonymized chat
    
        broker --> host: 2) Summarize 🐌🤗
        deactivate broker

        activate host
            host --> ads: 3) Summarized 🐌👀
            host --> curator: 4) Anonymize 🐌🧚
        deactivate host
        
        activate curator
            curator --> ads: 5) Anonymized 🐌👀
        deactivate curator

    end group

    group sort ads

        'activate ads
            ads --> curator: 6) Sort 🐌🧚
        'deactivate ads

        activate curator
            curator --> ads: 7) Sorted 🐌👀
        deactivate curator

    end group



group show ads

    activate ads
        ads --> user: 8) ⏪ Prompt 🤔 {next best actions}
    deactivate ads
    
    ' Answer to reviewer.
    activate user
        user --> ads: {user choice}
    deactivate user

    ' Confirm reviewed to broker.
    activate ads
        ads --> broker: 9) Promote 🐌🤵 {locator}
    deactivate ads

    
end group


' ------------
@enduml 