@startuml 👉 Printer NFC-QR check-in
' ------------

participant "Wallet 👱" as wallet  
'participant "Notifier 📣\nbff" as notifier
'participant "Finder 🔎\nvault" as finder
'participant "Printer 🖨️\nsupplier" as printer


box "Broker 🤵" #FFFFFA
    participant "Handler 📃" as broker
    participant "Wallets 🪣" as wallets
    participant "Engine ⚙️" as engine
end box



activate wallet
  wallet --> broker: Assess 🐌 {hook, locator}
deactivate wallet


activate broker

    broker -> wallets: READ {from}

    broker -> engine: RUN Resolve-Alias 
    activate engine
        engine -> broker: {$locator}
    deactivate engine
    
    broker -> engine: RUN Save-Chat
    activate engine
        engine -> broker: {chat}
    deactivate engine

    broker -> engine: RUN Save-Host

    broker -> engine: RUN Call-Converse
    broker -> engine: RUN Call-Introduce


deactivate broker


@enduml