@startuml Home@Host
 
participant "Broker 🤵" as broker
box Host 🤗 domain #FFFFFD
    participant "Home 🐌" as handler
    participant "Chats 🪣" as chats
    participant "Locators 🪣" as locators
end box
participant "Graph 🕸" as graph


broker --> handler: Home 🐌 

activate handler
    handler -> graph: VERIFY 🔐 {msg}
    handler -> chats: READ 🧲
    handler -> locators: TALK 😃
deactivate handler


@enduml 
