@startuml ASYNC

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "ASYNC 👷🏼" as async
end box

participant "Hosted 📦" as hosted


activate script
    script -> async: ASYNC 👷🏼 {uuid, task, inputs} 
deactivate script

activate async
    async --> hosted: SEND 📬 {Handle@ 🐌 task, uuid, inputs}
    activate hosted
    async -> script: 
deactivate async
activate script
          


@enduml