@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant ".ASYNC 📃" as async
end box

participant "Hosted 📦" as hosted


activate script
    script -> async: ASYNC {task, inputs} 
deactivate script

activate async
    async -> async: hook: {.UUID}
    async --> hosted: SEND {Handle 🐌 task, hook, inputs}
    activate hosted
    async -> script: RETURN {hook}
deactivate async
activate script
          


@enduml