@startuml OnInviteAdded

box "Broker 🤵" #FFFFFA
    participant "Invites 🪣" as invites
    participant "OnAdded 🔔" as broker
end box
participant "Helper 🤲" as helper



invites --> broker: ADDED 🔔 

activate broker
    broker --> helper: SEND 📬 {Invited@ 🐌}
    broker -> invites: SAVE 💾 {DONE}
deactivate broker

@enduml 