@startuml Wait

participant "User 🧑\ndomains" as user
box Hoster 💭 domain #FFFFFA
    participant "Host 🤗\nrole API" as host
    participant "Talker 😃\nrole API" as talker
end box
participant "Hosted 🧑‍💻\non-prem" as hosted


activate talker
    talker --> hosted: 1) Handle 🐌 {start}
deactivate talker

activate hosted
    hosted -> hosted: start...
    hosted --> talker: 2) Handled 🐌 

    activate talker
        talker --> user: 3 ⏪ Prompt {started}
        talker -> talker: 4) Wait ⏳ {signal}
    deactivate talker

    hosted -> hosted: running...
    hosted -> talker: 5) Read 🚀 {placeholder}
    activate talker
        talker --> hosted: {value}
    deactivate talker


    hosted -> hosted: ...end
    hosted --> talker: 6) Write 🐌 {signal} 
deactivate hosted

activate talker
    talker --> user: 7 ⏪ Prompt {done!}
deactivate talker

@enduml