@startuml Query@Broker

participant "Consumer 💼 " as host
box "Broker 🤵" #FFFFFA
    participant "Query 🐌" as broker
    participant "Chatters 🪣" as chatters
    participant "Queries 🪣" as queries
end box
participant "Graph 🕸" as graph


activate host
    host --> broker: Query 🐌
deactivate host

activate broker
    broker -> graph: VERIFY 🔐 {msg}
    broker -> chatters: READ 🧲 
    broker -> queries: SAVE 💾 {QUERIED}
deactivate broker

@enduml 