@startuml OnChatDetail

box Host 🤗 domain #FFFFFA
    participant "Chats 🪣" as table
    participant "OnDetail 🔔" as script
end box
participant  "Broker 🤵" as broker


table --> script: DETAIL 🔔

activate script
    
    script -> broker: SEND 📬 Chat @ Broker 🚀
    
    activate broker
        broker -> script: { chat details }
    deactivate broker

    script -> table: 💾 BINDS

deactivate script



@enduml 
