@startuml SignToken

participant "Issuer 🎴" as issuer
participant "Broker 🤵" as broker
box Identity 🆔 domain #FFFFFA
    participant "SignToken 😃" as script
    participant "Stamps 🪣" as tokens
end box


activate issuer
issuer -> broker: SHARE 💼 \n  .ID/TOKEN/SIGN 🧩

activate broker
    broker --> script: Disclose@Vault 🐌 
deactivate broker

activate script
    script -> tokens: SAVE 💾 {wallet, issuer}

    script -> issuer: {stamp}
deactivate script

    
@enduml