@startuml VerifyToken

participant "Consumer 💼" as consumer
participant "Broker 🤵" as broker
box Identity 🆔 domain #FFFFFA
    participant "VerifyToken 😃" as script
    participant "Stamps 🪣" as tokens
    participant "Selfie 📸" as identify
end box
participant "Wallet 👱" as wallet


activate consumer
consumer -> broker: INVITE 🤲 .\n  ID/TOKEN/PROXY 🧩 \n  {identity, stamp}


activate broker
    broker -> script: INVITE 🤲 \n  TOKEN/VERIFY 🧩 {stamp}
deactivate broker

activate script
    script -> tokens: READ 🧲 {stamp}
    script -> identify: RUN {user}
deactivate script

activate identify
    identify -> wallet: selfie 📸
    identify -> script: 
deactivate identify


activate script
    script -> broker: 
deactivate script

activate broker
    broker -> consumer: 
deactivate broker


    
@enduml