@startuml PopBind
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "PopBind 😃" as popped
    participant "Binds 🪣" as binds
end box

wallet -> popped: PopBind 🔆 {bind, vault}


activate popped
    popped -> binds: SELECT 🧲 {bind, vault, wallet}
    popped -> wallet: INFO ⓘ {bind.*}
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {selection, bind.*}
deactivate popped

@enduml 
