@startuml Scan Wallet QR

title REVIEW THIS - IT'S OUTDATED!

' ------------------
actor "User" as user
participant "Host\n(domain)" as domain
participant "QR\nParser" as parser
participant "Broker\n(domain)" as aws
' ------------------
' SCAN WALLET QR
' ------------------
user --> domain: tap (wallet QR)
activate domain
domain -> parser: parse(wallet QR)
activate parser
parser -> domain: process(issuer,locator)
deactivate parser
' ------------------
' START SESSION
' ------------------
domain --> aws: welcome(locator)
deactivate domain
' ------------------
@enduml


