@startuml 👉 Printer NFC-QR check-in
' ------------

participant "Wallet 👱\napp" as wallet  
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Printer 🖨️\nsupplier" as printer
participant "Finder 🔎\nvault" as finder


activate wallet
  wallet --> broker: Assess 🐌 {locator}
deactivate wallet


activate broker

    group Translate, if .ALIAS 🧩 and not cached 

        broker -> printer: 1) Details 🚀

        activate printer
            printer -> broker: {host locator}
        deactivate printer

    end group


    broker --> wallet: 2) ⏪ Converse {chat}

    broker --> finder: 3) Introduce ⏩ {chat}
    deactivate broker

' ------------
@enduml