@startuml OnPromptReplied
 
box Host 🤗 domain #FFFFFD
    participant "Prompts 🪣" as prompts
    participant "OnReplied 🔔" as handler
    participant "Talker 😃" as talker
end box

prompts --> handler: REPLIED 🔔
activate handler
    handler -> talker: REEL 🎣 {prompt, answer}
deactivate handler


@enduml 
