@startuml Setup()

' ----------------------
box Sender Domain #FFFFFF
participant "Sender\nOutbox 🚀" as api1
participant "Sender\nDNS 🌐" as dns1
end box

box Receiver Domain #FFFFFF
participant "Receiver\nDNS 🌐" as dns2
participant "Receiver\nInbox 📨" as api2
end box


api1 --> dns1: public key
api2 --> dns2: inbox


' ----------------------
@enduml