@startuml Broker.Bind.Remove
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as script
    participant "Binds 🪣" as binds
end box
participant "Vault 🗄️" as vault


wallet -> script: Pop 🐌 {BIND}
activate script
    wallet -> script: {remove}
    script -> binds: 💾 REMOVED
deactivate script

activate binds
    binds -> vault: Unbound 🐌
deactivate binds

@enduml 
