@startuml OnPopTokenRevised
 
box Broker 🤵 domain #FFFAFA
    participant "Chats 🪣" as chats
    participant "Pops 🪣" as pops
end box
participant "Wallet 👱" as wallet


activate chats
    chats --> pops: 💾 POPPED
deactivate chats

activate pops
    pops -> pops: CHAT 💬
    pops --> wallet: INFO ⓘ {status}
deactivate pops


@enduml 
