@startuml Goodbye
' ------------------

participant "Wallet 🧑" as user
participant "Broker 🤵" as broker
participant "Review ⭐" as reviewer
participant "Host 🤗" as host
participant "Graph 🕸" as graph
participant "Finder 🔎" as finder


host --> graph: {manifest}

activate broker
    broker --> reviewer: 1) Help@Helper 🐌
deactivate broker

group Ask user feedback

    activate reviewer
        reviewer -> graph: 2) Service@Graph 🚀
        reviewer --> user: 3) ⏪ Prompt 🤔
    deactivate reviewer

    ' Answer to reviewer.
    activate user
        user --> reviewer: {rate}
    deactivate user

    ' Confirm reviewed to broker.
    activate reviewer
        
        loop Follow-up questions
            reviewer --> user: ⏪ Prompt 🤔 {why?}
        end loop


end group

group Delayed fan out of anonymous feedback 

        reviewer --> host: 4) Rated@Host 🐌

        reviewer --> finder: 5) ⏩ ingest {rated}

    deactivate reviewer

end group






' ------------
@enduml 