@startuml Forward

participant "User 🧑\ndomains" as user
participant "Host 🤗\ndomain" as host
participant "Talker 😃\nhelper" as talker

activate talker
    talker --> host: 1) Forward 🐌 {📨}
deactivate talker

activate host
    host --> user: 2) ⏪ Request 📨
deactivate host

activate user

user --> host: 3) Reply 🐌 {prompt}
activate host
user --> host: 5) Receive 🐌 {token}
user --> host: 7) Consume 🐌 {bind}
deactivate user
host --> talker: 8) Returned 🐌 {data}
deactivate host


@enduml

