@startuml OnChatterHost


box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "OnActivated 🔔" as script
    participant "Chatters 🪣" as table
    participant "OnHost 🔔" as handler
end box

participant "Host 🤗" as host


chats --> script: ACTIVATED 🔔

activate script
    script -> table: SAVE 💾 {HOST}
deactivate script

activate table
    table --> handler: HOST 🔔
deactivate table

activate handler
    handler --> host: SEND 📬 {Hello 🐌}
deactivate handler

@enduml