@startuml OnBindDetailed
 
'participant "Wallet 👱" as wallet
'participant "Vault 🗄️" as vault

box Broker 🤵 domain #FFFFFA
    participant "OnCreated 🔔" as created
    'participant "Bind@ 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "OnDetailed 🔔" as detailed
end box

participant "Wallet 👱" as wallet



created -> binds: SAVE 💾 {DETAILED}
activate binds
    binds --> detailed: DETAILED 🔔
deactivate binds

activate detailed
    detailed -> detailed: CHAT 💬
    detailed -> wallet: CONFIRM 👍 {accept?} 
deactivate detailed

alt Kept

    activate wallet
        wallet --> detailed: Yes
'    deactivate wallet

    activate detailed
        detailed ->  binds: SAVE 💾 {ACCEPTED}
    deactivate detailed


else Rejected

'    activate wallet
        wallet --> detailed: No
    deactivate wallet

    activate detailed
        detailed ->  binds: SAVE 💾 {REJECTED}
    deactivate detailed

end alt

@enduml 
