@startuml ⚙️ Form

participant "Consumer 💼" as consumer
box Broker 🤵 #FFFFFA
    participant "Inform 🐌" as broker
    participant "Chatters 🪣" as chatters
    participant "Forms 🪣" as forms
end box
participant "Graph 🕸" as graph


consumer --> broker: Inform 🐌

activate broker
    broker -> graph: VERIFY 🔐 {msg}
    broker -> chatters: READ 🧲
    broker -> forms: SAVE 💾 {INFORM}
deactivate broker


@enduml 