@startuml PopRemoveToken
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Bind 🔆" as bind
    participant "Binds 🪣" as binds
end box


wallet -> bind: POP 🎈 {Token}

activate bind    
    wallet -> bind: "tag"
    bind -> wallet: TEXT 🔠 "tag?"
    bind -> binds: SAVE 💾 {tag}
    bind -> wallet: DONE ✅ "changed"
    bind -> : GOODBYE 👋
deactivate bind
 
@enduml 
