@startuml OnPopChat
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chat 🔆" as popped
end box

wallet --> popped: POP 🎈 {Chat}


activate popped
    popped -> popped: CHAT 💬 
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {...}
deactivate popped

@enduml 
