@startuml Pop@Broker

 
participant "Wallet 👱" as wallet

box Hoster ☁️ domain #FFFFFA
    participant "Broker 🤵" as broker
    participant "Wallets 🪣" as wallets
    participant "Bind 📃" as bind
    participant "Host 📃" as host
    participant "Issuer 📃" as issuer
    participant "Token 📃" as token
    participant "Vault 📃" as vault
end box

activate wallet
wallet --> broker: Pop 🐌
deactivate wallet

activate broker
    broker -> wallets: READ {wallet}

    alt Context {BIND}
        broker -> bind: RUN {PopBind}
    else Context {HOST}
        broker -> host: RUN {PopHost}
    else Context {ISSUER}
        broker -> issuer: RUN {PopIssuer}
    else Context {TOKEN}
        broker -> token: RUN {PopToken}
    else Context {VAULT}
        broker -> vault: RUN {PopVault}
    end
    
deactivate broker

@enduml 
