@startuml Wallet: Share Token


actor User as user
participant "Wallet 👱\n(app)" as wallet
participant "Notifier 📣\n(domain)" as notifier
participant "Broker 🤵\n(domain)" as broker
participant "Consumer 💼\n(host)" as consumer
participant "Identity 🆔\n(vault)" as identity
participant "Graph 🕸\n(domain)" as graph

' --------------------
' QUERY
' --------------------

activate consumer
group Request ID check

    consumer -> graph: 8. Trusts@ {identity}
    consumer --> broker: 9. Query@ 
    deactivate consumer

    activate broker
        broker --> identity: Delegate@ {ID locator}
    deactivate broker

    activate identity
        identity -> graph: Trusts@ 


end group

group Verify ID

        identity --> broker: Prompt@
    deactivate identity

    activate broker
        broker --> notifier: Prompt@
    deactivate broker

    activate notifier
        notifier --> wallet
    deactivate notifier

    ' Wallet 👱
    activate wallet
        wallet -> identity: prompted@
        activate identity
            identity -> wallet: {prompt}
        deactivate identity

        user --> wallet: selfie
        wallet -> identity: iframe@

        activate identity
            identity -> wallet: {liveness html page}
        deactivate identity

        wallet --> identity: reply@
    deactivate wallet
    activate identity

end group


group Confirm ID 

        identity --> consumer: consume@ 
    deactivate identity

    ' CONSUMER
    activate consumer   
        consumer -> graph: Trusts@ {identity}
        'consumer -> identity: collect@
        'activate identity
        '    identity -> consumer: {data}
        'deactivate identity

end group

    deactivate consumer

@enduml 