@startuml OnOfferOffered


box Vault 🗄️ domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnOffered 🔔" as trigger
    'participant "Talker 😃" as talker
end box

participant "Broker 🤵" as broker

activate binds
    binds --> trigger: OFFERED 🔔
deactivate binds

activate trigger
    trigger --> broker: SEND 📬 {Bind@ 🐌} 
deactivate trigger


@enduml 