@startuml Opened@Broker

participant "Wallet 👱" as wallet

box "Broker 🤵 domain"  #FFFFFA
    participant "Opened@ 📃" as broker
    participant "Pops 🪣" as pops
    participant "Chats 🪣" as chats
end box
    

activate wallet
    wallet --> broker : Opened 🐌
deactivate wallet

activate broker
    alt is pop?
        broker -> pops: READ 🧲 
        broker -> pops: SAVE 💾 {OPENED}
    else
        broker -> chats: READ 🧲 
        broker -> chats: SAVE 💾 {OPENED}
    end
deactivate broker

@enduml