@startuml Opened@Broker

participant "Wallet 👱" as wallet

box "Broker 🤵 domain"  #FFFFFA
    participant "Opened@ 📃" as broker
    participant "Chats 🪣" as chats
end box
    

activate wallet
    wallet --> broker : Opened 🐌
deactivate wallet

activate broker
    broker -> chats: READ 🧲 
    broker -> chats: SAVE 💾 {OPENED}
deactivate broker

@enduml