@startuml Prompted@Host
 
participant "Wallet 👱" as wallet
box Host 🤗 domain #FFFFFD
    participant "Prompted 🚀" as handler
    participant "Prompts 🪣" as prompts
    participant "Chats 🪣" as chats
end box

wallet -> handler: Prompted 🚀 
activate wallet

    activate handler
        handler -> prompts: READ 🧲
        handler -> chats: VERIFY 🔐 {chat.PublicKey}
        handler -> wallet: {prompt}
    deactivate handler

deactivate wallet

@enduml 
