@startuml Wait

participant "User 🧑" as user
box Hoster ☁️ domain #FFFFFA
    'participant "Host 🤗\nrole API" as host
    participant "Script 📃" as script
    participant "Talker 😃" as talker
end box
participant "Hosted 📦" as hosted

script --> talker: ASYNC 👷🏼
activate script
activate talker

talker --> hosted:  Handle 🐌 {task}
deactivate talker

activate hosted
script --> user: ⏪ TEMP ⏳ {started}

script --> talker: WAIT ⏸️
deactivate script

hosted --> talker: Handled 🐌 {partial}
activate talker
    talker --> script:
deactivate talker

activate script
    script --> user: ⏪ TEMP ⏳ {running...}
    script --> talker: REPEAT 🔁 
    script --> talker: WAIT ⏸️
deactivate script
    
    hosted --> talker: Handled 🐌 {done}
deactivate hosted

activate talker
    talker --> script:
deactivate talker

activate script 
    script --> user: ⏪ SUCCESS ✅ {done!}
deactivate script

@enduml