@startuml CHAT
' TODO

participant  "Broker 🤵" as broker
box Host 🤗 domain #FFFFFA
    participant "Script 📃" as script
    participant ".CHAT 📃" as engine
    participant "$.Chat 🧠" as holder
    participant "Chats 🪣" as table
    participant "Binds 🪣" as binds
    participant "Tokens 🪣" as tokens
end box



activate script
    script -> engine: CHAT 💬
deactivate script

activate engine
    engine -> broker: SEND 📬 Chat @ Broker 🚀

    activate broker
        broker -> engine: { chat details }
    deactivate broker

    engine -> table: READ 🧲
    engine -> binds: 
    engine -> tokens: 
    engine -> table: SAVE 💾
    engine -> holder: SET 
    engine -> script:
deactivate engine

activate script
deactivate script

@enduml 
