@startuml Assess
' ------------

actor User as user  

'box "User Interface (UI)"  #FFFFFF
  participant "Wallet 👱\napp" as wallet
  participant "Notifier 📣\nbff" as notifier
  participant "Broker 🤵\nhost" as broker
'end box

participant "Printer 🖨️\nsupplier" as printer
participant "Finder 🔎\nvault" as finder
participant "Host 🤗\ndomain" as host


activate broker

    group Resolve, if @ALIAS 🧩 and not cached 

        broker -> printer: 1) Resolve 🚀

        activate printer
            printer -> broker: {host locator}
        deactivate printer

    end group

    'alt No host session?

        broker --> wallet: 2) ⏪ Converse 💬
        activate wallet
        

        broker --> finder: 3) Introduce ⏩
        deactivate broker
            activate finder
                finder --> wallet: 4) ⏪ Prompt ⓘ {intro}
                finder --> broker
            deactivate finder
        activate broker

    'end alt

    broker --> wallet: 5) ⏪ Prompt ⓘ {origin}
    broker --> wallet: 6) ⏪ Prompt ⓘ {tokens}
    broker --> host:  7) Hello 🐌
deactivate broker

activate host
    host --> wallet: 8) ⏪ Prompt ⓘ {context}
    host --> wallet: 9) ⏪ Prompt 😃 {what do you need?}
deactivate host

    user --> wallet: reply
deactivate wallet


' ------------
@enduml