@startuml Sync

participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Resourcer 🗃️\nvault" as resourcer

syncer -> resourcer: 1) Map 🚀
activate syncer

    activate resourcer
        'resourcer -> resourcer: stage
        resourcer -> syncer: {map}
    deactivate resourcer

    syncer -> resourcer: 2) Upload 🚀 {file}
    
    activate syncer
        syncer -> resourcer
        activate syncer
            syncer -> resourcer
            'activate syncer
            '    syncer -> resourcer
            'deactivate syncer
        deactivate syncer
        'syncer -> resourcer
    deactivate syncer

    syncer -> resourcer: 3) Uploaded 🚀
deactivate syncer

activate resourcer
    resourcer -> syncer: {changes}
deactivate resourcer

activate syncer
    syncer -> resourcer: 4) Download 🚀 {file}
    activate syncer
        syncer -> resourcer
        activate syncer
            syncer -> resourcer
            'activate syncer
                'syncer -> resourcer
            'deactivate syncer
        deactivate syncer
        'syncer -> resourcer
    deactivate syncer
deactivate syncer

@enduml