' https://quip.com/5rXfA36af1FM

@startuml
' ----------------------

participant "Seller 💵" as seller
participant "Broker 🤵" as broker
participant "Notifier 📣" as notifier
participant "Wallet 👱" as wallet
actor User as user
participant "Payer 💳" as payer
participant "Graph 🕸" as graph



group Ask for the bill

activate seller
seller --> broker: charge@
deactivate seller

  activate broker
  broker --> notifier: charge@
  deactivate broker

    activate notifier
    notifier --> wallet
    deactivate notifier

      activate wallet
      wallet -> seller: download bill
      user --> wallet: review()

end group

group Pay for bill

  wallet --> seller: {OK} 
  deactivate wallet

' ----------------------
' CHARGE
' ----------------------
activate seller
seller --> broker: charge\n- collectors
deactivate seller
activate broker

loop for each collector

activate broker
broker -> graph: trustable \n- collector \n- payers 
activate graph
broker <- graph: {payer sets}
deactivate graph
deactivate broker

end loop

broker -> broker: merge(sets)
broker --> notifier: charge(payers)
deactivate
activate notifier
notifier --> wallet: charge(...)
deactivate notifier

end group

' ----------------------
@enduml 