@startuml Broker.Binds.Localize
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🎈" as pop
    participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
participant "Graph 🕸" as graph
participant "Notifier 📣" as notifier


wallet -> pop: Pop 🎈 {WALLET}
activate pop
    wallet -> pop: {language: X}
    pop -> wallets: 💾 {language}
deactivate pop    

activate wallets
    wallets -> tokens: 💾 {language}
deactivate wallets

activate tokens
    tokens -> graph: TRANSLATE 🈯 {vault, schema}
    tokens -> frontend: 💾 {tokens}
deactivate tokens

activate frontend
    frontend -> notifier: IF changed: 🐌 Updated
deactivate frontend

@enduml 
