@startuml OnQueryAbrupt

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnAbrupt 🔔" as handler
end box
participant "Wallet 👱" as wallet


activate table
    table --> handler: ABRUPT 🔔
deactivate table

activate handler
    handler -> handler: CHAT 💬
    handler --> wallet: FAIL ❌ "not informed"
deactivate handler

@enduml