@startuml Goodbye
' ------------------

actor "User" as user
participant "Host 🤗\ndomain" as host
participant "Broker 🤵\nhost" as broker
participant "Ads 👀\nhelper" as ads
participant "Review ⭐\nagent" as reviewer


activate host
    host --> broker: 1) goodbye@
deactivate host

activate broker    
    broker --> ads: 2) advertise ⏩
    broker --> reviewer: 3) review ⏩
deactivate broker



' ------------
@enduml 