@startuml Pop@Vault
' TODO
 

box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
end box

participant "Vault 🗄️" as vault
participant "Broker 🤵" as broker
'participant "Wallet 👱" as wallet

activate script
    script -> binds: GET

    script -> script: PARALLEL 
    activate script
        script -> binds: DELETE
        script --> vault: SEND {Unbound@}
    deactivate script

    script --> broker: SEND {Updated@}
deactivate script
 
@enduml 
