@startuml Prompts (blocking)
 
box Host 🤗 domain #FFFFFD
    participant "Blocking ⌘" as script
    participant "PROMPT 🤔" as PROMPT
    participant "Prompts 🪣" as table
    participant "Appendixes 🪣" as appendixes
end box
participant "Wallet 👱" as wallet

 
activate script
    script -> PROMPT: PROMPT 🤔 
deactivate script

activate PROMPT
    PROMPT -> appendixes: SAVE 💾 
    PROMPT -> table: 

activate table
    table -> PROMPT: {prompt}
    PROMPT -> PROMPT: WAIT 🧘 {prompt}
deactivate PROMPT
    table --> wallet: Prompt @ Broker 🐌 {prompt}
deactivate table


activate wallet
    wallet -> appendixes: Download 🚀
    wallet --> table: Reply @ Host 🐌 {prompt, reply}
deactivate wallet

activate table
    table -> PROMPT: RACE 🏁 {prompt, reply}
deactivate table

activate PROMPT
    PROMPT -> script: RETURN {reply}
deactivate PROMPT

activate script
deactivate script

@enduml 
