@startuml SHARE
 
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker
    participant "Host 🤗" as host
    'participant "Consumer 💼" as consumer
end box

box Itemizer 🛢  #FFFFFA
    participant "Hooks" as hooks
end box

participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: .PROMPT 🤔 
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {hook, prompt}
    talker --> broker: Prompt 🐌 {hook}
activate broker

    alt Non-blocking 
        alt With Options
            talker -> talker: HOOK 🪝 {hook}
        end alt
        talker -> script: RETURN { }
    else Blocking
        talker -> talker: WAIT 🧘 {hook}
    end alt

deactivate talker

    broker --> wallet:
deactivate broker

activate wallet
    wallet -> host: Prompted 🚀 {hook}
    
    activate host
        host -> hooks: GET 🧲 {hook}
        host -> wallet: {prompt}
    deactivate host

    wallet --> host: Reply 🐌 {hook, reply}
deactivate wallet

activate host
    host -> talker: REEL 🎣 {hook, reply}
deactivate host

activate talker
    talker -> script: RETURN {reply}
deactivate talker

activate script
deactivate script

@enduml 
