@startuml SHARE
 
box Talker 😃 domain #FFFFFD
    participant "Script 📃" as script
    participant ".PROMPT 📃" as talker
    participant "Hooks 🪣" as hooks
    participant "Handler 📃" as handler
end box

box Hoster ☁️ domain #FFFFFA
    participant "Host 🤗" as host
end box

participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: .PROMPT 🤔 
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {hook, prompt}
    talker --> host: SEND {Prompt 🐌 hook}
    activate host
        host --> broker: 
    deactivate host
activate broker

    alt Non-blocking 
        alt With Options
            talker -> talker: HOOK 🪝 {hook}
        end alt
        talker -> script: RETURN { }
    else Blocking
        talker -> talker: WAIT 🧘 {hook}
    end alt

deactivate talker

    broker --> wallet:
deactivate broker

activate wallet
    wallet -> host: Prompted 🚀 {hook}
    
    activate host
        host -> handler
        activate handler
            handler -> hooks: GET 🧲 {hook}
            handler -> host: {prompt}
        deactivate handler
        host -> wallet: 
    deactivate host

    wallet --> host: Reply 🐌 {hook, reply}
deactivate wallet

activate host
    host -> handler: 
deactivate host

activate handler
    handler -> talker: REEL 🎣 {hook, reply}
deactivate handler

activate talker
    talker -> script: RETURN {reply}
deactivate talker

activate script
deactivate script

@enduml 
