@startuml Broker.Tokens.Issued
 
participant "Issuer 🎴" as issuer
box Broker 🤵 domain #FFFFFA
    participant "Issue 🐌" as issue
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
participant "Graph 🕸" as graph
participant "Wallet 👱" as wallet

issuer -> issue: Issue 🐌 

activate issue
    issue -> tokens: 💾 {ISSUED}
deactivate issue

activate tokens
    tokens -> graph: Translate 🚀
    activate graph
        graph -> tokens: 💾 {DETAILED}
    deactivate graph
    tokens -> wallet: Prompt 🐌 "accept?" 
deactivate tokens

activate wallet
    wallet -> tokens: 🐌 Reply 💾 {OFFERED}
deactivate wallet

activate tokens
    tokens -> issuer: IF "no": 🐌 Offered 💾 {DECLINED}
    tokens -> wallet: IF "yes": Save 🐌
deactivate tokens

activate wallet
    wallet -> tokens: 🐌 Saved 💾 {SAVED}
deactivate wallet

activate tokens
    tokens -> issuer: Offered 🐌 {answer:accepted}
    tokens -> frontend: 💾 {tokens}
deactivate tokens

activate frontend
    frontend -> wallet: 🐌 Updated 
deactivate frontend



@enduml 
