@startuml OnQueryTrusted

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnTrusted 🔔" as handler
end box
participant "Vault 🗄️" as vault
participant "Graph 🕸" as graph


table --> handler: TRUSTED 🔔 

activate handler
    handler -> vault: SEND 📬 {Collect@ 🚀}

    activate vault
        vault -> handler: {data}
    deactivate vault

    handler -> graph: VERIFY 🔐 {schema}

    handler -x table: SAVE 💾 {BROKEN, data}
    handler -> table: SAVE 💾 {COLLECTED, data}

deactivate handler

@enduml 