@startuml Broker.Queries

participant "Consumer 💼" as consumer
box Broker 🤵 domain #FFFFFA
    participant "Query 🐌" as script
    participant "Queries 🪣" as queries
    participant "Forms 🪣" as forms
    participant "Wallets 🪣" as wallets
end box
participant "Graph 🕸" as graph
participant "Wallet 👱" as wallet
participant "Vault 🗄️" as vault

consumer -> script: Query 🐌

activate script
    script -> queries: 💾 QUERIED
deactivate script

activate queries
    queries -> forms: informed?
deactivate queries

activate forms
    forms -> queries: 💾 INFORMED ✅ ABRUPT ❌
deactivate forms

activate queries
    queries -> wallets: READ 🧲 {Binds, Tokens}
deactivate queries

activate wallets
    'wallets -x consumer: 💾 EMPTY 🐌 Suggest @ Consumer 
    wallets -> queries: 💾 DETAILED ✅ EMPTY ❌
deactivate wallets

activate queries
    queries -> graph: Trusts @ Graph 🚀
deactivate queries

activate graph
    'graph -x consumer: 💾 EMPTY 🐌 Suggest @ Consumer 
    graph -> queries: 💾 TRUSTED ✅ EMPTY ❌
deactivate graph

activate queries
    queries -> wallet: ONE "Select"
    queries -> wallet: CONFIRM 👍 "Share?"
deactivate queries

activate wallet
    wallet -> queries: 💾 DISCLOSED or SHARED ✅ REJECTED ❌
deactivate wallet

activate queries
    queries -> wallet: ✅ SHARED: Share @ Notifier 🐌
    queries -> vault: ✅ DISCLOSED: Disclose @ Vault 🐌
deactivate queries


@enduml