@startuml Broker.Queries

participant "Consumer 💼" as consumer
box Broker 🤵 domain #FFFFFA
    participant "Query 🐌" as script
    participant "Queries 🪣" as queries
    participant "Forms 🪣" as forms
    participant "Wallets 🪣" as wallets
end box
participant "Graph 🕸" as graph
participant "Wallet 👱" as wallet
participant "Vault 🗄️" as vault

consumer -> script: Query 🐌

activate script
    script -> queries: SAVE 💾
deactivate script

activate queries
    queries -> forms: 🔔 QUERIED: informed? ❌ ABRUPT 
    queries -> wallets: 🔔 INFORMED: READ 🧲 {Binds, Tokens} ❌ UNMATCHED 
    queries -> graph: 🔔 MATCHED: TRUSTS 🫡 {consumer} ❌ UNTRUSTED 
    queries -> wallet: 🔔 TRUSTED: ONE 🤔 "Select" ❌ UNSELECTED 
    queries -> wallet: 🔔 SELECTED: CONFIRM 👍 "Share?" ❌ REJECTED 
    group 🔔 One of: DISCLOSED, SHARED 
    queries -> wallet: 🔔 SHARED: Share @ Notifier 🐌
    queries -> vault: 🔔 DISCLOSED: Disclose @ Vault 🐌
    end group 
deactivate queries


@enduml