@startuml OnBindBound
 
'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "OnDetailed 🔔" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "OnBound 🔔" as handler
end box

participant "Vault 🗄️" as vault

activate script
    script -> binds: SAVE 💾 {BOUND}
deactivate script

activate binds
    binds --> handler: BOUND 🔔
deactivate binds

activate handler
    handler --> vault: SEND 📬 {Bound@}
deactivate handler


@enduml 
