@startuml OnQueryInformed

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnInformed 🔔" as handler
    participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "Token 🪣" as tokens
end box


activate table
    table --> handler: INFORMED 🔔
deactivate table

activate handler
    handler -> wallets: READ 🧲 
    handler -> binds: 
    handler -> tokens: 
    
    alt has matches
        handler -> table: SAVE 💾 {MATCHED}
    else not matched
        handler -> table: SAVE 💾 {UNMATCHED}
    end alt 

deactivate handler

@enduml