@startuml OnTokenRemoved

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as pop
    participant "Tokens 🪣" as tokens
    participant "OnRemoved 🔔" as removed
end box
participant "Notifier 📣" as notifier


wallet --> pop: Pop 🐌

activate pop
    wallet --> pop: {remove}
    pop -> tokens: SAVE 💾 {REMOVED}
deactivate pop

activate tokens
    tokens --> removed: REMOVED 🔔
deactivate tokens

activate removed
    removed --> notifier: SEND 📬 {Remove 🐌}
deactivate removed

@enduml 
