@startuml VerifyToken

participant "Consumer 💼" as consumer
participant "Broker 🤵" as broker
box Identifier 🆔 domain #FFFFFA
    participant "VerifyToken 😃" as script
    participant "Stamps 🪣" as tokens
    participant "Selfie 📸" as identify
end box
participant "Wallet 👱" as wallet


activate consumer
consumer -> broker: Identify@Broker 🐌 \n  {identity, biostamp} 


activate broker
    broker -> script: INVITE 🤲 {biostamp} \n .ID/VERIFY 🧩 
deactivate broker

activate script
    script -> tokens: READ 🧲 {biostamp}
    script --> identify: RUN {user}
deactivate script

activate identify
    identify -> wallet: selfie 📸
    identify -> script: 
deactivate identify


activate script
    script -> broker: 
deactivate script

activate broker
    broker -> consumer: Identified@Consumer 🐌
deactivate broker


    
@enduml