@startuml Collet@Vault

participant "Consumer 💼" as consumer

box Vault 🗄️️ domain #FFFFFA
    participant "Collect 🚀" as vault
    participant "Discloses 🪣" as table
end box


activate consumer
    consumer -> vault: Collect 🚀 
    activate vault
        vault -> table: READ 🧲 
        vault -> consumer: RETURN {data}
    deactivate vault

deactivate consumer

@enduml 