@startuml Goodbye
' ------------------

participant "Consumer 💼" as consumer
participant "Broker 🤵" as broker
box Helper 🤲 domain #FFFFFA
    participant "Help 🐌" as script
    participant "Helps 🪣" as table
end box
participant "Graph 🕸" as graph


activate consumer
    consumer --> broker: Invited 🐌
deactivate consumer

activate broker
    broker --> script: Help 🐌
deactivate broker

activate script
    script -> graph: VERIFY 🔐 {msg}
    script -> graph: TRUSTS 🫡 {msg.from, .BROKER 🧩}
    script -> table: SAVE 💾 {INVITED}
deactivate script

@enduml 