@startuml OnReady

box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as table
    participant "OnReady 🔔" as ready
end box
participant "Consumer 💼" as consumer


activate table
    table --> ready: READY 🔔 
deactivate table

activate ready
    ready --> consumer: SEND 📬 {Consume@ 🐌}
deactivate ready

activate consumer
    consumer -> table: Collect 🚀
deactivate consumer

@enduml 