@startuml State machine

box sender 👥 domain #FFFFFA
    participant "Script 📃" as script
    participant "Dataset 🪣 Key: hook" as table
    participant "Inbox 📥" as inbox
end box

box receiver 👥 domain #FFFFFA
    participant "Handler 🐌" as handler
end box


activate script
    script -> table: SAVE 💾 {hook, STATE-1}
    script --> handler: SEND 📬 {hook}
deactivate script

activate handler
    handler --x inbox: Message 🐌 {hook, result}
activate inbox
    inbox -> table: READ 🧲 {hook} >> item
    inbox -> table: SAVE 💾 item {result, STATE-2}

activate table
    table -> inbox: 
deactivate inbox
    <-- table  : Event 🔔 {STATE-2}
deactivate table

    handler --> inbox: Message 🐌 {hook, result}
deactivate handler

activate inbox
    inbox -> table: READ 🧲 {hook} >> item
    inbox -> table: SAVE 💾 item {result, STATE-2}
activate table
    table -> inbox: No event raised ✅
deactivate table
deactivate inbox


@enduml