@startuml VerifyToken

participant "Consumer 💼" as consumer
box Broker 🤵 #FFFFFA
    participant "Identify 🐌" as broker
    participant "Chatters 🪣" as chatters
end box
participant "Graph 🕸" as graph
participant "Identifier 🆔" as script
participant "Wallet 👱" as wallet


activate consumer
    consumer -> broker: Identify@Broker 🐌 {identity, biostamp} 

activate broker
    broker -> graph: VERIFY 🔐 {msg}
    broker -> chatters: READ 🧲
    broker -> script: INVITE 🤲 .ID/VERIFY 🧩 {biostamp}  
deactivate broker


activate script
    script -> wallet: selfie 📸
    script -> broker: 
deactivate script

activate broker
    broker -> consumer: SEND 📬 { Identified@Consumer 🐌 }
deactivate broker


    
@enduml