@startuml Consumer@Consumer

participant "Vault 🗄️" as vault
box Consumer 💼 domain #FFFFFA
    participant "Consumer 💼" as consumer
    participant "Queries 🪣" as hooks
end box

participant "Graph 🕸" as graph


activate vault
    vault -> consumer: Context 🚀 {schema}

    activate consumer
        consumer -> hooks: READ 🧲 
        consumer -> graph: TRUSTS 🫡 {vault, schema}
        consumer -> vault: {context}
    deactivate consumer

deactivate vault

@enduml 