@startuml Broker.Chats.Open
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as chatters
end box
participant "Printer 🖨️" as printer
participant "Graph 🕸" as graph
participant "Finder 🔎" as finder
participant "Broker 🤵" as broker
participant "Host 🤗" as host

wallet -> chats: 🐌 Locate 💾 INSERTED

activate chats
    
    chats -> printer: Resolve @ Printer 🚀 
    activate printer
        printer -> chats: 💾 RESOLVED
    deactivate printer

    chats -> graph: Translate @ Graph 🚀
    activate graph
        graph -> chats: 💾 DETAILED
    deactivate graph
    
    chats -> wallet: 🐌 Open @ Notifier
deactivate chats

activate wallet
    wallet -> chats: 🐌 Opened 💾 OPENED 
deactivate wallet

activate chats
    chats -> finder: INVITE 🤲
    chats -> broker: INVITE 🤲
deactivate chats

activate broker
    broker -> chats: 💾 ACTIVE
deactivate broker

activate chats
    chats -> chatters: 💾 HOST
deactivate chats    

activate chatters
    chatters -> host: Hello @ Host 🐌 
deactivate chatters

@enduml 
