@startuml Idempotency

box sender 👥 domain #FFFFFA
    participant "Script 📃" as script
end box

box receiver 👥 domain #FFFFFA
    participant "Handler 🐌" as handler
    participant "Dataset 🪣 Key: hook, sender" as table
    participant "OnInserted 🔔" as event
end box


activate script
    script -> script: .UUID >> hook
    script --x handler: SEND 📬 {hook}
    
activate handler
    handler -> table: SAVE 💾 {hook, sender}
activate table
    table -> handler: saved ✅
deactivate handler
    table --> event: Event 🔔 {INSERTED}
deactivate table

    script -> script: retry 
    activate script
        script --> handler: SEND 📬 {hook}
    deactivate script
deactivate script

activate handler
    handler -> table: SAVE 💾 {hook, sender}


activate table
    table -> handler: ignore duplicate key if fields are equal ✅ 
deactivate handler
    table -x handler: raise error on duplicate key if fields differ ❌ 
deactivate table


@enduml