@startuml Freeze
' ------------------

actor "User" as user

participant "Prompt 🤔\n{dog? 🐶}" as dog
participant "Prompt 🤔\n{cat? 🐱}" as cat
participant "Prompt 🤔\n{fish? 🐠}" as fish
participant "Wallet 👱\napp" as wallet

participant "Host 🤗\ndomain" as host

host --> dog: 1) ⏪ Prompt 🤔 {dog? 🐶}
activate dog

host --> cat: 2) ⏪ Prompt 🤔 {cat? 🐱}
activate cat

user --> dog: reply 🐶
dog --> host: 3) late Reply 🐌 
deactivate dog

host --> wallet: 4) Freeze ❄️
activate wallet
deactivate wallet

host --> fish: 5) ⏪ Prompt 🤔 {fish? 🐠}
activate fish
    fish --> host: 6) Reply 🐌 
deactivate fish

user --> cat: reply 🐱
cat -->x cat : 7) blocked ⛔
cat --> host: 8) late Reply 🐌 
deactivate cat

activate host
    host --> host: 9) Ignored
deactivate host

@enduml 