@startuml Onboard@Broker

 
'participant "Wallet 👱" as wallet
participant "Notifier 📣" as wallet

box Broker 🤵️ domain #FFFFFA
    participant "Onboard 🚀" as broker
    participant "Notifiers 🪣" as notifiers
    participant "Wallets 🪣" as wallets
end box

activate wallet
    wallet -> broker: Onboard 🚀

    activate broker
        broker -> notifiers: READ 🧲 
        broker -> wallets: SAVE 💾
        broker -> wallet: {wallet.ID}
    deactivate broker

deactivate wallet


@enduml 
