@startuml Vault.Binds

box Vault 🗄️ domain #FFFFFA
    participant "Script  📃" as script
    participant "BIND ⌘" as cmd
    participant "Binds 🪣" as binds
    participant "Hosted 📦" as hosted
end box
participant "Broker 🤵" as broker


activate script
    script -> cmd: BIND ⌘ {schema}
deactivate script

activate cmd
    cmd -> binds: 💾 {OFFERED}
deactivate cmd

activate binds
    binds -> broker: Bind 🐌
deactivate binds

activate broker
    broker -> binds: IF "yes": 🐌 Bound 💾 {BOUND}
activate binds
    broker -> binds: IF "no": 🐌 Bound 💾 {DECLINED}
deactivate broker

    binds -> hosted: ASYNC 👷🏼 {Bound}
deactivate binds

@enduml 