@startuml Disclose@Broker

participant "Broker 🤵" as broker
box Vault 🗄️️ domain #FFFFFA
    participant "Disclose 🐌" as vault
    participant "Binds 🪣" as binds
    participant "Collects 🪣" as collects
end box


broker --> vault: Disclose 🐌

activate vault    
    vault -> binds: READ 🧲 
    vault -> collects: SAVE 💾 {ASKED}
deactivate vault

@enduml 