@startuml Disclose@Broker

participant "Broker 🤵" as broker
box Vault 🗄️️ domain #FFFFFA
    participant "Disclose 🐌" as vault
    participant "Binds 🪣" as binds
    participant "Discloses 🪣" as discloses
end box
participant "Graph 🕸" as graph


broker --> vault: Disclose 🐌

activate vault    
    vault -> graph: VERIFY 🔐 {msg}
    vault -> graph: TRUSTS 🫡 {msg.from, .BROKER 🧩}
    vault -> binds: READ 🧲 
    vault -> discloses: SAVE 💾 {ASKED}
deactivate vault

@enduml 