@startuml Disclose@Broker

participant "Broker 🤵" as broker
box Vault 🗄️️ domain #FFFFFA
    participant "Script 📃" as vault
    participant "Talker 😃" as talker
    participant "Shares 🪣" as shares
end box


broker --> vault: Disclose 🐌

activate vault    
    vault -> talker: TRUSTS 🫡 {consumer}
    vault -> shares: SAVE 💾 {ASKED}
deactivate vault

@enduml 