@startuml PopTokenTag
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Token 🔆" as token
    participant "Tag 🔆" as tag
    participant "Tokens 🪣" as tokens
end box


wallet -> token: POP 🎈 {Token}

activate token    
    wallet -> token: "tag"
    token -> tag: RUN {token}
deactivate token

activate tag
    tag -> wallet: TEXT 🔠 "tag?"
    tag -> tokens: SAVE 💾 {tag}
    tag -> wallet: DONE ✅ "changed"
    tag -> : GOODBYE 👋
deactivate tag
 
@enduml 
