@startuml OnQueryReceived

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnReceived 🔔" as handler
end box
participant "Graph 🕸" as graph

table --> handler: RECEIVED 🔔 

activate handler
    handler -> graph: VERIFY 🔐 {token signature}
    handler -x table: SAVE 💾 CORRUPTED ❌ 
    handler -> graph: TRUSTS 🫡 {issuer, schema, VAULT}
    handler -x table: SAVE 💾 UNTRUSTED ❌
    handler -> table: SAVE 💾 VALID ✅
    
    
deactivate handler


@enduml 