@startuml OnQueryReceived

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnReceived 🔔" as handler
end box
participant "Graph 🕸" as graph

table --> handler: RECEIVED 🔔 

activate handler
    handler -x table: unexpected schema ❌ 
    handler -> graph: VERIFY 🔐 {token}
    handler -x table: invalid token ❌ 
    handler -x table: issuer not trusted ❌ 
    handler -x table: broker state not active ❌ 
    handler -> table: SAVE 💾 TOKENED ✅
    
    
deactivate handler


@enduml 