@startuml Collet@Vault

participant "Consumer 💼" as consumer

box Vault 🗄️️ domain #FFFFFA
    participant "Collect 🚀" as vault
    participant "Shares 🪣" as shares
end box


activate consumer
    consumer -> vault: Collect 🚀 {hook}
    activate vault
        vault -> shares: READ 🧲 {hook}
        vault -> consumer: RETURN {data}
    deactivate vault

deactivate consumer

@enduml 