@startuml Collet@Vault

participant "Consumer 💼" as consumer

box Vault 🗄️️ domain #FFFFFA
    participant "Collect@ 📃" as vault
    participant "Collects 🪣" as collects
end box


activate consumer
    consumer -> vault: Collect 🚀 {collect}
    activate vault
        vault -> collects: READ 🧲 {collect}
        vault -> consumer: RETURN {data}
    deactivate vault

deactivate consumer

@enduml 