@startuml 👉 Printer NFC-QR check-in
' ------------

actor User as user  

participant "Wallet 👱\napp" as wallet
participant "Broker 🤵\nhost" as broker

participant "Locator 🔆\nNFC/QR" as qr
participant "Printer 🖨️\nsupplier" as printer
participant "Host 🤗\ndomain" as host



group Print locators

    host --> printer: 1) Order 🐌

    activate printer
      printer --> qr: print
    deactivate printer

end group 


user -> wallet: scan ✨

activate wallet
  wallet -> qr: scan ✨
  wallet --> broker: 2) ⏩ Assess 
deactivate wallet


activate broker

    broker -> printer: 3) Resolve 🚀

activate printer
    printer -> broker: {host locator}
deactivate printer
    
    broker --> host: 4) Hello 🐌
deactivate broker


activate host
    host --> wallet: 5) ⏪ Prompt 🤔 {what?}
deactivate host

activate wallet
    user --> wallet: reply
deactivate wallet

' ------------
@enduml