@startuml Wait

participant "User 🧑" as user

box Talker 😃 domain #FFFFFA
    'participant "Host 🤗\nrole API" as host
    participant "Script 📃" as script
    'participant "Engine ⚙️" as engine
    'participant "Inbox 📨" as inbox
end box
participant "Hosted 📦" as hosted

script --> hosted: 👷🏼 ASYNC 🐌 Handle {task, uuid}
activate hosted
activate script
script --> user: ⏳ TEMP {started}

loop 
    script -> script: 🧘 WAIT {uuid}
deactivate script

    hosted --> script: 🐌 Handled 🏁 RACE {uuid, status}

    alt IF status is not DONE
        activate script
            script --> user: ⏳ TEMP {status...}
            script -> script: REPEAT 🔁 
        deactivate script
    end alt
        
end loop

    hosted --> script: 🐌 Handled 🏁 RACE {uuid, done}
deactivate hosted

activate script 
    script --> user: ✅ DONE {done!}
deactivate script

@enduml