@startuml Wait

participant "User 🧑" as user

box Talker 😃 domain #FFFFFA
    'participant "Host 🤗\nrole API" as host
    participant "Script 📃" as script
    participant "Engine ⚙️" as engine
    participant "Inbox 📨" as inbox
end box
participant "Hosted 📦" as hosted

script -> engine: ASYNC 👷🏼
activate script
activate engine
    engine --> hosted:  Handle 🐌 {task, hook}
    activate hosted
    engine -> script: {hook}
deactivate engine

script --> user: ⏪ TEMP ⏳ {started}

script -> engine: WAIT 🧘 {hook}
deactivate script

hosted --> inbox: Handled 🐌 {hook, partial}
activate inbox
    inbox -> script: REEL 🎣 {hook}
deactivate inbox

activate script
    script --> user: ⏪ TEMP ⏳ {running...}
    script -> engine: REPEAT 🔁 
    script -> engine: WAIT 🧘 {hook}
deactivate script
    
    hosted --> inbox: Handled 🐌 {hook, done}
deactivate hosted

activate inbox
    inbox -> engine: REEL 🎣 {hook}
deactivate inbox

activate engine
    engine -> script
deactivate engine

activate script 
    script --> user: ⏪ SUCCESS ✅ {done!}
deactivate script

@enduml