@startuml OnBindOffered
 
box Broker 🤵 domain #FFFFFA
    participant "Binds 🪣" as binds
    participant "OnOffered 🔔" as handler
end box
participant "Graph 🕸" as graph


activate binds
    binds --> handler: OFFERED 🔔
deactivate binds

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler ->  binds: SAVE 💾 {DETAILED}
deactivate handler


@enduml 
