@startuml Clone

actor "User" as user
participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Resourcer 🗃️\nvault" as resourcer

'group Register

    activate resourcer
        resourcer --> wallet: 1) ⏪ Prompt 🤔 {what? ➜ clone} 
        resourcer -> resourcer: stage
        resourcer --> wallet: 2) ⏪ Prompt ⓘ { pin 🄰 }
    deactivate resourcer    

        user --> syncer: 3) $ clone { pin 🄰 }

    activate syncer 
        syncer -> user: show pin 🄱
        syncer -> resourcer: Clone 🚀 { 🄰🄱 }
    deactivate syncer
        
    activate resourcer
        resourcer -> syncer: { cloned }
        resourcer --> wallet: ⏪ Prompt 🤔 { sent pin 🄱? ➜ yes }
        resourcer -> resourcer: activate
        resourcer --> wallet: ⏪ Prompt ✔ { OK, sync now } 
    deactivate resourcer

    user --> syncer: 5) Sync ⏩
    

'end group

@enduml