@startuml
!pragma layout smetana

class "Wallet 🧑\napp" as wallet
class "Syncer 🔃\ntool" as syncer
class "Resourcer 🗃️\nvault" as resourcer

user --> wallet: chat
user --> syncer: sync
wallet --> broker: chat
wallet --> resourcer: reply
broker --> notifier: prompts
notifier --> wallet: prompts
resourcer --> broker: prompts
syncer --> resourcer: sync

@enduml
