@startuml Handle

participant "User 🧑" as user
box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker
end box
participant "Hosted 📦" as hosted

activate script
    script --> user: ⏪ PROMPT 🤔
    script -> talker: EVAL {function} 
deactivate script


activate talker
    talker --> hosted: Handle 🐌 {function, hook}
activate hosted
    talker -> talker: WAIT 🧘 {hook}
deactivate talker
    
    hosted --> talker: Handled 🐌 {hook, result}
deactivate hosted

activate talker
    talker --> script: REEL 🎣 {hook}
deactivate talker

activate script
    script --> user: ⏪ PROMPT 🤔
deactivate script

@enduml