@startuml Bound@Vault

participant "Broker 🤵" as broker
box Vault 🗄️ domain #FFFFFA
    participant "Bound 🐌" as vault
    participant "Binds 🪣" as binds
end box
participant "Graph 🕸" as graph


activate broker
    broker --> vault: Bound 🐌 {bind, answer}
deactivate broker

activate vault
    
    vault -> graph: VERIFY 🔐 {msg}
    vault -> graph: TRUSTS 🫡 {msg.from, .BROKER 🧩}
    vault -> binds: READ 🧲 {bind, broker}

    alt answer is ACCEPTED
        vault -> binds: SAVE 💾 {BOUND}
    else answer is DECLINED
        vault -> binds: SAVE 💾 {DECLINED}
    end

deactivate vault


@enduml 