@startuml OnTokenDetailed


box Broker 🤵 domain #FFFFFA
    participant "OnIssued 🔔" as script
    participant "Tokens 🪣" as table
    participant "OnDetailed 🔔" as handler
end box
participant "Wallet 👱" as wallet


activate script
    script -> table: SAVE 💾 {DETAILED}
deactivate script

activate table
    table --> handler: DETAILED 🔔
deactivate table

activate handler
    handler -> wallet: CONFIRM 👍 {accept?} 
    handler -> table: SAVE 💾 {OFFERED}
deactivate handler

@enduml 
