@startuml Tokens@Broker

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Remove 📃" as remove
    participant "Tokens 🪣" as tokens
    participant "OnPurge 📃" as purge
end box

participant "Notifier 📣" as notifier

wallet --> remove: Pop 🐌

activate remove
    remove -> tokens: DELETE {undo}
deactivate remove

activate tokens
    tokens --> tokens: wait...
    tokens --> purge: PURGE 
deactivate tokens

activate purge
    purge --> notifier: Remove 🐌 {token}
deactivate purge

@enduml 
