@startuml Receive@Consumer

participant "Wallet 🧑" as wallet
box Consumer 💼 domain #FFFFFA
    participant "Receive 🐌" as consumer
    participant "Talker 😃" as talker
    participant "Queries 🪣" as queries
    participant "Chats 🪣" as chats
end box

activate wallet
    wallet --> consumer: Receive 🐌 {hook}
deactivate wallet

@enduml 