@startuml Grab@Printer

'participant "Broker 🤵" as broker
'participant "Graph 🕸" as graph

participant "Domain 👥" as domain

box Hoster ☁️ domain #FFFFFA
    participant "Printer 🖨️" as printer
    'participant "Talker 😃" as talker
end box

box Itemizer 🛢 domain #FFFFFA
    participant "Aliases 🪣" as aliases
end box

activate domain
domain -> printer: Grab 🚀 {alias, locator}
activate printer
    printer -> aliases: SAVE 💾 {alias, locator}
    
    activate aliases
        aliases -> printer: {status}
    deactivate aliases

    alt success
        printer -> domain: RETURN {OK}
    else failure
        printer -> domain: RETURN {BLOCKED, UNHOST}
    end
    
deactivate printer
deactivate domain

@enduml 