@startuml OnPromptInserted
 
box Host 🤗 domain #FFFFFD
    participant "Prompts 🪣" as prompts
    participant "OnInserted 🔔" as handler
end box
participant "Talker 😃" as talker

prompts --> handler: INSERTED 🔔
activate handler

    group IF Language.Differs(Chat.Language)
        handler -> talker: TRANSLATE 🈯
    end group

    handler -> prompts: SAVE 💾 {TRANSLATED}
deactivate handler


@enduml 
