@startuml OnPromptTranslated
 
box Host 🤗 domain #FFFFFD
    participant "Prompts 🪣" as prompts
    participant "OnTranslated 🔔" as handler
end box

prompts --> handler: TRANSLATED 🔔
activate handler
    handler -> handler: ASSERT
    handler -> prompts: SAVE 💾 {ASSERTED}
deactivate handler


@enduml 
