@startuml OnInviteHelped

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnHelped 🔔" as handler
end box
participant "Graph 🕸" as graph

table --> handler: HELPED 🔔 

activate handler
    handler -> graph: VERIFY 🔐 {help, schema}
    handler -> table: SAVE 💾 {VERIFIED}
deactivate handler

@enduml 