@startuml OnChatBinds

box Host 🤗 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "OnBinds 🔔" as script
    participant "Binds 🪣" as binds
end box


chats --> script: BINDS 🔔

activate script
    script -> script: PARALLEL {Chat.Binds}
    
    activate script
        script -> binds: READ 🧲
        script -> script: SET {bind details}
    deactivate script   

    script -> chats: 💾 TOKENS

deactivate script   


@enduml 
