@startuml Handle

box Business #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker

    participant "Hosted 📦" as hosted
end box

activate script
    script --> talker: EVAL {X into $A}
    script --> talker: EVAL {function} 
deactivate script


activate talker
    talker --> hosted: Handle 🐌 {function, hook}
activate hosted
    talker -> talker: WAIT 🧘 {hook}
deactivate talker
          
    hosted -> talker: Placed 🚀 {$A}

    activate talker
        talker -> hosted: {X}
    deactivate talker

    hosted -> talker: Place 🚀 {Y into $B}

    hosted --> talker: Handled 🐌 {hook}
deactivate hosted

activate talker
    talker --> script: REEL 🎣 {hook}
deactivate talker

activate script
    script -> talker: EVAL {$B}
activate talker
    talker -> script: {Y}
deactivate talker
deactivate script


@enduml