@startuml PopTokenRemove
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Token 🔆" as token
    participant "Remove 🔆" as remove
    participant "Tokens 🪣" as tokens
end box


wallet -> token: POP 🎈 {Token}

activate token    
    wallet -> token: "remove"
    token -> remove: RUN {token}
deactivate token

activate remove
    remove -> wallet: CONFIRM 👍 "remove?"
    remove -> tokens: SAVE 💾 {REMOVED}
    remove -> wallet: DONE ✅ "removed"
    remove -> : GOODBYE 👋
deactivate remove
 
@enduml 
