@startuml 👉 Printer NFC-QR check-in
' ------------

participant "Wallet 👱" as wallet  
'participant "Notifier 📣\nbff" as notifier
'participant "Finder 🔎\nvault" as finder
'participant "Printer 🖨️\nsupplier" as printer


box "Broker 🤵" #FFFFFA
    participant "Handler 📃" as broker
    participant "Wallets 🪣" as wallets
    participant "Chats 🪣" as chats
end box



activate wallet
  wallet --> broker: Locate 🐌 {hook, locator}
deactivate wallet


activate broker

    broker -> wallets: READ 🧲 {from}
    broker -> wallets: VERIFY 🔐 {msg}
    broker -> chats: SAVE 💾 

deactivate broker


@enduml