@startuml ONE
 
box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "ONE ⌘" as many
    participant "PROMPT ⌘" as prompt
    'participant "Host 🤗" as host
    'participant "Consumer 💼" as consumer
end box

'participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> many: ONE ⌘ {text, options}
deactivate script

activate many
    many -> prompt: RUN 🏃 {text, options}
deactivate many

activate prompt
    prompt --> wallet: Prompt@Broker 🐌 {text, options}
deactivate prompt

activate wallet
    wallet --> prompt: {selection}
deactivate wallet

activate prompt
    prompt -> many: RETURN {selection}
deactivate prompt

activate many
    many -> script: RETURN {selection}
deactivate many

activate script
deactivate script

@enduml 
