@startuml 👉 Printer NFC-QR check-in
' ------------

'participant "Notifier 📣\nbff" as notifier
'participant "Printer 🖨️\nsupplier" as printer

box "Broker 🤵" #FFFFFA
    participant "Locate@ 📃" as assess
    participant "Call-Converse 📃" as script
    participant "Update-Chats 📃" as script2
'    participant "Chats" as chats
'    participant "Chatters" as chatters
end box

participant "Notifier 📣" as notifier
participant "Wallet 👱" as wallet  


'participant "Finder 🔎" as finder


activate assess
    assess -> script: {$chat}
deactivate assess

activate script
    script --> notifier: SEND Converse {$chat}

    activate notifier
        notifier --> wallet: 
    deactivate notifier

    script -> script2: RUN {$chat.wallet}
    script -> assess: 
deactivate script

activate assess
deactivate assess

@enduml