@startuml Emojied@Host
 
participant "Broker 🤵" as broker
box Host 🤗 domain #FFFFFD
    participant "Emojied 🐌" as handler
    participant "Talker 😃" as talker
end box

broker --> handler: Emojied 🐌 {hook}

activate handler
    handler -> talker: REEL 🎣 {hook}
deactivate handler


@enduml 
