@startuml OnQueryTrusted

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnTrusted 🔔" as handler
    participant "Schemas 🪣" as schemas
end box
participant "Wallet 👱" as wallet


activate table
    table --> handler: TRUSTED 🔔
deactivate table

activate handler

    group If many
        handler -> wallet: ONE "Which one?" 
    end group

    handler -> schemas: READ 🧲
    handler -> wallet: CONFIRM 👍 "share?"

    alt IF Bind
        handler -> table: SAVE 💾 {DISCLOSED} 
    else IF Token
        handler -> table: SAVE 💾 {SHARED}
    end

deactivate handler

@enduml