@startuml OnPopInserted
 
box Broker 🤵 domain #FFFFFA
    participant "Pops 🪣" as pops
    participant "OnInserted 🔔" as popped
    participant "Chats 🪣" as chats
end box

activate pops
    pops --> popped: INSERTED 🔔
deactivate pops

activate popped
    popped -> chats: SAVE 💾 {hook}
deactivate popped




@enduml 
