@startuml Place@Talker

participant "Hosted 📦" as hosted

box Talker 😃 domain #FFFFFA
    participant "API 📨" as talker
    participant "Chats 🪣" as chats
    participant "Holders 🪣" as holders
end box


activate hosted
    hosted -> talker: Place 🚀 {A into $p}

    activate talker
        talker -> chats: GET {chat}
        talker -> holders: SAVE 💾 {chat, A into $p}
        talker -> hosted: 
    deactivate talker

deactivate hosted

@enduml