@startuml Place@Talker

participant "Hosted 📦" as hosted

box Talker 😃 domain #FFFFFA
    participant "Inbox 📨" as inbox
    participant "Chats 🪣" as chats
    participant "Holders 🪣" as holders
end box


activate hosted
    hosted -> inbox: Place 🚀 {A into $p}

    activate inbox
        inbox -> chats: GET {chat}
        inbox -> holders: SAVE 💾 {chat, A into $p}
        inbox -> hosted: 
    deactivate inbox

deactivate hosted

@enduml