@startuml Broker.Tokens.Updates
 
participant "Issuer 🎴" as issuer
box Broker 🤵 domain #FFFFFA
    participant "Revise 🐌" as revise
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
    participant "Pops 🪣" as pops
end box
participant "Wallet 👱" as wallet
    

issuer -> revise: Revise 🐌
activate revise
    revise -> tokens: 💾 {status}
deactivate revise

activate tokens

'group update the Frontend

    tokens -> frontend: 💾 {tokens}    
    activate frontend
        frontend -> wallet: 🐌 Updated 
    deactivate frontend

'end group

'group Pop-up the info

    tokens -> pops: 💾 TOKEN.REVISED
deactivate tokens

activate pops
    pops -> wallet: Open 🐌 
    pops -> wallet: INFO ⓘ {status}
deactivate pops

'end group

@enduml 
