@startuml OnQueryQueried

box Broker 🤵 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnQueried 🔔" as handler
    participant "Chats 🪣" as chats
    participant "Forms 🪣" as forms
end box


activate table
    table --> handler: QUERIED 🔔
deactivate table

activate handler
    handler -> chats: READ 🧲
    handler -> forms: 

    alt Is schema informed?
        handler -> table: SAVE 💾 {INFORMED}
    else not informed
        handler -> table: SAVE 💾 {ABRUPT}
    end 
deactivate handler

@enduml