@startuml OnTokenOffered

box Broker 🤵 domain #FFFFFA
    participant "Tokens 🪣" as tokens
    participant "OnOffered 🔔" as offered
end box
participant "Notifier 📣" as notifier
''participant "Wallet 👱" as wallet

activate tokens
    tokens --> offered: OFFERED 🔔
deactivate tokens

activate offered
    group IF accepted
        offered --> notifier: SEND 📬 {Save@ 🐌 token}
    end group
    group IF declined
        offered -> tokens: SAVE 💾 {DECLINED}
deactivate offered
    end group
    

@enduml 