@startuml OnBindDetailed
 
'participant "Wallet 👱" as wallet
participant "Vault 🗄️" as vault

box Broker 🤵 domain #FFFFFA
    participant "Bind@ 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "OnCreated 🔔" as handler
end box

participant "Wallet 👱" as wallet


activate vault
    vault --> script: Bind 🐌
deactivate vault

activate script
    script -> binds: SAVE 💾 {CREATED}
deactivate script

activate binds
    binds --> handler: CREATED 🔔
deactivate binds

activate handler
    handler -> wallet: CONFIRM 👍
deactivate handler

activate wallet
    wallet --> handler: 
deactivate wallet

activate handler
    handler ->  binds: ️SAVE 💾 {KEPT}
deactivate handler


@enduml 
