@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant ".ASYNC 📃" as async
    participant "Holders 🪣" as holders
    participant "Inbox 📨" as inbox
end box

participant "Hosted 📦" as hosted


activate script
    script -> async: ASYNC {function} 
deactivate script

activate async
    async -> async: hook: {.UUID}
    async --> hosted: SEND {Handle 🐌 function, hook}
    activate hosted
    async -> async: WAIT 🧘 {hook}
deactivate async
          
    hosted --> inbox: Handled 🐌 {hook, 3}
deactivate hosted

activate inbox
    inbox -> async: REEL 🎣 {hook, 3}
deactivate inbox

activate async
    async -> script: RETURN {3}
deactivate async

activate script


@enduml