@startuml Pop@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Pop@ 📃" as pop
    participant "Pops 🪣" as pops
    participant "OnPopped@ 🔔" as popped
    participant "Opened@ 📃" as opened
end box


wallet --> pop: Pop 🐌 

activate pop
    pop -> pops: SAVE 💾
deactivate pop

activate pops
    pops --> popped: POPPED 🔔
deactivate pops

activate popped
    popped --> wallet: SEND 📬 Open 🐌 {pop}
deactivate popped

activate wallet
    wallet --> opened: Opened 🐌 
deactivate wallet

activate opened
    opened -> pops: SAVE 💾 {OPENED}
deactivate opened

@enduml 
