@startuml Broker.Chatters 

participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as table
end box
participant "Finder 🔎" as finder
participant "Host 🤗" as host

wallet -> chats: 🐌 Opened @ Broker

activate chats
    chats -> table: 💾 FINDER
deactivate chats

activate table
    table -> finder: 🐌 Present @ Finder
deactivate table

activate finder
    finder -> chats : 🐌 Presented @ Broker 💾 PRESENTED 
deactivate finder

activate chats
    chats -> table:  💾 BROKER
deactivate chats

activate table
    table -> wallet: INFO ⓘ 
    table -> chats: 💾 ACTIVE
deactivate table

activate chats
    chats -> table: 💾 HOST
deactivate chats

activate table
    table -> host: 🐌 Hello @ Host 
deactivate table

@enduml