@startuml Wallet: Share Token


participant "Consumer 💼" as consumer
'participant "Broker 🤵" as broker
participant "Graph 🕸" as graph
participant "Identifier 🆔" as identity
participant "Wallet 👱" as user

' --------------------
' QUERY
' --------------------

activate consumer
consumer -> user : 1) ⏩ Share Token 🎫

consumer -> graph: 2) Trusts 🚀 {identity}
consumer -> identity: 3 ⏩ Invite 

deactivate consumer
activate identity



identity -> user: 4 ⏩ Take Selfie 📸

identity -> consumer: 5 ⏪ Consume 🧩

deactivate identity


@enduml 