@startuml 🤲 Helper.Helps

box "Helper 🤲" #FFFFFA
    participant "Helps 🪣" as table
    participant "OnInvited 🔔" as event
    'participant "Help 🐌" as handler
    'participant "Schemas 🪣" as schemas
    'participant "Script 📃" as script
end box
'participant "Graph 🕸" as graph
'participant "Biller 🤝" as biller
'participant "Consumer 💼 " as consumer
participant "Biller 🤝" as biller


table --> event: INVITED 🔔
activate event
    event -> biller: SEND 📬 {Authorize 🚀}
    event -> table: 
deactivate event

@enduml 