@startuml Introduce@Broker

 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Chats@ 📃" as broker
    participant "Wallets 🪣" as wallets
    participant "Chats 🪣" as chats
end box

activate wallet
wallet -> broker: Chats 🚀 {wallet}

    activate broker
        broker -> wallets: READ 🧲
        broker -> chats: 
        
        broker -> wallet: RETURN {$wallet.Chats}
    deactivate broker

deactivate wallet

@enduml 
