@startuml OnDiscloseAsked

box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as table
    participant "OnAsked 🔔" as handler
end box
participant "Graph 🕸" as graph


activate table
    table --> handler: ASKED 🔔 
deactivate table

activate handler
    handler -> graph: TRUSTS 🫡 {consumer}
    
    alt trusted?
        handler -> table: TRUSTED ✅
    else
        handler -> table: UNTRUSTED ❌
    end alt
deactivate handler

@enduml 