@startuml OnOfferOffered


box Vault 🗄️ domain #FFFFFA
    participant "BIND ⌘" as script
    participant "Offer 🪣" as offers
    participant "OnOffered 🔔" as trigger
    'participant "Talker 😃" as talker
end box

participant "Broker 🤵" as broker


activate script
    script -> offers: SAVE 💾 {OFFERED}
deactivate script

activate offers
    offers --> trigger: OFFERED 🔔
deactivate offers

activate trigger
    trigger --> broker: SEND 📬 {Bindable 🐌} 
deactivate trigger


@enduml 