@startuml Invite@Broker

participant "Consumer 💼 " as host
box "Broker 🤵" #FFFFFA
    participant "Invite 🐌" as broker
    participant "Chats 🪣" as chats
    participant "Invites 🪣" as invites
end box
participant "Graph 🕸" as graph


activate host
    host --> broker: Invite 🐌
deactivate host

activate broker
    broker -> graph: VERIFY 🔐 {msg}
    broker -> chats: READ 🧲 
    broker -> invites: SAVE 💾 {HELPER} 
deactivate broker

@enduml 