@startuml All
' ----------------------

box Sender Domain #FFFFFF
    participant "Sender\nLogic 🧠" as dom1
    participant "Sender\nEvents 🐌" as bus1
    participant "Sender\nOutbox 🚀" as srv1
    participant "Sender\nDNS 🌐" as dns1
end box

box Receiver Domain #FFFFFF
    participant "Receiver\nDNS 🌐" as dns2
    participant "Receiver\nInbox 📨" as api2
    participant "Receiver\nEvents 🐌" as bus2
    participant "Receiver\nLogic 🧠" as dom2
end box


activate dom1
    dom1 -> dom1: new ID
    dom1 --> bus1: {msg}
deactivate dom1

activate bus1
    bus1 --> srv1: {msg}
deactivate bus1

activate srv1
    srv1 -> srv1: sign
    srv1 -> api2: {msg}

    activate api2
        
        api2 -> dns1: public key?
        activate dns1
            dns1 -> api2: {public key}
        deactivate dns1

        api2 x--> srv1: HTTP 401 if invalid signature
        api2 x--> srv1: HTTP 422 if invalid schema
        api2 x--> srv1: HTTP 200 if duplicate ID
        api2 --> bus2: {msg}
        activate bus2
            api2 -> api2: store ID
            api2 -> srv1: HTTP 200
    deactivate api2
    deactivate srv1
    bus2 --> dom2: {msg}

deactivate bus2


' ----------------------
@enduml