@startuml Chat

actor "User" as user
participant "Wallet 🧑\napp" as wallet
participant "Syncer 🔃\ntool" as syncer
participant "Resourcer 🗃️\nvault" as resourcer
participant "Broker 🤵\ndomain" as broker

'group Register

    user --> syncer: 1) chat {key}

    activate syncer
        syncer --> resourcer: 2) Chat 🐌
    deactivate syncer

    activate resourcer
        resourcer --> broker: 3) Engage ⏩
    deactivate resourcer

    activate broker
        broker --> resourcer:
    deactivate broker

    activate resourcer
        resourcer --> wallet: 4) ⏪ Prompt {what?} 
    deactivate resourcer

@enduml