@startuml OnBindAltered

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Script 📃" as script
    participant "Binds 🪣" as binds
    participant "OnAltered 🔔" as handler
    participant "Wallets 🪣" as wallets
    participant "Frontend 🪣" as frontend
end box

'participant "Notifier 📣" as notifier
'wallet --> script: Pop 🐌

activate script
    script -> binds: SAVE 💾, DELETE 🗑️

activate binds
    binds --> handler: ALTERED 🔔
deactivate binds

activate handler
    handler -> wallets: READ 🧲
    handler -> frontend: READ 🧲 {Wallet: $wallet.ID}
    handler -> frontend: SAVE 💾 {$wallet.Binds}
deactivate handler

@enduml 
