@startuml Issuer.Tokens.Issued
 
box Issuer 🎴 domain #FFFFFA
    participant "Script  📃" as script
    participant "Talker 😃" as talker
    participant "Tokens 🪣" as tokens
end box
participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> talker: ISSUE 🎫
deactivate script

activate talker
    talker -> tokens: 💾 ISSUED
deactivate talker


activate tokens
    tokens -> broker: Issue 🐌  
deactivate tokens

activate broker
    broker -> tokens: 🐌 💾 OFFERED, declined

    activate tokens
        tokens -> script: RETURN false
    deactivate tokens

    broker -> wallet: IF accepted: Save 🐌 
deactivate broker

activate wallet
    wallet -> tokens: Issued 🚀
    wallet -> broker: Saved 🐌
deactivate wallet

activate broker
    broker -> tokens: 🐌 💾 OFFERED, accepted
deactivate broker

activate tokens
    tokens -> script: RETURN true
deactivate tokens

@enduml 
