@startuml OnChatLocated

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "OnCreated 🔔" as script
    participant "Chats 🪣" as table
    participant "OnDetailed 🔔" as handler
end box

participant "Notifier 📣" as notifier

'wallet --> script: Pop 🐌


activate script
    script -> table: SAVE 💾 {DETAILED}
deactivate script

activate table
    table --> handler: DETAILED 🔔
deactivate table

activate handler
    handler --> notifier: SEND 📬 {Open 🐌}
deactivate handler

@enduml 
