@startuml Bind()

 
' ---------------------
''actor User as user
''participant "Notifier 📣" as notifier
''participant "Graph 🕸" as graph
participant "Vault 🗄️" as vault
participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet



activate vault
    vault -> wallet: 1) Prompt ⏩ "Hi! What do you need?"
    vault --> broker: 2) Bindable 🐌 {offered schemas}
deactivate vault    

activate broker
    broker -> wallet: 3) Prompt ⏩ "Bind?"
    broker --> vault: 4) Bound 🐌 {selected schemas} 
deactivate broker

activate vault
    vault --> wallet: 5) Prompt ⏩ "Bound!"
deactivate vault

' ---------------------
@enduml 
