@startuml Accept()


' ----------------------
actor "User\nin chat" as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Issuer 🎴\ndomain" as issuer

' ISSUE
activate issuer
    issuer --> broker: 1) offer@
deactivate issuer

' REGISTER
activate broker
    broker --> wallet: 2) ⏪ prompt 
deactivate broker

activate wallet
    user --> wallet: save
    wallet --> broker: {Yes}
deactivate wallet

activate broker
    broker --> notifier: 3) offer@
deactivate broker

' NOTIFY
activate notifier
    notifier --> wallet
deactivate notifier

' ACCEPT
activate wallet
    ' DOWNLOAD
    wallet -> issuer: 4) token@
    activate issuer
        issuer -> wallet: {token}
    deactivate issuer
    wallet -> wallet: persist

    ' CONFIRM
    wallet --> broker: 5) accepted@ { path }
deactivate wallet

' NOTIFY
activate broker
    broker --> wallet: 6) ⏪ update tokens 
    broker --> issuer: 7) accepted@
deactivate broker

activate issuer
    issuer --> wallet: 8) ⏪ prompt 
deactivate issuer


' ----------------------
@enduml