
@startuml Bind()

 
' ---------------------
actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Vault 🗄️\nhost" as vault
participant "Graph 🕸\ndomain" as graph


activate broker
   
    ' Translate.
    broker -> graph: 1) Translate 🚀
    activate graph
        graph -> broker: {translations}
    deactivate

    ' Inform the user about the bind.
    broker --> wallet: 2) ⏪ Prompt 🤔
    
    ' Bind with the vault.
    broker --> vault: 3) Bound 🐌

    broker --> wallet: 4) ⏪ Update Binds 🔗
    
deactivate broker


' ---------------------
@enduml 