@startuml ISSUE


box Talker 😃️ domain #FFFFFA
    participant "Script 📃" as script
    participant ".ISSUE 📃" as talker
    'participant "Consumer 💼" as consumer
    participant "Issuer 🎴" as issuer
end box

box Itemizer 🛢  #FFFFFA
    participant "Hooks" as hooks
end box

participant "Broker 🤵" as broker
'participant "Vault 🗄️" as vault
participant "Wallet 👱" as wallet

activate script
    script -> talker: ISSUE 🎫
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {hook}
    talker --> broker: SEND 📬 {Offer 🐌 hook}
activate broker
    talker -> talker: WAIT {hook}
deactivate talker

    broker --> wallet: Save 🐌
deactivate broker

activate wallet
    wallet -> issuer: Issued 🚀 {hook}

    activate issuer
        issuer -> hooks: GET 🧲 {hook}
        issuer -> wallet: {offer}
    deactivate issuer

    wallet --> broker: Saved 🐌
deactivate wallet

activate broker
    broker --> issuer: Accepted 🐌 {hook, token}
deactivate broker

activate issuer
    issuer -> talker: REEL 🎣 {hook, token}
deactivate issuer

activate talker
    talker -> script: RETURN {token}
deactivate talker

activate script
deactivate script

@enduml 
