@startuml 👉 Printer NFC-QR check-in
' ------------

'participant "Wallet 👱\napp" as wallet  
'participant "Notifier 📣\nbff" as notifier
'participant "Finder 🔎\nvault" as finder

box "Broker 🤵" #FFFFFA
    participant "Locate@ 📃" as assess
    participant "Resolve-Alias 📃" as script
    participant "Engine ⚙️" as engine
    'participant "Handler 📃" as broker
    'participant "Chats" as chats
    'participant "Chatters" as chatters
end box

participant "Printer 🖨️" as printer



activate assess
    assess -> script: {locator}
deactivate assess

activate script
    script -> engine: PARSE {locator}

    group locator.IsAlias 

        script -> printer: SEND 🚀 Resolve 

        activate printer
            printer -> script: {host locator}
        deactivate printer

        script -> engine: PARSE {locator}

    end group

    script -> assess: RETURN {$locator}
deactivate script

activate assess
deactivate assess

@enduml