@startuml SignFile

participant "Consumer 💼" as consumer
box Identifier 🆔 domain #FFFFFA
    participant "SignFile  😃" as script
    participant "Selfie 📸" as identify
    participant "Hosted 📦" as hosted
end box
participant "Wallet 👱" as wallet


consumer --> script: Query@Broker 🐌 {SIGN-FILE, raw-file}

activate script
    script -> wallet: CONFIRM 👍 "sign?" {raw-file}
    script --> identify: RUN {user}
deactivate script

activate identify
    identify -> wallet: selfie 📸
    identify -> script: 
deactivate identify

activate script
    script -> hosted: CALL 🧮 {Sign, raw-file}
deactivate script

activate hosted
    hosted -> script: {signed-file}
deactivate hosted

activate script
    script --> consumer: Consume@Consumer 🐌 {signed}
deactivate script

    
@enduml