@startuml Introduce

actor "User\nin chat" as user
participant "Broker 🤵\nhost" as broker
participant "Finder 🔎\nvault" as finder
participant "Reviewer ⭐\nvault" as reviewer
participant "Graph 🕸\ndomain" as graph
'participant "Host 🤗\ndomain" as host


activate broker

    broker --> finder: 1) Introduce 🐌
    deactivate broker

    activate finder

      finder -> reviewer: 2) Reviews 🚀
      activate reviewer
        reviewer -> finder: {reviews}
      deactivate reviewer

      finder -> graph: 3) Identity 🚀
      activate graph
        graph -> finder: {identity}
      deactivate graph


      finder -> graph: 4) Translate 🚀
      activate graph
        graph -> finder: {translation}
      deactivate graph

      finder --> user: 5 ⏪ Prompt 🤔

      finder --> broker: 6) Introduced 🐌
      
    deactivate finder
    activate broker




  
' ------------
@enduml