@startuml Broker.Tokens.Updates
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Tokens 🪣" as tokens
    participant "Frontend 🪣" as frontend
end box
participant "Issuer 🎴" as issuer
    
wallet -> tokens: 🐌 Pop » Token » Remove » Undo
activate tokens
    tokens -> wallet: 🐌 Save
deactivate tokens

activate wallet
    wallet -> tokens: 🐌 Saved 💾 {SAVED}
deactivate wallet

activate tokens
    tokens -> issuer: Offered 🐌 {accepted}
    tokens -> frontend: 💾 {tokens}
deactivate tokens

activate frontend
    frontend -> wallet: 🐌 Updated 
deactivate frontend

@enduml 
