@startuml 👉 Printer NFC-QR check-in
' ------------

'participant "Wallet 👱\napp" as wallet  
'participant "Notifier 📣\nbff" as notifier
'participant "Finder 🔎\nvault" as finder
'participant "Printer 🖨️\nsupplier" as printer


box "Broker 🤵" #FFFFFA
    participant "Assess@ 📃" as assess
    participant "Save-Host 📃" as script
    'participant "Engine ⚙️" as engine
    participant "Domains 🪣" as domains
    'participant "Chats 🪣" as chats
    'participant "Chatters 🪣" as chatters
end box

participant "Graph 🕸" as graph


activate assess
    assess -> script: 
deactivate assess

activate script
    script -> graph: SEND 🚀 Identity {host}
    script -> domains: SAVE {host}
    script -> assess: 
deactivate script

activate assess
deactivate assess


@enduml