@startuml OnTokenRejected

participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Saved@ 📃" as script
    participant "Tokens 🪣" as tokens
    participant "OnSaved 🔔" as change
end box

'participant "Notifier 📣" as notifier
participant "Issuer 🎴" as issuer

wallet --> script: ? 🐌

activate script
    script -> tokens: SAVE 💾 {REJECTED}
deactivate script

activate tokens
    tokens --> change: REJECTED 🔔
deactivate tokens

activate change
    change --> issuer: SEND 📬 {Rejected 🐌}
deactivate change

@enduml 