@startuml Handle

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant ".EVAL 📃" as talker
    participant "Memory 🧠" as memory
    participant "Holders 🪣" as holders
    participant "Inbox 📨" as inbox
end box

participant "Hosted 📦" as hosted


activate script
    script -> talker: EVAL ⬇️ {1 into $A} 
deactivate script

activate talker
    talker -> memory: GET 🧲 {A}
    talker -> script: 
deactivate talker

activate script 
    script -> talker: EVAL ⬇️ {function} 
deactivate script

activate talker
    talker -> talker: hook: {.UUID}
    talker --> hosted: Handle 🐌 {function, hook}
activate hosted
    talker -> holders: WAIT 🧘 {hook}
deactivate talker
          
    hosted -> inbox: Placed 🚀 {$A}

    activate inbox
        inbox -> holders: GET 🧲 {A}
        inbox -> hosted: {1}
    deactivate inbox

    hosted -> inbox: Place 🚀 {2 into $B}
    activate inbox
        inbox -> holders: SAVE 💾 {B:2}
        inbox -> hosted:
    deactivate inbox

    hosted --> inbox: Handled 🐌 {hook, 3}
deactivate hosted

activate inbox
    inbox -> talker: REEL 🎣 {hook, 3}
deactivate inbox

activate talker
    talker -> holders: GET 🧲 {A,B}
    talker -> memory: SAVE 💾 {A:1,B:2}
    talker -> script: RETURN {3}
deactivate talker

activate script
    script -> talker: EVAL ⬇️ {$B}
deactivate script

activate talker
    talker -> memory: GET 🧲 {B}
    talker -> script: {2}
deactivate talker

activate script


@enduml