@startuml Handle

participant "User 🧑" as user
box Hoster ☁️ domain #FFFFFA
    participant "Host 🤗" as host
    participant "Talker 😃" as talker
    participant "Script 📃" as script
end box

activate script
    script --> talker: ONE 1️⃣
deactivate script

activate talker
    talker --> user: ⏪ Prompt 🤔 {hook}
activate user
    talker -> talker: WAIT ⏸️ {hook}
deactivate talker

    user --> host: Reply 🐌 {hook}
deactivate user
    
activate host
    host --> talker:
deactivate host

activate talker
    talker --> script: REEL 🎣 {hook}
deactivate talker

activate script
deactivate script

@enduml