@startuml Handle


box Hoster ☁️ domain #FFFFFA
    participant "Script 📃" as script
    participant "Talker 😃" as talker
    participant "Prompts🪣" as hooks
    participant "Host 🤗" as host
end box
participant "User 🧑" as user

activate script
    script --> talker: ONE 1️⃣
deactivate script

activate talker
    talker -> hooks: SAVE 💾 {prompt}

    'activate hooks
    'deactivate hooks

    talker --> user: ⏪ Prompt 🤔 {prompt}
activate user
    talker -> talker: WAIT ⏸️ {prompt}
deactivate talker

    user -> host: Prompted 🚀 {prompt}
    activate host
        host -> hooks: GET ⏬ {prompt}
        host -> user: 
    deactivate host

    user --> host: Reply 🐌 {prompt}
deactivate user
    
activate host
    host --> talker:
deactivate host

activate talker
    talker --> script: REEL 🎣 {prompt}
deactivate talker

activate script
deactivate script

@enduml