@startuml Sub: Register Subscriber()
' ----------------
participant "Subscriber\nService" as graph
participant "Subscriber\nWebhook" as hook
participant "Publisher\nAPI" as listener

' ----------------
' REGISTER
' ----------------
graph --> listener: register(webhook)
activate graph
deactivate graph
activate listener

' ----------------
' CHECK HEALTH
' ----------------
listener --> hook: confirm(request)
deactivate listener
activate hook
hook --> graph: confirm(request)
deactivate hook
activate graph

' ----------------
' REPLY
' ----------------
graph --> listener: {confirmed}
deactivate listener
deactivate graph

' ----------------
@enduml