@startuml OnDomainInserted

box Broker 🤵 domain #FFFFFA
    participant "Itemizer 🛢" as itemizer
    participant "Schemas 🪣" as table
    participant "OnInserted 🔔" as handler
end box
participant "Graph 🕸" as graph


itemizer --> table: propagate 💾

activate table
    table --> handler: INSERTED 🔔
deactivate table

activate handler
    handler -> graph: GRAPH 🕸 Schema
    handler -> table: SAVE 💾 
deactivate handler

@enduml 
