@startuml Bind Biller

participant "Folder 🗂️\ndomain" as folder
participant "Collector 🏦\ndomain" as collector
actor "User\nin chat" as user
'participant "Broker 🤵\ndomain" as broker
participant "Biller 🤝\ndomain" as biller

biller --> user: 1) ⏪ Prompt 🤔 {what? ➜ bind}

activate biller
    biller --> user: 2) ⏪ Bind {profile}
    biller --> collector: 3) ⏪ ShareBind {collector}
    biller --> folder: 4) ⏪ ShareBind {folder}
    biller --> user: 5) ⏪ ShareToken+ID {admin}
deactivate biller
    
' ------------
@enduml