@startuml Download@Host
 
participant "Wallet 👱" as wallet
box Host 🤗 domain #FFFFFD
    participant "Download 🚀" as handler
    participant "Appendixes 🪣" as appendixes
    participant "Chats 🪣" as chats
end box

wallet -> handler: Download 🚀 
activate wallet

    activate handler
        handler -> appendixes: READ 🧲
        handler -> chats: VERIFY 🔐 {chat.PublicKey}
        handler -> wallet: {content}
    deactivate handler

deactivate wallet

@enduml 
