@startuml Locate
' ------------

'actor User as user  

'box "User Interface (UI)"  #FFFFFF
  participant "Wallet 👱" as wallet
  'participant "Notifier 📣\nbff" as notifier
  participant "Broker 🤵" as broker
'end box

participant "Printer 🖨️" as printer
participant "Finder 🔎" as finder
participant "Host 🤗" as host


wallet --> broker: 1) Locate 🐌

activate broker

    group Resolve, if .ALIAS 🧩 and not cached 

        broker -> printer: 2) Resolve 🚀

    end group

    'alt No host session?

        broker --> wallet: 3) Open 🐌
    deactivate broker
    
    activate wallet
        wallet --> broker: 4) Opened 🐌
    deactivate wallet

    activate broker   

        broker --> finder: 5) 🐌 Help @ Helper     
        deactivate broker
            activate finder
                finder --> wallet: 6) ⏪ Prompt
                finder --> broker: 7) 🐌 Helped @ Consumer 
            deactivate finder
        activate broker

    'end alt

    broker --> wallet: 8) ⏪ Prompt  
    broker --> host:  9) Hello 🐌
deactivate broker

activate host
    host --> wallet: A) ⏪ Prompt 
deactivate host

'    user --> wallet: reply
'deactivate wallet


' ------------
@enduml