@startuml Broker.Pops
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "Pop 🐌" as pop
    participant "Pops 🪣" as pops
    participant "Chats 🪣" as chats
    participant "Chatters 🪣" as chatters
end box


wallet -> pop: Pop 🐌 

activate pop
    pop -> pops: 💾 INSERTED
deactivate pop

activate pops
    pops -> chats: 💾 INSERTED
deactivate pops

activate chats
    chats -> wallet: Open 🐌 {chat.ID}
deactivate chats

activate wallet
    wallet -> chats: 💾 OPENED 
deactivate wallet

activate chats
    chats -> chatters: 💾 POP, broker
deactivate chats

activate chatters
    chatters -> pops: 💾 POPPED
deactivate chatters

activate pops
    pops -> wallet: Prompt 🐌
deactivate pops


@enduml 
