@startuml Subscribe

participant "Streamer 🌬️\ndomain" as streamer

box Subscriber #FFFFFF
    participant "Buffer ⏳\nhelper" as buffer
    participant "Subscriber 🔔\ndomain" as domain
end box

'activate domain
    domain -> buffer: 1) Queue@
    domain --> streamer: 2) Subscribe@
'deactivate domain  

group Stream

    'activate streamer
        streamer --> buffer: 3) Push@
    'deactivate streamer

    activate buffer
        buffer --> domain: 4) Wake-up@
    deactivate buffer

    activate domain

        loop more?
            domain -> buffer: 5) Poll@ 
            domain -> buffer: 6) Confirm@ 
        end loop


end group   

deactivate domain

@enduml