@startuml Subscribe

participant "Streamer 🌬️\ndomain" as streamer

box Subscriber #FFFFFF
    participant "Buffer ⏳\nhelper" as buffer
    participant "Subscriber 🔔\ndomain" as domain
end box


activate streamer
    streamer --> buffer: 1) Updated@
deactivate streamer

activate buffer
    buffer --> domain: 2) Wake-up@
deactivate buffer

activate domain

    loop more?
        domain --> buffer: 3) Consume@ 
    end loop

deactivate domain

@enduml