@startuml Subscribe

participant "Streamer 🌬️\ndomain" as streamer

box Subscriber #FFFFFF
    participant "Buffer ⏳\nhelper" as buffer
    participant "Subscriber 🔔\ndomain" as domain
end box

group Subscribe

    activate domain
        domain --> buffer: 1) Queue 🐌
    deactivate domain

    activate buffer
        buffer --> domain: 2) Queued 🐌
    deactivate buffer

    activate domain
        domain --> streamer: 3) Subscribe 🐌 {buffer, queue}
    deactivate domain  

end group

group Stream

    'activate streamer
        streamer --> buffer: 4) Push 🐌
    'deactivate streamer

    activate buffer
        buffer --> domain: 5) Wake-up 🐌
    deactivate buffer

    activate domain

        loop more?
            domain -> buffer: 6) Poll 🚀
            domain -> buffer: 7) Confirm 🚀
        end loop


end group   

deactivate domain

@enduml