@startuml OnInviteInvited

box Consumer 💼 domain #FFFFFA
    participant "Queries 🪣" as table
    participant "OnInvited 🔔" as handler
end box
participant "Graph 🕸" as graph

table --> handler: INVITED 🔔 

activate handler
    handler -> graph: TRUSTS 🫡 {Helper, Schema}
    handler -x table: SAVE 💾 {UNTRUSTED}
    handler -> table: SAVE 💾 {TRUSTED}
deactivate handler

@enduml 