@startuml Language@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵️ domain #FFFFFA
    participant "Language@  📃" as broker
    participant "Wallets 🪣" as wallets
end box


activate wallet
    wallet --> broker: Language 🐌
deactivate wallet

activate broker
    broker -> wallets: READ {wallet}
    broker -> wallets: SAVE 💾 {language}
deactivate broker


@enduml 