@startuml Localize@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵️ domain #FFFFFA
    participant "Localize 🐌" as broker
    participant "Wallets 🪣" as wallets
end box


activate wallet
    wallet --> broker: Localize 🐌
deactivate wallet

activate broker
    broker -> wallets: READ 🧲
    broker -> wallets: SAVE 💾 {language}
deactivate broker


@enduml 