@startuml OnBindChanges

'participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Script 📃" as script
    participant "Binds 🪣" as binds
    participant "OnChanges 📃" as change
end box

participant "Notifier 📣" as notifier

'wallet --> script: Pop 🐌

activate script
    script -> binds: SAVE 💾, DELETE 🗑️

activate binds
    binds --> change: event 🔔
deactivate binds

activate change
    change --> notifier: SEND 📬 {Updated 🐌}
deactivate change

@enduml 
