@startuml SHARE
 
box Consumer 💼 domain #FFFFFA
    participant "Script 📃" as script
    participant "SHARE ⌘" as talker
    participant "Queries 🪣" as table
end box

participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet
participant "Vault 🗄️" as vault
participant "Identity 🆔" as identity

activate script
    script -> talker: SHARE 💼 {schemas}
deactivate script

activate talker
    talker -> table: SAVE 💾 {schemas}
deactivate talker

activate table
    table --> broker: Query 🐌 
activate broker
    table -> talker
deactivate table

activate talker
    talker -> talker: WAIT 
deactivate talker

    broker --> vault: 
    activate vault

    broker --> wallet: 
deactivate broker
activate wallet

    wallet --> table: Receive 🐌 {token}
deactivate wallet
activate table

    vault --> table: Consume 🐌 {bind}    
deactivate vault

    table -> identity: IDENTIFY 🆔 (if it is an identity-bound token)

    table -> talker: RACE 🏁 {schema, data}
deactivate table

activate talker
    talker -> script: RETURN {schema, data}
deactivate talker

activate script
deactivate script

@enduml 
