@startuml Binds@Broker

 
participant "Wallet 👱" as wallet

box Hosted 📦 domain #FFFFFA
    participant "Broker 🤵" as broker
    participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
end box

activate wallet
wallet -> broker: Binds 🚀

    activate broker
        broker -> wallets: READ {wallet}

        activate wallets
        wallets -> binds: .Binds
        wallets -> broker: 
        deactivate wallets

        broker -> wallet: RETURN {$wallet.Binds}
    deactivate broker

deactivate wallet

@enduml 
