@startuml Translate

' ------------
actor User as user
participant "Wallet 👱\napp" as wallet
participant "Notifier 📣\nbff" as notifier
participant "Broker 🤵\nhost" as broker
participant "Graph 🕸\ndomain" as graph

' ------------
' UI
' ------------
user --> wallet: language
activate wallet
    wallet --> broker: 1) translate@
deactivate wallet

' BROKER
activate broker
    broker -> graph: 2) translate@

    activate graph
        graph -> broker: {translated}
    deactivate graph

    broker -> broker: update
    broker --> notifier: 3) translated@
deactivate broker

' NOTIFIER
activate notifier
    notifier --> wallet
deactivate notifier

' UI
activate wallet
    
    wallet -> broker: 4) chats@
    activate broker
        broker -> wallet: {chats}
    deactivate broker

    wallet -> broker: 5) binds@
    activate broker
        broker -> wallet: {binds}
    deactivate broker

    wallet -> broker: 6) tokens@
    activate broker
        broker -> wallet: {tokens}
    deactivate broker
    
deactivate wallet

' ------------
@enduml