@startuml Consumer@Consumer

participant "Vault 🗄️" as vault
box Consumer 💼 domain #FFFFFA
    participant "Consume 🐌" as consumer
    participant "Queries 🪣" as hooks
end box
participant "Graph 🕸" as graph


vault --> consumer: Consume 🐌 {query, collect}

activate consumer
    consumer -> graph: VERIFY 🔐 {msg}
    consumer -> hooks: READ 🧲 {query}
    consumer -> hooks: SAVE 💾 {CONSUME, collect}
deactivate consumer


@enduml 