@startuml Present

participant "Broker 🤵\nhost" as broker

box "Finder 🔎" #FFFFFA
  participant "Handler 📃" as finder
end box

participant "Reviewer ⭐\nvault" as reviewer
participant "Graph 🕸\ndomain" as graph
'participant "Host 🤗\ndomain" as host


    broker --> finder: 🐌 Help @ Helper 

    activate finder

      finder -> finder: PARALLEL
      activate finder
        finder -> reviewer: SEND: Reviews 🚀
        finder -> graph: SEND: Identity 🚀
        finder -> graph: SEND: Translate 🚀
      deactivate finder
        
      finder --> broker: ⓘ INFO

      finder --> broker: 🐌 Helped @ Consumer 
      
    deactivate finder

  
' ------------
@enduml