@startuml 👉 Printer NFC-QR check-in
' ------------

actor User as user  

box "User Interface (UI)"  #FFFFFF
  participant "Wallet 👱\napp" as wallet
  participant "Notifier 📣\nbff" as notifier
  participant "Broker 🤵\nhost" as broker
end box 

participant "Host 🤗\ndomain" as host
participant "Finder 🔎\nvault" as finder
participant "Printer 🖨️\nsupplier" as printer
participant "Locator 🔆\nNFC/QR" as qr


group Print locators

    host --> finder: {manifest}
    host --> printer: 1) Order@

    activate printer
      printer --> qr: print
    deactivate printer

end group 


user -> wallet: scan ✨

activate wallet
  wallet -> qr: scan ✨
  wallet --> broker: 2) Assess@ {printer locator}
deactivate wallet


activate broker

    group Translate, if not cached

        broker -> printer: 3) Details@

        activate printer
            printer -> broker: {host locator}
        deactivate printer

    end group

    'alt No host session?

        broker --> wallet: 4) ⏪ assessed

        broker --> finder: 5) introduce ⏩
        deactivate broker
        
        activate finder
          finder --> broker
        deactivate finder
        
        activate broker

    'end alt

    broker --> host: 6) Hello@

deactivate broker


activate host
    host --> wallet: 7) ⏪ prompt
deactivate host


' ------------
@enduml