@startuml 👉 Host NFC-QR check-in
' ------------

actor User as user  

box "User Interface (UI)"  #FFFFFF
  participant "Wallet 👱\napp" as wallet
  participant "Notifier 📣\nbff" as notifier
  participant "Broker 🤵\nhost" as broker
end box

participant "Host 🤗\ndomain" as host
participant "Finder 🔎\nvault" as finder
participant "Locator 🔆\nNFC/QR" as qr


group Print locators
    host --> finder: {manifest}
    host --> qr: print
end group

user -> wallet: scan ✨

activate wallet
    wallet -> qr: scan ✨
    wallet --> broker: 1) Assess@ {locator}
deactivate wallet

activate broker

    'alt No host session?

        broker --> wallet: 2) ⏪ assessed

        broker --> finder: 3) introduce ⏩
        deactivate broker
            activate finder
                finder --> broker
            deactivate finder
        activate broker

    'end alt

    broker --> host:  4) Hello@
deactivate broker

activate host
    host --> wallet: 5) ⏪ prompt 
deactivate host

  

' ------------
@enduml