@startuml OnChatDetailed


box Broker 🤵 domain #FFFFFA
    participant "OnInserted 🔔" as script
    participant "Chats 🪣" as table
    participant "OnDetailed 🔔" as handler
end box

participant "Notifier 📣" as notifier
participant "Wallet 👱" as wallet

'wallet --> script: Pop 🐌


activate script
    script -> table: SAVE 💾 {DETAILED}
deactivate script

activate table
    table --> handler: DETAILED 🔔
deactivate table

activate handler
    handler --> notifier: SEND 📬 {Open 🐌}
deactivate handler

activate notifier
    notifier --> wallet: 
deactivate notifier

activate wallet 
    wallet --> table: Opened 🐌 {OPENED}
deactivate wallet

@enduml 
