@startuml OnChatStarted


box Broker 🤵 domain #FFFFFA
    participant "Chatters 🪣" as chatters
    participant "OnBroker 🔔" as script
    participant "Chats 🪣" as chats
    participant "OnStarted 🔔" as handler
end box


chatters --> script: BROKER 🔔

activate script
    script -> chats: SAVE 💾 {STARTED}
deactivate script

activate chats
    chats --> handler: STARTED 🔔
deactivate chats

activate handler
    handler -> chatters: SAVE 💾 {HOST}
deactivate handler

@enduml