@startuml Pop@Vault
' TODO
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    participant "Handler 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
end box

'participant "Vault 🗄️" as vault

activate wallet 
    wallet --> script: Unbind Vault
deactivate wallet

activate script
    script -> binds: READ 🧲
    script --> wallet: CONFIRM {remove?}
deactivate script

activate wallet
    wallet --> script: {yes}
deactivate wallet

activate script
    script --> wallet: ASK {which binds}
deactivate script

activate wallet
    wallet --> script: {selected}
deactivate wallet

activate script
    script -> script: PARALLEL 
    activate script
        script -> binds: DELETE 🗑️ 
        'script --> vault: SEND 📬 {Unbound@}
    deactivate script

    'script --> wallet: SEND 📬 {Updated@}
deactivate script
 
@enduml 
