@startuml OnBindOffered
 
'participant "Wallet 👱" as wallet
participant "Vault 🗄️" as vault

box Broker 🤵 domain #FFFFFA
    participant "Bind@ 📃" as script
    'participant "Wallets 🪣" as wallets
    participant "Binds 🪣" as binds
    participant "OnOffered 🔔" as handler
end box

participant "Graph 🕸" as graph


activate vault
    vault --> script: Bind 🐌
deactivate vault

activate script
    script -> binds: SAVE 💾 {OFFERED}
deactivate script

activate binds
    binds --> handler: OFFERED 🔔
deactivate binds

activate handler
    handler -> graph: TRANSLATE 🈯 
    handler ->  binds: SAVE 💾 {DETAILED}
deactivate handler


@enduml 
