@startuml PopWallet
 
participant "Wallet 👱" as wallet
box Broker 🤵 domain #FFFFFA
    participant "PopWallet 😃" as popped
    participant "Wallets 🪣" as wallets
end box


wallet -> popped: Pop 🎈 {WALLET}

activate popped
    popped -> wallets: SELECT 🧲 
    popped -> wallet: INFO ⓘ {wallet}
    popped -> wallet: ONE 🤔 {what?}
    popped -> : RUN {selection, wallet}
deactivate popped


@enduml 
