@startuml TIME
 
box Talker 😃 domain #FFFFFA
    participant "Script 📃" as script
    participant "TIME 🕓" as many
    participant "PROMPT ⌘" as prompt
    'participant "Host 🤗" as host
    'participant "Consumer 💼" as consumer
end box

'participant "Broker 🤵" as broker
participant "Wallet 👱" as wallet

activate script
    script -> many: TIME 🕓 {text}
deactivate script

activate many
    many -> prompt: RUN 🏃 {text}
deactivate many

activate prompt
    prompt --> wallet: Prompt@Broker 🐌 {text}
deactivate prompt

activate wallet
    wallet --> prompt: {answer}
deactivate wallet

activate prompt
    prompt -> many: RETURN {answer}
deactivate prompt

activate many
    many -> script: RETURN {answer}
deactivate many

activate script
deactivate script

@enduml 
