@startuml Hook

box Talker 😃 domain #FFFFFA
    participant "Script 📃" as inbox
    participant "REEL 🎣" as reel
    participant "Hooks 🪣" as hooks
    participant "Caller 📃" as caller
end box

'activate caller
    caller -> hooks: HOOK 🪝 {uuid}
'deactivate caller

activate inbox
    inbox -> reel:  REEL 🎣 {uuid, result}
deactivate inbox

activate reel
    reel -> hooks: READ 🧲 {uuid}
    
    activate hooks
        hooks -> reel: {script, line}
    deactivate hooks

    reel -> caller: jump to HOOK 🪝 with {result}

deactivate reel

@enduml