@startuml Hook

participant "Domain 👥" as domain

box Talker 😃 domain #FFFFFA
    participant "Inbox 📨" as inbox
    participant ".REEL 📃" as reel
    participant "Hooks 🪣" as hooks
    participant "Imprints 🪣" as imprints
    participant "Caller 📃" as caller
end box


domain --> inbox: 🐌 {hook, out}

activate inbox
    inbox -> reel:  REEL 🎣 {hook, out}
deactivate inbox

activate reel
    reel -> hooks: READ {hook}
    
    activate hooks
        hooks -> reel: {caller, script, holders}
    deactivate hooks

    reel -> imprints: RECALL ⛏️

    reel -> caller: exit {script}  with {out}

deactivate reel

@enduml