@startuml Tokens@Broker

 
participant "Wallet 👱" as wallet

box Broker 🤵️ domain #FFFFFA
    participant "Tokens@ 📃" as broker
    participant "Wallets 🪣" as wallets
    participant "Tokens 🪣" as tokens
end box

activate wallet
wallet -> broker: Tokens 🚀

    activate broker
        broker -> wallets: READ {wallet}
        broker -> tokens: 
        broker -> wallet: RETURN {$wallet.Tokens}
    deactivate broker

deactivate wallet

@enduml 
