@startuml OnDiscloseTrusted


box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as discloses
    participant "OnTrusted 🔔" as handler
end box
participant "Consumer 💼" as consumer



activate discloses
    discloses --> handler: TRUSTED 🔔 
deactivate discloses

activate handler
    handler -> consumer: SEND 📬 {Queried @ Consumer}
    handler -> discloses: UPDATE 💾 {context}
    handler -> discloses: DETAILED ✅
deactivate handler

@enduml 