@startuml OnDiscloseTrusted


box Vault 🗄️ domain #FFFFFA
    participant "Discloses 🪣" as discloses
    participant "OnTrusted 🔔" as handler
end box
participant "Consumer 💼" as consumer



activate discloses
    discloses --> handler: TRUSTED 🔔 
deactivate discloses

activate handler
    handler --> consumer: CALL 🧮 {disclose}
    handler -> discloses: UPDATE 💾 {READY, result}
deactivate handler

@enduml 