@startuml OnTokenRevised
 

'participant "Vault 🗄️" as vault
'participant "Graph 🕸" as graph
participant "Issuer 🎴" as issuer

box Broker 🤵 domain #FFFAFA
    participant "Revise 🐌" as script
    participant "OnLanguage 🔔" as script
    participant "Tokens 🪣" as tokens
    participant "OnRevised 🔔" as onRevised
    participant "Pops 🪣" as pops
    participant "Chats 🪣" as chats
end box

participant "Wallet 👱" as wallet


activate issuer
    issuer --> script: Revise 🐌 {status}
deactivate issuer

activate script
    script -> tokens: SAVE 💾 {status}
deactivate script

activate tokens
    tokens --> onRevised: UPDATED 🔔
deactivate tokens

activate onRevised
    onRevised -> pops: 💾 INSERT
deactivate onRevised

activate pops
    pops -> chats: 💾 INSERT
deactivate pops

activate chats
    chats --> wallet: Open 🐌 
deactivate chats

activate wallet
    wallet --> chats: Opened 🐌
deactivate wallet

activate chats
    chats -> pops: 💾 POPPED
deactivate chats

activate pops
    pops --> wallet: INFO ⓘ {status}
deactivate pops


@enduml 
