@startuml Sub: Replay Updates
' ------------------

participant "Subscriber\nService" as srv
participant "Subscriber\nWebhook" as sub
participant "Publisher\nAPI" as pub

' ------------------
' SUBSCRIBE
' ------------------
srv --> pub: subscribe(filter)

' ------------------
' WARM-UP
' ------------------
srv --> pub: replay(from)
activate pub
pub -> pub: queue()
pub --> sub : load(update[], token)
activate sub
sub -> srv: consume(...)
deactivate sub
activate srv
srv -> srv: save()
srv --> pub: next(token)
deactivate pub
srv -> srv: empty token
deactivate srv

' ------------------
@enduml
