@startuml Translate

' ------------
actor User as user
participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph

' ------------
' UI
' ------------
user --> wallet: language
activate wallet
    wallet --> broker: 1) Translate 🐌
deactivate wallet

' BROKER
activate broker
    broker -> graph: 2) Translate 🚀

    activate graph
        graph -> broker: {translated}
    deactivate graph

    broker --> notifier: 3) Updated 🐌
deactivate broker

' NOTIFIER
activate notifier
    notifier --> wallet
deactivate notifier

' UI
activate wallet    
    wallet -> broker: 4) Frontend 🚀
    activate broker
        broker -> wallet: {frontend}
    deactivate broker    
deactivate wallet

' ------------
@enduml