@startuml Translate

participant "Wallet 👱" as wallet
participant "Notifier 📣" as notifier
participant "Broker 🤵" as broker
participant "Graph 🕸" as graph

activate wallet
    wallet --> broker: 1) Pop 🐌
activate broker
    wallet --> broker: {language}
deactivate wallet
    broker -> graph: 2) Translate 🚀
    broker --> notifier: 3) Updated 🐌
deactivate broker

' NOTIFIER
activate notifier
    notifier --> wallet
deactivate notifier

' UI
activate wallet    
    wallet -> broker: 4) Frontend 🚀
deactivate wallet

' ------------
@enduml