@startuml Charge
' ------------------


box "Broker" #LightGray
    participant "Broker 🤵" as broker
    participant "Biller 🤝" as biller
    participant "Collector 🏦" as collector
end box

box "Participants" #LightSlateGray
    participant "Host 🤗" as host
    participant "Curator 🧚" as curator
end box

box "Advertiser" #LightGray
    participant "Ads 👀" as ads
    participant "Payer 💳" as payer
end box



group register advertiser

    'activate broker
        broker --> biller: contract@
    'deactivate broker    

    activate biller
        biller --> ads: authorize ⏩
    
        activate ads
            ads --> payer: 
            ads --> biller: 
        deactivate ads

    deactivate biller    

end group


'activate broker

group show ads

    activate broker
        broker --> ads: 1) advertise@
        broker --> biller: 2) bill@
    deactivate broker

    activate biller
        
        activate host
            host --> biller: 3) add@
        deactivate host

        activate curator
            curator --> biller: 3) add@
        deactivate curator
   
end group


group monthly billing

        biller --> payer: 4) charge@

    activate payer
        payer --> curator: 5) ⏪ pay
        payer --> host: 5) ⏪ pay
        payer --> collector: 5) ⏪ pay
    deactivate payer

    activate collector
        collector --> biller: 6) paid@
    deactivate collector

    deactivate biller

end group



' ------------
@enduml 