@startuml Pop@Broker
 
participant "Wallet 👱" as wallet

box Broker 🤵 domain #FFFFFA
    'participant "Pop 🐌" as pop
    participant "Pops 🪣" as pops
    participant "Popped@ 🔔" as popped
    participant "Hello 🐌" as introduced
end box

box "Talker 😃" #FFFFFA
    participant "Engine ⚙️" as engine
    participant "Talkers 🪣" as talkers
end box

'participant "Vault 🗄️" as vault

'activate wallet 
    wallet --> pops: Pop 🐌 
'deactivate wallet

'activate pops
'    pops -> pop
'deactivate pops

activate pops
    pops --> popped: INSERTED 🔔
deactivate pops

activate popped
    popped -> engine: REGISTER 🔆 {script}
deactivate popped

activate engine
    engine -> talkers: SAVE 💾
    engine -> popped: {locator}
deactivate engine

activate popped
    popped --> wallet: SEND 📬 Assess 🐌
deactivate popped

'activate wallet
'    wallet --> locate: Locate 🐌 {locator}
'deactivate wallet

'activate locate
'    locate --> wallet: SEND 📬 Open 🐌 {locator}
'deactivate locate


activate wallet
    wallet --> introduced:
deactivate wallet

activate introduced
    'introduced -> engine: CHAT 💬
    introduced -> engine: TALK 😃
deactivate introduced

'activate popX
'deactivate popX

activate engine
    engine -> talkers: READ 🧲
    engine -> : RUN 🏃 {script} 
deactivate engine

@enduml 
