@startuml
' ----------------------
actor User as user
participant "Wallet\n(app)" as ui
participant "Notifier\n(domain)" as api
participant "Broker\n(domain)" as aws
participant "Seller\n(host)" as seller
participant "Payer\n(vault)" as payer
participant "Collector\n(domain)" as collector
participant "Graph\n(backbone)" as graph
' ----------------------
' REGISTER COLLECTOR
' ----------------------
seller --> collector: register()
' ----------------------
' ENDORSE
' ----------------------
user --> ui: pay(payer)
activate ui
ui --> payer: endorse(request, collector)
deactivate ui
' ----------------------
' SELECT METHOD
' ----------------------
activate payer
payer -> payer: validate(wallet)
payer -> graph: trust(collector)?
payer --> aws: prompt(method?)
deactivate payer
user --> payer: prompt answer: {method}
' ----------------------
' TWO FACTOR OTP
' ----------------------
activate payer
payer --> user: SMS(one time password)
payer --> aws: prompt(OTP?)
deactivate payer
user --> payer: prompt answer: {OTP}
' ----------------------
' COLLECT
' ----------------------
activate payer
payer -> payer: pay()
payer --> collector: collect()
activate collector
' ----------------------
' SUCCESS CONFIRMATION
' ----------------------
payer --> aws: prompt(success!)
deactivate payer
' ----------------------
collector -> graph: trust(payer)?
collector --> seller: paid()
deactivate collector
' ----------------------
activate seller
seller --> aws: prompt(receipt!)
seller --> aws: goodbye()
deactivate seller
' ----------------------
@enduml 