@startuml IDENTIFY
 
box Consumer 💼 domain #FFFFFA
    participant "Script 📃" as script
    participant "IDENTIFY 🆔" as identify
    participant "Identified 🐌" as identified
end box
participant "Broker 🤵" as broker
participant "Identifier 🆔" as identity
participant "Wallet 👱" as wallet


activate script
    script -> identify: IDENTIFY 🆔 {token}
deactivate script

activate identify
    identify --> broker: SEND 📬 Identify@Broker 🐌 {identity, biostamp, hook}
activate broker
    identify -> identify: WAIT ⏳ {hook}
deactivate identify

    broker --> identity: INVITE 🤲 
deactivate broker

activate identity
    identity --> wallet: 
    identity --> broker: 
deactivate identity

activate broker
    broker --> identified: Identified@Consumer 🐌 {hook}
deactivate broker

activate identified 
    identified --> identify: RACE 🏁 {hook}
deactivate identified

activate identify
    identify -> script
deactivate identify

activate script
deactivate script

@enduml 
