@startuml Bind()

 
participant "Vault 🗄️" as vault

box Broker 🤵 domain  #FFFFFA
    participant "Bind 🐌" as broker
    'participant "Talker 😃" as talker
    'participant "Script 📃" as script
    participant "Chats 🪣" as chats
    participant "Binds 🪣" as binds
end box
participant "Graph 🕸" as graph



vault --> broker: Bind 🐌 
deactivate vault    

activate broker
    broker -> graph: VERIFY 🔐 {msg}
    broker -> chats: READ 🧲 
    broker -> binds: SAVE 💾 {OFFERED}
deactivate broker


@enduml 
